// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: proto/gamesync/v1/gamesync.proto

package gamesync

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Gamesync_IssueToken_FullMethodName          = "/nn.npln.gamesync.v1.Gamesync/IssueToken"
	Gamesync_RefreshToken_FullMethodName        = "/nn.npln.gamesync.v1.Gamesync/RefreshToken"
	Gamesync_GetDocument_FullMethodName         = "/nn.npln.gamesync.v1.Gamesync/GetDocument"
	Gamesync_ReadDocuments_FullMethodName       = "/nn.npln.gamesync.v1.Gamesync/ReadDocuments"
	Gamesync_ListDocuments_FullMethodName       = "/nn.npln.gamesync.v1.Gamesync/ListDocuments"
	Gamesync_QueryCollectionIds_FullMethodName  = "/nn.npln.gamesync.v1.Gamesync/QueryCollectionIds"
	Gamesync_WriteDocuments_FullMethodName      = "/nn.npln.gamesync.v1.Gamesync/WriteDocuments"
	Gamesync_LazyWriteDocuments_FullMethodName  = "/nn.npln.gamesync.v1.Gamesync/LazyWriteDocuments"
	Gamesync_BeginTransaction_FullMethodName    = "/nn.npln.gamesync.v1.Gamesync/BeginTransaction"
	Gamesync_CommitTransaction_FullMethodName   = "/nn.npln.gamesync.v1.Gamesync/CommitTransaction"
	Gamesync_RollbackTransaction_FullMethodName = "/nn.npln.gamesync.v1.Gamesync/RollbackTransaction"
	Gamesync_KeepUserSession_FullMethodName     = "/nn.npln.gamesync.v1.Gamesync/KeepUserSession"
	Gamesync_CreateRound_FullMethodName         = "/nn.npln.gamesync.v1.Gamesync/CreateRound"
)

// GamesyncClient is the client API for Gamesync service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GamesyncClient interface {
	IssueToken(ctx context.Context, in *IssueTokenRequest, opts ...grpc.CallOption) (*IssueTokenResponse, error)
	RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error)
	GetDocument(ctx context.Context, in *GetDocumentRequest, opts ...grpc.CallOption) (*Document, error)
	ReadDocuments(ctx context.Context, in *ReadDocumentsRequest, opts ...grpc.CallOption) (*ReadDocumentsResponse, error)
	ListDocuments(ctx context.Context, in *ListDocumentsRequest, opts ...grpc.CallOption) (*ListDocumentsResponse, error)
	QueryCollectionIds(ctx context.Context, in *QueryCollectionIdsRequest, opts ...grpc.CallOption) (*QueryCollectionIdsResponse, error)
	WriteDocuments(ctx context.Context, in *WriteDocumentsRequest, opts ...grpc.CallOption) (*WriteDocumentsResponse, error)
	LazyWriteDocuments(ctx context.Context, in *LazyWriteDocumentsRequest, opts ...grpc.CallOption) (*LazyWriteDocumentsResponse, error)
	BeginTransaction(ctx context.Context, in *BeginTransactionRequest, opts ...grpc.CallOption) (*BeginTransactionResponse, error)
	CommitTransaction(ctx context.Context, in *CommitTransactionRequest, opts ...grpc.CallOption) (*CommitTransactionResponse, error)
	RollbackTransaction(ctx context.Context, in *RollbackTransactionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	KeepUserSession(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[KeepUserSessionRequest, KeepUserSessionResponse], error)
	CreateRound(ctx context.Context, in *CreateRoundRequest, opts ...grpc.CallOption) (*Round, error)
}

type gamesyncClient struct {
	cc grpc.ClientConnInterface
}

func NewGamesyncClient(cc grpc.ClientConnInterface) GamesyncClient {
	return &gamesyncClient{cc}
}

func (c *gamesyncClient) IssueToken(ctx context.Context, in *IssueTokenRequest, opts ...grpc.CallOption) (*IssueTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssueTokenResponse)
	err := c.cc.Invoke(ctx, Gamesync_IssueToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamesyncClient) RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshTokenResponse)
	err := c.cc.Invoke(ctx, Gamesync_RefreshToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamesyncClient) GetDocument(ctx context.Context, in *GetDocumentRequest, opts ...grpc.CallOption) (*Document, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Document)
	err := c.cc.Invoke(ctx, Gamesync_GetDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamesyncClient) ReadDocuments(ctx context.Context, in *ReadDocumentsRequest, opts ...grpc.CallOption) (*ReadDocumentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadDocumentsResponse)
	err := c.cc.Invoke(ctx, Gamesync_ReadDocuments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamesyncClient) ListDocuments(ctx context.Context, in *ListDocumentsRequest, opts ...grpc.CallOption) (*ListDocumentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDocumentsResponse)
	err := c.cc.Invoke(ctx, Gamesync_ListDocuments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamesyncClient) QueryCollectionIds(ctx context.Context, in *QueryCollectionIdsRequest, opts ...grpc.CallOption) (*QueryCollectionIdsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryCollectionIdsResponse)
	err := c.cc.Invoke(ctx, Gamesync_QueryCollectionIds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamesyncClient) WriteDocuments(ctx context.Context, in *WriteDocumentsRequest, opts ...grpc.CallOption) (*WriteDocumentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteDocumentsResponse)
	err := c.cc.Invoke(ctx, Gamesync_WriteDocuments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamesyncClient) LazyWriteDocuments(ctx context.Context, in *LazyWriteDocumentsRequest, opts ...grpc.CallOption) (*LazyWriteDocumentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LazyWriteDocumentsResponse)
	err := c.cc.Invoke(ctx, Gamesync_LazyWriteDocuments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamesyncClient) BeginTransaction(ctx context.Context, in *BeginTransactionRequest, opts ...grpc.CallOption) (*BeginTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BeginTransactionResponse)
	err := c.cc.Invoke(ctx, Gamesync_BeginTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamesyncClient) CommitTransaction(ctx context.Context, in *CommitTransactionRequest, opts ...grpc.CallOption) (*CommitTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitTransactionResponse)
	err := c.cc.Invoke(ctx, Gamesync_CommitTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamesyncClient) RollbackTransaction(ctx context.Context, in *RollbackTransactionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Gamesync_RollbackTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamesyncClient) KeepUserSession(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[KeepUserSessionRequest, KeepUserSessionResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Gamesync_ServiceDesc.Streams[0], Gamesync_KeepUserSession_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[KeepUserSessionRequest, KeepUserSessionResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Gamesync_KeepUserSessionClient = grpc.BidiStreamingClient[KeepUserSessionRequest, KeepUserSessionResponse]

func (c *gamesyncClient) CreateRound(ctx context.Context, in *CreateRoundRequest, opts ...grpc.CallOption) (*Round, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Round)
	err := c.cc.Invoke(ctx, Gamesync_CreateRound_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GamesyncServer is the server API for Gamesync service.
// All implementations must embed UnimplementedGamesyncServer
// for forward compatibility.
type GamesyncServer interface {
	IssueToken(context.Context, *IssueTokenRequest) (*IssueTokenResponse, error)
	RefreshToken(context.Context, *RefreshTokenRequest) (*RefreshTokenResponse, error)
	GetDocument(context.Context, *GetDocumentRequest) (*Document, error)
	ReadDocuments(context.Context, *ReadDocumentsRequest) (*ReadDocumentsResponse, error)
	ListDocuments(context.Context, *ListDocumentsRequest) (*ListDocumentsResponse, error)
	QueryCollectionIds(context.Context, *QueryCollectionIdsRequest) (*QueryCollectionIdsResponse, error)
	WriteDocuments(context.Context, *WriteDocumentsRequest) (*WriteDocumentsResponse, error)
	LazyWriteDocuments(context.Context, *LazyWriteDocumentsRequest) (*LazyWriteDocumentsResponse, error)
	BeginTransaction(context.Context, *BeginTransactionRequest) (*BeginTransactionResponse, error)
	CommitTransaction(context.Context, *CommitTransactionRequest) (*CommitTransactionResponse, error)
	RollbackTransaction(context.Context, *RollbackTransactionRequest) (*emptypb.Empty, error)
	KeepUserSession(grpc.BidiStreamingServer[KeepUserSessionRequest, KeepUserSessionResponse]) error
	CreateRound(context.Context, *CreateRoundRequest) (*Round, error)
	mustEmbedUnimplementedGamesyncServer()
}

// UnimplementedGamesyncServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGamesyncServer struct{}

func (UnimplementedGamesyncServer) IssueToken(context.Context, *IssueTokenRequest) (*IssueTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IssueToken not implemented")
}
func (UnimplementedGamesyncServer) RefreshToken(context.Context, *RefreshTokenRequest) (*RefreshTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshToken not implemented")
}
func (UnimplementedGamesyncServer) GetDocument(context.Context, *GetDocumentRequest) (*Document, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDocument not implemented")
}
func (UnimplementedGamesyncServer) ReadDocuments(context.Context, *ReadDocumentsRequest) (*ReadDocumentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadDocuments not implemented")
}
func (UnimplementedGamesyncServer) ListDocuments(context.Context, *ListDocumentsRequest) (*ListDocumentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDocuments not implemented")
}
func (UnimplementedGamesyncServer) QueryCollectionIds(context.Context, *QueryCollectionIdsRequest) (*QueryCollectionIdsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryCollectionIds not implemented")
}
func (UnimplementedGamesyncServer) WriteDocuments(context.Context, *WriteDocumentsRequest) (*WriteDocumentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteDocuments not implemented")
}
func (UnimplementedGamesyncServer) LazyWriteDocuments(context.Context, *LazyWriteDocumentsRequest) (*LazyWriteDocumentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LazyWriteDocuments not implemented")
}
func (UnimplementedGamesyncServer) BeginTransaction(context.Context, *BeginTransactionRequest) (*BeginTransactionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BeginTransaction not implemented")
}
func (UnimplementedGamesyncServer) CommitTransaction(context.Context, *CommitTransactionRequest) (*CommitTransactionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CommitTransaction not implemented")
}
func (UnimplementedGamesyncServer) RollbackTransaction(context.Context, *RollbackTransactionRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RollbackTransaction not implemented")
}
func (UnimplementedGamesyncServer) KeepUserSession(grpc.BidiStreamingServer[KeepUserSessionRequest, KeepUserSessionResponse]) error {
	return status.Error(codes.Unimplemented, "method KeepUserSession not implemented")
}
func (UnimplementedGamesyncServer) CreateRound(context.Context, *CreateRoundRequest) (*Round, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRound not implemented")
}
func (UnimplementedGamesyncServer) mustEmbedUnimplementedGamesyncServer() {}
func (UnimplementedGamesyncServer) testEmbeddedByValue()                  {}

// UnsafeGamesyncServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GamesyncServer will
// result in compilation errors.
type UnsafeGamesyncServer interface {
	mustEmbedUnimplementedGamesyncServer()
}

func RegisterGamesyncServer(s grpc.ServiceRegistrar, srv GamesyncServer) {
	// If the following call panics, it indicates UnimplementedGamesyncServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Gamesync_ServiceDesc, srv)
}

func _Gamesync_IssueToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamesyncServer).IssueToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gamesync_IssueToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamesyncServer).IssueToken(ctx, req.(*IssueTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gamesync_RefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamesyncServer).RefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gamesync_RefreshToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamesyncServer).RefreshToken(ctx, req.(*RefreshTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gamesync_GetDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamesyncServer).GetDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gamesync_GetDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamesyncServer).GetDocument(ctx, req.(*GetDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gamesync_ReadDocuments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadDocumentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamesyncServer).ReadDocuments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gamesync_ReadDocuments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamesyncServer).ReadDocuments(ctx, req.(*ReadDocumentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gamesync_ListDocuments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDocumentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamesyncServer).ListDocuments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gamesync_ListDocuments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamesyncServer).ListDocuments(ctx, req.(*ListDocumentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gamesync_QueryCollectionIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCollectionIdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamesyncServer).QueryCollectionIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gamesync_QueryCollectionIds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamesyncServer).QueryCollectionIds(ctx, req.(*QueryCollectionIdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gamesync_WriteDocuments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteDocumentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamesyncServer).WriteDocuments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gamesync_WriteDocuments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamesyncServer).WriteDocuments(ctx, req.(*WriteDocumentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gamesync_LazyWriteDocuments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LazyWriteDocumentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamesyncServer).LazyWriteDocuments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gamesync_LazyWriteDocuments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamesyncServer).LazyWriteDocuments(ctx, req.(*LazyWriteDocumentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gamesync_BeginTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeginTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamesyncServer).BeginTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gamesync_BeginTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamesyncServer).BeginTransaction(ctx, req.(*BeginTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gamesync_CommitTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamesyncServer).CommitTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gamesync_CommitTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamesyncServer).CommitTransaction(ctx, req.(*CommitTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gamesync_RollbackTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamesyncServer).RollbackTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gamesync_RollbackTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamesyncServer).RollbackTransaction(ctx, req.(*RollbackTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gamesync_KeepUserSession_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GamesyncServer).KeepUserSession(&grpc.GenericServerStream[KeepUserSessionRequest, KeepUserSessionResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Gamesync_KeepUserSessionServer = grpc.BidiStreamingServer[KeepUserSessionRequest, KeepUserSessionResponse]

func _Gamesync_CreateRound_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRoundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamesyncServer).CreateRound(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gamesync_CreateRound_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamesyncServer).CreateRound(ctx, req.(*CreateRoundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Gamesync_ServiceDesc is the grpc.ServiceDesc for Gamesync service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Gamesync_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nn.npln.gamesync.v1.Gamesync",
	HandlerType: (*GamesyncServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IssueToken",
			Handler:    _Gamesync_IssueToken_Handler,
		},
		{
			MethodName: "RefreshToken",
			Handler:    _Gamesync_RefreshToken_Handler,
		},
		{
			MethodName: "GetDocument",
			Handler:    _Gamesync_GetDocument_Handler,
		},
		{
			MethodName: "ReadDocuments",
			Handler:    _Gamesync_ReadDocuments_Handler,
		},
		{
			MethodName: "ListDocuments",
			Handler:    _Gamesync_ListDocuments_Handler,
		},
		{
			MethodName: "QueryCollectionIds",
			Handler:    _Gamesync_QueryCollectionIds_Handler,
		},
		{
			MethodName: "WriteDocuments",
			Handler:    _Gamesync_WriteDocuments_Handler,
		},
		{
			MethodName: "LazyWriteDocuments",
			Handler:    _Gamesync_LazyWriteDocuments_Handler,
		},
		{
			MethodName: "BeginTransaction",
			Handler:    _Gamesync_BeginTransaction_Handler,
		},
		{
			MethodName: "CommitTransaction",
			Handler:    _Gamesync_CommitTransaction_Handler,
		},
		{
			MethodName: "RollbackTransaction",
			Handler:    _Gamesync_RollbackTransaction_Handler,
		},
		{
			MethodName: "CreateRound",
			Handler:    _Gamesync_CreateRound_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "KeepUserSession",
			Handler:       _Gamesync_KeepUserSession_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/gamesync/v1/gamesync.proto",
}
