// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/gamesync/v1/gamesync.proto

package gamesync

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IssueTokenRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	UserSession        string                 `protobuf:"bytes,1,opt,name=user_session,json=userSession,proto3" json:"user_session,omitempty"`
	MatchmakingIdToken string                 `protobuf:"bytes,2,opt,name=matchmaking_id_token,json=matchmakingIdToken,proto3" json:"matchmaking_id_token,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *IssueTokenRequest) Reset() {
	*x = IssueTokenRequest{}
	mi := &file_proto_gamesync_v1_gamesync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueTokenRequest) ProtoMessage() {}

func (x *IssueTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gamesync_v1_gamesync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueTokenRequest.ProtoReflect.Descriptor instead.
func (*IssueTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_gamesync_v1_gamesync_proto_rawDescGZIP(), []int{0}
}

func (x *IssueTokenRequest) GetUserSession() string {
	if x != nil {
		return x.UserSession
	}
	return ""
}

func (x *IssueTokenRequest) GetMatchmakingIdToken() string {
	if x != nil {
		return x.MatchmakingIdToken
	}
	return ""
}

type IssueTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         *Token                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueTokenResponse) Reset() {
	*x = IssueTokenResponse{}
	mi := &file_proto_gamesync_v1_gamesync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueTokenResponse) ProtoMessage() {}

func (x *IssueTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gamesync_v1_gamesync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueTokenResponse.ProtoReflect.Descriptor instead.
func (*IssueTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_gamesync_v1_gamesync_proto_rawDescGZIP(), []int{1}
}

func (x *IssueTokenResponse) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserSession   string                 `protobuf:"bytes,1,opt,name=user_session,json=userSession,proto3" json:"user_session,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_proto_gamesync_v1_gamesync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gamesync_v1_gamesync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_gamesync_v1_gamesync_proto_rawDescGZIP(), []int{2}
}

func (x *RefreshTokenRequest) GetUserSession() string {
	if x != nil {
		return x.UserSession
	}
	return ""
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         *Token                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_proto_gamesync_v1_gamesync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gamesync_v1_gamesync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_gamesync_v1_gamesync_proto_rawDescGZIP(), []int{3}
}

func (x *RefreshTokenResponse) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

type GetDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ReadMask      *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=read_mask,json=readMask,proto3" json:"read_mask,omitempty"`
	Transaction   []byte                 `protobuf:"bytes,3,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentRequest) Reset() {
	*x = GetDocumentRequest{}
	mi := &file_proto_gamesync_v1_gamesync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentRequest) ProtoMessage() {}

func (x *GetDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gamesync_v1_gamesync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentRequest.ProtoReflect.Descriptor instead.
func (*GetDocumentRequest) Descriptor() ([]byte, []int) {
	return file_proto_gamesync_v1_gamesync_proto_rawDescGZIP(), []int{4}
}

func (x *GetDocumentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetDocumentRequest) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

func (x *GetDocumentRequest) GetTransaction() []byte {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type ReadDocumentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Documents     []string               `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	ReadMask      *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=read_mask,json=readMask,proto3" json:"read_mask,omitempty"`
	Transaction   []byte                 `protobuf:"bytes,3,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadDocumentsRequest) Reset() {
	*x = ReadDocumentsRequest{}
	mi := &file_proto_gamesync_v1_gamesync_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadDocumentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadDocumentsRequest) ProtoMessage() {}

func (x *ReadDocumentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gamesync_v1_gamesync_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadDocumentsRequest.ProtoReflect.Descriptor instead.
func (*ReadDocumentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_gamesync_v1_gamesync_proto_rawDescGZIP(), []int{5}
}

func (x *ReadDocumentsRequest) GetDocuments() []string {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *ReadDocumentsRequest) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

func (x *ReadDocumentsRequest) GetTransaction() []byte {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type ReadDocumentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*ReadResult          `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	ReadTime      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=read_time,json=readTime,proto3" json:"read_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadDocumentsResponse) Reset() {
	*x = ReadDocumentsResponse{}
	mi := &file_proto_gamesync_v1_gamesync_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadDocumentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadDocumentsResponse) ProtoMessage() {}

func (x *ReadDocumentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gamesync_v1_gamesync_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadDocumentsResponse.ProtoReflect.Descriptor instead.
func (*ReadDocumentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_gamesync_v1_gamesync_proto_rawDescGZIP(), []int{6}
}

func (x *ReadDocumentsResponse) GetResults() []*ReadResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ReadDocumentsResponse) GetReadTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ReadTime
	}
	return nil
}

type ListDocumentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parent        string                 `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	ReadMask      *fieldmaskpb.FieldMask `protobuf:"bytes,4,opt,name=read_mask,json=readMask,proto3" json:"read_mask,omitempty"`
	ShowMissing   bool                   `protobuf:"varint,5,opt,name=show_missing,json=showMissing,proto3" json:"show_missing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDocumentsRequest) Reset() {
	*x = ListDocumentsRequest{}
	mi := &file_proto_gamesync_v1_gamesync_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDocumentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDocumentsRequest) ProtoMessage() {}

func (x *ListDocumentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gamesync_v1_gamesync_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDocumentsRequest.ProtoReflect.Descriptor instead.
func (*ListDocumentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_gamesync_v1_gamesync_proto_rawDescGZIP(), []int{7}
}

func (x *ListDocumentsRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ListDocumentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListDocumentsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListDocumentsRequest) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

func (x *ListDocumentsRequest) GetShowMissing() bool {
	if x != nil {
		return x.ShowMissing
	}
	return false
}

type ListDocumentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Documents     []*Document            `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDocumentsResponse) Reset() {
	*x = ListDocumentsResponse{}
	mi := &file_proto_gamesync_v1_gamesync_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDocumentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDocumentsResponse) ProtoMessage() {}

func (x *ListDocumentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gamesync_v1_gamesync_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDocumentsResponse.ProtoReflect.Descriptor instead.
func (*ListDocumentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_gamesync_v1_gamesync_proto_rawDescGZIP(), []int{8}
}

func (x *ListDocumentsResponse) GetDocuments() []*Document {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *ListDocumentsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type QueryCollectionIdsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Document      string                 `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryCollectionIdsRequest) Reset() {
	*x = QueryCollectionIdsRequest{}
	mi := &file_proto_gamesync_v1_gamesync_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryCollectionIdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryCollectionIdsRequest) ProtoMessage() {}

func (x *QueryCollectionIdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gamesync_v1_gamesync_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryCollectionIdsRequest.ProtoReflect.Descriptor instead.
func (*QueryCollectionIdsRequest) Descriptor() ([]byte, []int) {
	return file_proto_gamesync_v1_gamesync_proto_rawDescGZIP(), []int{9}
}

func (x *QueryCollectionIdsRequest) GetDocument() string {
	if x != nil {
		return x.Document
	}
	return ""
}

func (x *QueryCollectionIdsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *QueryCollectionIdsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type QueryCollectionIdsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CollectionIds []string               `protobuf:"bytes,1,rep,name=collection_ids,json=collectionIds,proto3" json:"collection_ids,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryCollectionIdsResponse) Reset() {
	*x = QueryCollectionIdsResponse{}
	mi := &file_proto_gamesync_v1_gamesync_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryCollectionIdsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryCollectionIdsResponse) ProtoMessage() {}

func (x *QueryCollectionIdsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gamesync_v1_gamesync_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryCollectionIdsResponse.ProtoReflect.Descriptor instead.
func (*QueryCollectionIdsResponse) Descriptor() ([]byte, []int) {
	return file_proto_gamesync_v1_gamesync_proto_rawDescGZIP(), []int{10}
}

func (x *QueryCollectionIdsResponse) GetCollectionIds() []string {
	if x != nil {
		return x.CollectionIds
	}
	return nil
}

func (x *QueryCollectionIdsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type WriteDocumentsRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	WriteOperations     []*WriteOperation      `protobuf:"bytes,1,rep,name=write_operations,json=writeOperations,proto3" json:"write_operations,omitempty"`
	DefermentOperations []*DefermentOperation  `protobuf:"bytes,2,rep,name=deferment_operations,json=defermentOperations,proto3" json:"deferment_operations,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *WriteDocumentsRequest) Reset() {
	*x = WriteDocumentsRequest{}
	mi := &file_proto_gamesync_v1_gamesync_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteDocumentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteDocumentsRequest) ProtoMessage() {}

func (x *WriteDocumentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gamesync_v1_gamesync_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteDocumentsRequest.ProtoReflect.Descriptor instead.
func (*WriteDocumentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_gamesync_v1_gamesync_proto_rawDescGZIP(), []int{11}
}

func (x *WriteDocumentsRequest) GetWriteOperations() []*WriteOperation {
	if x != nil {
		return x.WriteOperations
	}
	return nil
}

func (x *WriteDocumentsRequest) GetDefermentOperations() []*DefermentOperation {
	if x != nil {
		return x.DefermentOperations
	}
	return nil
}

type WriteDocumentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WriteResults  []*WriteResult         `protobuf:"bytes,1,rep,name=write_results,json=writeResults,proto3" json:"write_results,omitempty"`
	CommitTime    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=commit_time,json=commitTime,proto3" json:"commit_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteDocumentsResponse) Reset() {
	*x = WriteDocumentsResponse{}
	mi := &file_proto_gamesync_v1_gamesync_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteDocumentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteDocumentsResponse) ProtoMessage() {}

func (x *WriteDocumentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gamesync_v1_gamesync_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteDocumentsResponse.ProtoReflect.Descriptor instead.
func (*WriteDocumentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_gamesync_v1_gamesync_proto_rawDescGZIP(), []int{12}
}

func (x *WriteDocumentsResponse) GetWriteResults() []*WriteResult {
	if x != nil {
		return x.WriteResults
	}
	return nil
}

func (x *WriteDocumentsResponse) GetCommitTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CommitTime
	}
	return nil
}

type LazyWriteDocumentsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WriteOperations []*LazyWriteOperation  `protobuf:"bytes,1,rep,name=write_operations,json=writeOperations,proto3" json:"write_operations,omitempty"`
	LazyWriteConfig string                 `protobuf:"bytes,2,opt,name=lazy_write_config,json=lazyWriteConfig,proto3" json:"lazy_write_config,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LazyWriteDocumentsRequest) Reset() {
	*x = LazyWriteDocumentsRequest{}
	mi := &file_proto_gamesync_v1_gamesync_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LazyWriteDocumentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LazyWriteDocumentsRequest) ProtoMessage() {}

func (x *LazyWriteDocumentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gamesync_v1_gamesync_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LazyWriteDocumentsRequest.ProtoReflect.Descriptor instead.
func (*LazyWriteDocumentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_gamesync_v1_gamesync_proto_rawDescGZIP(), []int{13}
}

func (x *LazyWriteDocumentsRequest) GetWriteOperations() []*LazyWriteOperation {
	if x != nil {
		return x.WriteOperations
	}
	return nil
}

func (x *LazyWriteDocumentsRequest) GetLazyWriteConfig() string {
	if x != nil {
		return x.LazyWriteConfig
	}
	return ""
}

type LazyWriteDocumentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommitTime    *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=commit_time,json=commitTime,proto3" json:"commit_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LazyWriteDocumentsResponse) Reset() {
	*x = LazyWriteDocumentsResponse{}
	mi := &file_proto_gamesync_v1_gamesync_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LazyWriteDocumentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LazyWriteDocumentsResponse) ProtoMessage() {}

func (x *LazyWriteDocumentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gamesync_v1_gamesync_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LazyWriteDocumentsResponse.ProtoReflect.Descriptor instead.
func (*LazyWriteDocumentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_gamesync_v1_gamesync_proto_rawDescGZIP(), []int{14}
}

func (x *LazyWriteDocumentsResponse) GetCommitTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CommitTime
	}
	return nil
}

type BeginTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginTransactionRequest) Reset() {
	*x = BeginTransactionRequest{}
	mi := &file_proto_gamesync_v1_gamesync_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginTransactionRequest) ProtoMessage() {}

func (x *BeginTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gamesync_v1_gamesync_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginTransactionRequest.ProtoReflect.Descriptor instead.
func (*BeginTransactionRequest) Descriptor() ([]byte, []int) {
	return file_proto_gamesync_v1_gamesync_proto_rawDescGZIP(), []int{15}
}

type BeginTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   []byte                 `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginTransactionResponse) Reset() {
	*x = BeginTransactionResponse{}
	mi := &file_proto_gamesync_v1_gamesync_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginTransactionResponse) ProtoMessage() {}

func (x *BeginTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gamesync_v1_gamesync_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginTransactionResponse.ProtoReflect.Descriptor instead.
func (*BeginTransactionResponse) Descriptor() ([]byte, []int) {
	return file_proto_gamesync_v1_gamesync_proto_rawDescGZIP(), []int{16}
}

func (x *BeginTransactionResponse) GetTransaction() []byte {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type CommitTransactionRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	WriteOperations     []*WriteOperation      `protobuf:"bytes,1,rep,name=write_operations,json=writeOperations,proto3" json:"write_operations,omitempty"`
	DefermentOperations []*DefermentOperation  `protobuf:"bytes,2,rep,name=deferment_operations,json=defermentOperations,proto3" json:"deferment_operations,omitempty"`
	Transaction         []byte                 `protobuf:"bytes,3,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CommitTransactionRequest) Reset() {
	*x = CommitTransactionRequest{}
	mi := &file_proto_gamesync_v1_gamesync_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitTransactionRequest) ProtoMessage() {}

func (x *CommitTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gamesync_v1_gamesync_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitTransactionRequest.ProtoReflect.Descriptor instead.
func (*CommitTransactionRequest) Descriptor() ([]byte, []int) {
	return file_proto_gamesync_v1_gamesync_proto_rawDescGZIP(), []int{17}
}

func (x *CommitTransactionRequest) GetWriteOperations() []*WriteOperation {
	if x != nil {
		return x.WriteOperations
	}
	return nil
}

func (x *CommitTransactionRequest) GetDefermentOperations() []*DefermentOperation {
	if x != nil {
		return x.DefermentOperations
	}
	return nil
}

func (x *CommitTransactionRequest) GetTransaction() []byte {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type CommitTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WriteResults  []*WriteResult         `protobuf:"bytes,1,rep,name=write_results,json=writeResults,proto3" json:"write_results,omitempty"`
	CommitTime    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=commit_time,json=commitTime,proto3" json:"commit_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitTransactionResponse) Reset() {
	*x = CommitTransactionResponse{}
	mi := &file_proto_gamesync_v1_gamesync_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitTransactionResponse) ProtoMessage() {}

func (x *CommitTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gamesync_v1_gamesync_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitTransactionResponse.ProtoReflect.Descriptor instead.
func (*CommitTransactionResponse) Descriptor() ([]byte, []int) {
	return file_proto_gamesync_v1_gamesync_proto_rawDescGZIP(), []int{18}
}

func (x *CommitTransactionResponse) GetWriteResults() []*WriteResult {
	if x != nil {
		return x.WriteResults
	}
	return nil
}

func (x *CommitTransactionResponse) GetCommitTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CommitTime
	}
	return nil
}

type RollbackTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   []byte                 `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackTransactionRequest) Reset() {
	*x = RollbackTransactionRequest{}
	mi := &file_proto_gamesync_v1_gamesync_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackTransactionRequest) ProtoMessage() {}

func (x *RollbackTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gamesync_v1_gamesync_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackTransactionRequest.ProtoReflect.Descriptor instead.
func (*RollbackTransactionRequest) Descriptor() ([]byte, []int) {
	return file_proto_gamesync_v1_gamesync_proto_rawDescGZIP(), []int{19}
}

func (x *RollbackTransactionRequest) GetTransaction() []byte {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type KeepUserSessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to RequestType:
	//
	//	*KeepUserSessionRequest_Echo
	//	*KeepUserSessionRequest_UpdateTarget
	//	*KeepUserSessionRequest_DeleteTarget
	RequestType   isKeepUserSessionRequest_RequestType `protobuf_oneof:"request_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeepUserSessionRequest) Reset() {
	*x = KeepUserSessionRequest{}
	mi := &file_proto_gamesync_v1_gamesync_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeepUserSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeepUserSessionRequest) ProtoMessage() {}

func (x *KeepUserSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gamesync_v1_gamesync_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeepUserSessionRequest.ProtoReflect.Descriptor instead.
func (*KeepUserSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_gamesync_v1_gamesync_proto_rawDescGZIP(), []int{20}
}

func (x *KeepUserSessionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KeepUserSessionRequest) GetRequestType() isKeepUserSessionRequest_RequestType {
	if x != nil {
		return x.RequestType
	}
	return nil
}

func (x *KeepUserSessionRequest) GetEcho() string {
	if x != nil {
		if x, ok := x.RequestType.(*KeepUserSessionRequest_Echo); ok {
			return x.Echo
		}
	}
	return ""
}

func (x *KeepUserSessionRequest) GetUpdateTarget() *UpdateTargetRequest {
	if x != nil {
		if x, ok := x.RequestType.(*KeepUserSessionRequest_UpdateTarget); ok {
			return x.UpdateTarget
		}
	}
	return nil
}

func (x *KeepUserSessionRequest) GetDeleteTarget() *DeleteTargetRequest {
	if x != nil {
		if x, ok := x.RequestType.(*KeepUserSessionRequest_DeleteTarget); ok {
			return x.DeleteTarget
		}
	}
	return nil
}

type isKeepUserSessionRequest_RequestType interface {
	isKeepUserSessionRequest_RequestType()
}

type KeepUserSessionRequest_Echo struct {
	Echo string `protobuf:"bytes,2,opt,name=echo,proto3,oneof"`
}

type KeepUserSessionRequest_UpdateTarget struct {
	UpdateTarget *UpdateTargetRequest `protobuf:"bytes,3,opt,name=update_target,json=updateTarget,proto3,oneof"`
}

type KeepUserSessionRequest_DeleteTarget struct {
	DeleteTarget *DeleteTargetRequest `protobuf:"bytes,4,opt,name=delete_target,json=deleteTarget,proto3,oneof"`
}

func (*KeepUserSessionRequest_Echo) isKeepUserSessionRequest_RequestType() {}

func (*KeepUserSessionRequest_UpdateTarget) isKeepUserSessionRequest_RequestType() {}

func (*KeepUserSessionRequest_DeleteTarget) isKeepUserSessionRequest_RequestType() {}

type KeepUserSessionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to ResponseType:
	//
	//	*KeepUserSessionResponse_Echo
	//	*KeepUserSessionResponse_DocumentChange
	//	*KeepUserSessionResponse_TargetChange
	ResponseType  isKeepUserSessionResponse_ResponseType `protobuf_oneof:"response_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeepUserSessionResponse) Reset() {
	*x = KeepUserSessionResponse{}
	mi := &file_proto_gamesync_v1_gamesync_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeepUserSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeepUserSessionResponse) ProtoMessage() {}

func (x *KeepUserSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gamesync_v1_gamesync_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeepUserSessionResponse.ProtoReflect.Descriptor instead.
func (*KeepUserSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_gamesync_v1_gamesync_proto_rawDescGZIP(), []int{21}
}

func (x *KeepUserSessionResponse) GetResponseType() isKeepUserSessionResponse_ResponseType {
	if x != nil {
		return x.ResponseType
	}
	return nil
}

func (x *KeepUserSessionResponse) GetEcho() string {
	if x != nil {
		if x, ok := x.ResponseType.(*KeepUserSessionResponse_Echo); ok {
			return x.Echo
		}
	}
	return ""
}

func (x *KeepUserSessionResponse) GetDocumentChange() *DocumentChange {
	if x != nil {
		if x, ok := x.ResponseType.(*KeepUserSessionResponse_DocumentChange); ok {
			return x.DocumentChange
		}
	}
	return nil
}

func (x *KeepUserSessionResponse) GetTargetChange() *TargetChange {
	if x != nil {
		if x, ok := x.ResponseType.(*KeepUserSessionResponse_TargetChange); ok {
			return x.TargetChange
		}
	}
	return nil
}

type isKeepUserSessionResponse_ResponseType interface {
	isKeepUserSessionResponse_ResponseType()
}

type KeepUserSessionResponse_Echo struct {
	Echo string `protobuf:"bytes,1,opt,name=echo,proto3,oneof"`
}

type KeepUserSessionResponse_DocumentChange struct {
	DocumentChange *DocumentChange `protobuf:"bytes,2,opt,name=document_change,json=documentChange,proto3,oneof"`
}

type KeepUserSessionResponse_TargetChange struct {
	TargetChange *TargetChange `protobuf:"bytes,3,opt,name=target_change,json=targetChange,proto3,oneof"`
}

func (*KeepUserSessionResponse_Echo) isKeepUserSessionResponse_ResponseType() {}

func (*KeepUserSessionResponse_DocumentChange) isKeepUserSessionResponse_ResponseType() {}

func (*KeepUserSessionResponse_TargetChange) isKeepUserSessionResponse_ResponseType() {}

type UpdateTargetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        *Target                `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTargetRequest) Reset() {
	*x = UpdateTargetRequest{}
	mi := &file_proto_gamesync_v1_gamesync_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTargetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTargetRequest) ProtoMessage() {}

func (x *UpdateTargetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gamesync_v1_gamesync_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTargetRequest.ProtoReflect.Descriptor instead.
func (*UpdateTargetRequest) Descriptor() ([]byte, []int) {
	return file_proto_gamesync_v1_gamesync_proto_rawDescGZIP(), []int{22}
}

func (x *UpdateTargetRequest) GetTarget() *Target {
	if x != nil {
		return x.Target
	}
	return nil
}

type DeleteTargetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTargetRequest) Reset() {
	*x = DeleteTargetRequest{}
	mi := &file_proto_gamesync_v1_gamesync_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTargetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTargetRequest) ProtoMessage() {}

func (x *DeleteTargetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gamesync_v1_gamesync_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTargetRequest.ProtoReflect.Descriptor instead.
func (*DeleteTargetRequest) Descriptor() ([]byte, []int) {
	return file_proto_gamesync_v1_gamesync_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteTargetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateRoundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Round         *Round                 `protobuf:"bytes,1,opt,name=round,proto3" json:"round,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoundRequest) Reset() {
	*x = CreateRoundRequest{}
	mi := &file_proto_gamesync_v1_gamesync_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoundRequest) ProtoMessage() {}

func (x *CreateRoundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gamesync_v1_gamesync_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoundRequest.ProtoReflect.Descriptor instead.
func (*CreateRoundRequest) Descriptor() ([]byte, []int) {
	return file_proto_gamesync_v1_gamesync_proto_rawDescGZIP(), []int{24}
}

func (x *CreateRoundRequest) GetRound() *Round {
	if x != nil {
		return x.Round
	}
	return nil
}

var File_proto_gamesync_v1_gamesync_proto protoreflect.FileDescriptor

const file_proto_gamesync_v1_gamesync_proto_rawDesc = "" +
	"\n" +
	" proto/gamesync/v1/gamesync.proto\x12\x13nn.npln.gamesync.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a!proto/gamesync/v1/resources.proto\x1a\x17validate/validate.proto\"h\n" +
	"\x11IssueTokenRequest\x12!\n" +
	"\fuser_session\x18\x01 \x01(\tR\vuserSession\x120\n" +
	"\x14matchmaking_id_token\x18\x02 \x01(\tR\x12matchmakingIdToken\"F\n" +
	"\x12IssueTokenResponse\x120\n" +
	"\x05token\x18\x01 \x01(\v2\x1a.nn.npln.gamesync.v1.TokenR\x05token\"]\n" +
	"\x13RefreshTokenRequest\x12!\n" +
	"\fuser_session\x18\x01 \x01(\tR\vuserSession\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\"H\n" +
	"\x14RefreshTokenResponse\x120\n" +
	"\x05token\x18\x01 \x01(\v2\x1a.nn.npln.gamesync.v1.TokenR\x05token\"\x83\x01\n" +
	"\x12GetDocumentRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x127\n" +
	"\tread_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\breadMask\x12 \n" +
	"\vtransaction\x18\x03 \x01(\fR\vtransaction\"\x8f\x01\n" +
	"\x14ReadDocumentsRequest\x12\x1c\n" +
	"\tdocuments\x18\x01 \x03(\tR\tdocuments\x127\n" +
	"\tread_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\breadMask\x12 \n" +
	"\vtransaction\x18\x03 \x01(\fR\vtransaction\"\x8b\x01\n" +
	"\x15ReadDocumentsResponse\x129\n" +
	"\aresults\x18\x01 \x03(\v2\x1f.nn.npln.gamesync.v1.ReadResultR\aresults\x127\n" +
	"\tread_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\breadTime\"\xc6\x01\n" +
	"\x14ListDocumentsRequest\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\tR\x06parent\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\x127\n" +
	"\tread_mask\x18\x04 \x01(\v2\x1a.google.protobuf.FieldMaskR\breadMask\x12!\n" +
	"\fshow_missing\x18\x05 \x01(\bR\vshowMissing\"|\n" +
	"\x15ListDocumentsResponse\x12;\n" +
	"\tdocuments\x18\x01 \x03(\v2\x1d.nn.npln.gamesync.v1.DocumentR\tdocuments\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"s\n" +
	"\x19QueryCollectionIdsRequest\x12\x1a\n" +
	"\bdocument\x18\x01 \x01(\tR\bdocument\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"k\n" +
	"\x1aQueryCollectionIdsResponse\x12%\n" +
	"\x0ecollection_ids\x18\x01 \x03(\tR\rcollectionIds\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xc3\x01\n" +
	"\x15WriteDocumentsRequest\x12N\n" +
	"\x10write_operations\x18\x01 \x03(\v2#.nn.npln.gamesync.v1.WriteOperationR\x0fwriteOperations\x12Z\n" +
	"\x14deferment_operations\x18\x02 \x03(\v2'.nn.npln.gamesync.v1.DefermentOperationR\x13defermentOperations\"\x9c\x01\n" +
	"\x16WriteDocumentsResponse\x12E\n" +
	"\rwrite_results\x18\x01 \x03(\v2 .nn.npln.gamesync.v1.WriteResultR\fwriteResults\x12;\n" +
	"\vcommit_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"commitTime\"\x9b\x01\n" +
	"\x19LazyWriteDocumentsRequest\x12R\n" +
	"\x10write_operations\x18\x01 \x03(\v2'.nn.npln.gamesync.v1.LazyWriteOperationR\x0fwriteOperations\x12*\n" +
	"\x11lazy_write_config\x18\x02 \x01(\tR\x0flazyWriteConfig\"Y\n" +
	"\x1aLazyWriteDocumentsResponse\x12;\n" +
	"\vcommit_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"commitTime\"\x19\n" +
	"\x17BeginTransactionRequest\"<\n" +
	"\x18BeginTransactionResponse\x12 \n" +
	"\vtransaction\x18\x01 \x01(\fR\vtransaction\"\xe8\x01\n" +
	"\x18CommitTransactionRequest\x12N\n" +
	"\x10write_operations\x18\x01 \x03(\v2#.nn.npln.gamesync.v1.WriteOperationR\x0fwriteOperations\x12Z\n" +
	"\x14deferment_operations\x18\x02 \x03(\v2'.nn.npln.gamesync.v1.DefermentOperationR\x13defermentOperations\x12 \n" +
	"\vtransaction\x18\x03 \x01(\fR\vtransaction\"\x9f\x01\n" +
	"\x19CommitTransactionResponse\x12E\n" +
	"\rwrite_results\x18\x01 \x03(\v2 .nn.npln.gamesync.v1.WriteResultR\fwriteResults\x12;\n" +
	"\vcommit_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"commitTime\">\n" +
	"\x1aRollbackTransactionRequest\x12 \n" +
	"\vtransaction\x18\x01 \x01(\fR\vtransaction\"\xf4\x01\n" +
	"\x16KeepUserSessionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x04echo\x18\x02 \x01(\tH\x00R\x04echo\x12O\n" +
	"\rupdate_target\x18\x03 \x01(\v2(.nn.npln.gamesync.v1.UpdateTargetRequestH\x00R\fupdateTarget\x12O\n" +
	"\rdelete_target\x18\x04 \x01(\v2(.nn.npln.gamesync.v1.DeleteTargetRequestH\x00R\fdeleteTargetB\x0e\n" +
	"\frequest_type\"\xda\x01\n" +
	"\x17KeepUserSessionResponse\x12\x14\n" +
	"\x04echo\x18\x01 \x01(\tH\x00R\x04echo\x12N\n" +
	"\x0fdocument_change\x18\x02 \x01(\v2#.nn.npln.gamesync.v1.DocumentChangeH\x00R\x0edocumentChange\x12H\n" +
	"\rtarget_change\x18\x03 \x01(\v2!.nn.npln.gamesync.v1.TargetChangeH\x00R\ftargetChangeB\x0f\n" +
	"\rresponse_type\"J\n" +
	"\x13UpdateTargetRequest\x123\n" +
	"\x06target\x18\x01 \x01(\v2\x1b.nn.npln.gamesync.v1.TargetR\x06target\")\n" +
	"\x13DeleteTargetRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"F\n" +
	"\x12CreateRoundRequest\x120\n" +
	"\x05round\x18\x01 \x01(\v2\x1a.nn.npln.gamesync.v1.RoundR\x05round2\xd9\n" +
	"\n" +
	"\bGamesync\x12]\n" +
	"\n" +
	"IssueToken\x12&.nn.npln.gamesync.v1.IssueTokenRequest\x1a'.nn.npln.gamesync.v1.IssueTokenResponse\x12c\n" +
	"\fRefreshToken\x12(.nn.npln.gamesync.v1.RefreshTokenRequest\x1a).nn.npln.gamesync.v1.RefreshTokenResponse\x12U\n" +
	"\vGetDocument\x12'.nn.npln.gamesync.v1.GetDocumentRequest\x1a\x1d.nn.npln.gamesync.v1.Document\x12f\n" +
	"\rReadDocuments\x12).nn.npln.gamesync.v1.ReadDocumentsRequest\x1a*.nn.npln.gamesync.v1.ReadDocumentsResponse\x12f\n" +
	"\rListDocuments\x12).nn.npln.gamesync.v1.ListDocumentsRequest\x1a*.nn.npln.gamesync.v1.ListDocumentsResponse\x12u\n" +
	"\x12QueryCollectionIds\x12..nn.npln.gamesync.v1.QueryCollectionIdsRequest\x1a/.nn.npln.gamesync.v1.QueryCollectionIdsResponse\x12i\n" +
	"\x0eWriteDocuments\x12*.nn.npln.gamesync.v1.WriteDocumentsRequest\x1a+.nn.npln.gamesync.v1.WriteDocumentsResponse\x12u\n" +
	"\x12LazyWriteDocuments\x12..nn.npln.gamesync.v1.LazyWriteDocumentsRequest\x1a/.nn.npln.gamesync.v1.LazyWriteDocumentsResponse\x12o\n" +
	"\x10BeginTransaction\x12,.nn.npln.gamesync.v1.BeginTransactionRequest\x1a-.nn.npln.gamesync.v1.BeginTransactionResponse\x12r\n" +
	"\x11CommitTransaction\x12-.nn.npln.gamesync.v1.CommitTransactionRequest\x1a..nn.npln.gamesync.v1.CommitTransactionResponse\x12^\n" +
	"\x13RollbackTransaction\x12/.nn.npln.gamesync.v1.RollbackTransactionRequest\x1a\x16.google.protobuf.Empty\x12p\n" +
	"\x0fKeepUserSession\x12+.nn.npln.gamesync.v1.KeepUserSessionRequest\x1a,.nn.npln.gamesync.v1.KeepUserSessionResponse(\x010\x01\x12R\n" +
	"\vCreateRound\x12'.nn.npln.gamesync.v1.CreateRoundRequest\x1a\x1a.nn.npln.gamesync.v1.RoundB?Z:npln.nintendo.net/npln-practice/proto/gamesync/v1;gamesync\xf8\x01\x01b\x06proto3"

var (
	file_proto_gamesync_v1_gamesync_proto_rawDescOnce sync.Once
	file_proto_gamesync_v1_gamesync_proto_rawDescData []byte
)

func file_proto_gamesync_v1_gamesync_proto_rawDescGZIP() []byte {
	file_proto_gamesync_v1_gamesync_proto_rawDescOnce.Do(func() {
		file_proto_gamesync_v1_gamesync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gamesync_v1_gamesync_proto_rawDesc), len(file_proto_gamesync_v1_gamesync_proto_rawDesc)))
	})
	return file_proto_gamesync_v1_gamesync_proto_rawDescData
}

var file_proto_gamesync_v1_gamesync_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_proto_gamesync_v1_gamesync_proto_goTypes = []any{
	(*IssueTokenRequest)(nil),          // 0: nn.npln.gamesync.v1.IssueTokenRequest
	(*IssueTokenResponse)(nil),         // 1: nn.npln.gamesync.v1.IssueTokenResponse
	(*RefreshTokenRequest)(nil),        // 2: nn.npln.gamesync.v1.RefreshTokenRequest
	(*RefreshTokenResponse)(nil),       // 3: nn.npln.gamesync.v1.RefreshTokenResponse
	(*GetDocumentRequest)(nil),         // 4: nn.npln.gamesync.v1.GetDocumentRequest
	(*ReadDocumentsRequest)(nil),       // 5: nn.npln.gamesync.v1.ReadDocumentsRequest
	(*ReadDocumentsResponse)(nil),      // 6: nn.npln.gamesync.v1.ReadDocumentsResponse
	(*ListDocumentsRequest)(nil),       // 7: nn.npln.gamesync.v1.ListDocumentsRequest
	(*ListDocumentsResponse)(nil),      // 8: nn.npln.gamesync.v1.ListDocumentsResponse
	(*QueryCollectionIdsRequest)(nil),  // 9: nn.npln.gamesync.v1.QueryCollectionIdsRequest
	(*QueryCollectionIdsResponse)(nil), // 10: nn.npln.gamesync.v1.QueryCollectionIdsResponse
	(*WriteDocumentsRequest)(nil),      // 11: nn.npln.gamesync.v1.WriteDocumentsRequest
	(*WriteDocumentsResponse)(nil),     // 12: nn.npln.gamesync.v1.WriteDocumentsResponse
	(*LazyWriteDocumentsRequest)(nil),  // 13: nn.npln.gamesync.v1.LazyWriteDocumentsRequest
	(*LazyWriteDocumentsResponse)(nil), // 14: nn.npln.gamesync.v1.LazyWriteDocumentsResponse
	(*BeginTransactionRequest)(nil),    // 15: nn.npln.gamesync.v1.BeginTransactionRequest
	(*BeginTransactionResponse)(nil),   // 16: nn.npln.gamesync.v1.BeginTransactionResponse
	(*CommitTransactionRequest)(nil),   // 17: nn.npln.gamesync.v1.CommitTransactionRequest
	(*CommitTransactionResponse)(nil),  // 18: nn.npln.gamesync.v1.CommitTransactionResponse
	(*RollbackTransactionRequest)(nil), // 19: nn.npln.gamesync.v1.RollbackTransactionRequest
	(*KeepUserSessionRequest)(nil),     // 20: nn.npln.gamesync.v1.KeepUserSessionRequest
	(*KeepUserSessionResponse)(nil),    // 21: nn.npln.gamesync.v1.KeepUserSessionResponse
	(*UpdateTargetRequest)(nil),        // 22: nn.npln.gamesync.v1.UpdateTargetRequest
	(*DeleteTargetRequest)(nil),        // 23: nn.npln.gamesync.v1.DeleteTargetRequest
	(*CreateRoundRequest)(nil),         // 24: nn.npln.gamesync.v1.CreateRoundRequest
	(*Token)(nil),                      // 25: nn.npln.gamesync.v1.Token
	(*fieldmaskpb.FieldMask)(nil),      // 26: google.protobuf.FieldMask
	(*ReadResult)(nil),                 // 27: nn.npln.gamesync.v1.ReadResult
	(*timestamppb.Timestamp)(nil),      // 28: google.protobuf.Timestamp
	(*Document)(nil),                   // 29: nn.npln.gamesync.v1.Document
	(*WriteOperation)(nil),             // 30: nn.npln.gamesync.v1.WriteOperation
	(*DefermentOperation)(nil),         // 31: nn.npln.gamesync.v1.DefermentOperation
	(*WriteResult)(nil),                // 32: nn.npln.gamesync.v1.WriteResult
	(*LazyWriteOperation)(nil),         // 33: nn.npln.gamesync.v1.LazyWriteOperation
	(*DocumentChange)(nil),             // 34: nn.npln.gamesync.v1.DocumentChange
	(*TargetChange)(nil),               // 35: nn.npln.gamesync.v1.TargetChange
	(*Target)(nil),                     // 36: nn.npln.gamesync.v1.Target
	(*Round)(nil),                      // 37: nn.npln.gamesync.v1.Round
	(*emptypb.Empty)(nil),              // 38: google.protobuf.Empty
}
var file_proto_gamesync_v1_gamesync_proto_depIdxs = []int32{
	25, // 0: nn.npln.gamesync.v1.IssueTokenResponse.token:type_name -> nn.npln.gamesync.v1.Token
	25, // 1: nn.npln.gamesync.v1.RefreshTokenResponse.token:type_name -> nn.npln.gamesync.v1.Token
	26, // 2: nn.npln.gamesync.v1.GetDocumentRequest.read_mask:type_name -> google.protobuf.FieldMask
	26, // 3: nn.npln.gamesync.v1.ReadDocumentsRequest.read_mask:type_name -> google.protobuf.FieldMask
	27, // 4: nn.npln.gamesync.v1.ReadDocumentsResponse.results:type_name -> nn.npln.gamesync.v1.ReadResult
	28, // 5: nn.npln.gamesync.v1.ReadDocumentsResponse.read_time:type_name -> google.protobuf.Timestamp
	26, // 6: nn.npln.gamesync.v1.ListDocumentsRequest.read_mask:type_name -> google.protobuf.FieldMask
	29, // 7: nn.npln.gamesync.v1.ListDocumentsResponse.documents:type_name -> nn.npln.gamesync.v1.Document
	30, // 8: nn.npln.gamesync.v1.WriteDocumentsRequest.write_operations:type_name -> nn.npln.gamesync.v1.WriteOperation
	31, // 9: nn.npln.gamesync.v1.WriteDocumentsRequest.deferment_operations:type_name -> nn.npln.gamesync.v1.DefermentOperation
	32, // 10: nn.npln.gamesync.v1.WriteDocumentsResponse.write_results:type_name -> nn.npln.gamesync.v1.WriteResult
	28, // 11: nn.npln.gamesync.v1.WriteDocumentsResponse.commit_time:type_name -> google.protobuf.Timestamp
	33, // 12: nn.npln.gamesync.v1.LazyWriteDocumentsRequest.write_operations:type_name -> nn.npln.gamesync.v1.LazyWriteOperation
	28, // 13: nn.npln.gamesync.v1.LazyWriteDocumentsResponse.commit_time:type_name -> google.protobuf.Timestamp
	30, // 14: nn.npln.gamesync.v1.CommitTransactionRequest.write_operations:type_name -> nn.npln.gamesync.v1.WriteOperation
	31, // 15: nn.npln.gamesync.v1.CommitTransactionRequest.deferment_operations:type_name -> nn.npln.gamesync.v1.DefermentOperation
	32, // 16: nn.npln.gamesync.v1.CommitTransactionResponse.write_results:type_name -> nn.npln.gamesync.v1.WriteResult
	28, // 17: nn.npln.gamesync.v1.CommitTransactionResponse.commit_time:type_name -> google.protobuf.Timestamp
	22, // 18: nn.npln.gamesync.v1.KeepUserSessionRequest.update_target:type_name -> nn.npln.gamesync.v1.UpdateTargetRequest
	23, // 19: nn.npln.gamesync.v1.KeepUserSessionRequest.delete_target:type_name -> nn.npln.gamesync.v1.DeleteTargetRequest
	34, // 20: nn.npln.gamesync.v1.KeepUserSessionResponse.document_change:type_name -> nn.npln.gamesync.v1.DocumentChange
	35, // 21: nn.npln.gamesync.v1.KeepUserSessionResponse.target_change:type_name -> nn.npln.gamesync.v1.TargetChange
	36, // 22: nn.npln.gamesync.v1.UpdateTargetRequest.target:type_name -> nn.npln.gamesync.v1.Target
	37, // 23: nn.npln.gamesync.v1.CreateRoundRequest.round:type_name -> nn.npln.gamesync.v1.Round
	0,  // 24: nn.npln.gamesync.v1.Gamesync.IssueToken:input_type -> nn.npln.gamesync.v1.IssueTokenRequest
	2,  // 25: nn.npln.gamesync.v1.Gamesync.RefreshToken:input_type -> nn.npln.gamesync.v1.RefreshTokenRequest
	4,  // 26: nn.npln.gamesync.v1.Gamesync.GetDocument:input_type -> nn.npln.gamesync.v1.GetDocumentRequest
	5,  // 27: nn.npln.gamesync.v1.Gamesync.ReadDocuments:input_type -> nn.npln.gamesync.v1.ReadDocumentsRequest
	7,  // 28: nn.npln.gamesync.v1.Gamesync.ListDocuments:input_type -> nn.npln.gamesync.v1.ListDocumentsRequest
	9,  // 29: nn.npln.gamesync.v1.Gamesync.QueryCollectionIds:input_type -> nn.npln.gamesync.v1.QueryCollectionIdsRequest
	11, // 30: nn.npln.gamesync.v1.Gamesync.WriteDocuments:input_type -> nn.npln.gamesync.v1.WriteDocumentsRequest
	13, // 31: nn.npln.gamesync.v1.Gamesync.LazyWriteDocuments:input_type -> nn.npln.gamesync.v1.LazyWriteDocumentsRequest
	15, // 32: nn.npln.gamesync.v1.Gamesync.BeginTransaction:input_type -> nn.npln.gamesync.v1.BeginTransactionRequest
	17, // 33: nn.npln.gamesync.v1.Gamesync.CommitTransaction:input_type -> nn.npln.gamesync.v1.CommitTransactionRequest
	19, // 34: nn.npln.gamesync.v1.Gamesync.RollbackTransaction:input_type -> nn.npln.gamesync.v1.RollbackTransactionRequest
	20, // 35: nn.npln.gamesync.v1.Gamesync.KeepUserSession:input_type -> nn.npln.gamesync.v1.KeepUserSessionRequest
	24, // 36: nn.npln.gamesync.v1.Gamesync.CreateRound:input_type -> nn.npln.gamesync.v1.CreateRoundRequest
	1,  // 37: nn.npln.gamesync.v1.Gamesync.IssueToken:output_type -> nn.npln.gamesync.v1.IssueTokenResponse
	3,  // 38: nn.npln.gamesync.v1.Gamesync.RefreshToken:output_type -> nn.npln.gamesync.v1.RefreshTokenResponse
	29, // 39: nn.npln.gamesync.v1.Gamesync.GetDocument:output_type -> nn.npln.gamesync.v1.Document
	6,  // 40: nn.npln.gamesync.v1.Gamesync.ReadDocuments:output_type -> nn.npln.gamesync.v1.ReadDocumentsResponse
	8,  // 41: nn.npln.gamesync.v1.Gamesync.ListDocuments:output_type -> nn.npln.gamesync.v1.ListDocumentsResponse
	10, // 42: nn.npln.gamesync.v1.Gamesync.QueryCollectionIds:output_type -> nn.npln.gamesync.v1.QueryCollectionIdsResponse
	12, // 43: nn.npln.gamesync.v1.Gamesync.WriteDocuments:output_type -> nn.npln.gamesync.v1.WriteDocumentsResponse
	14, // 44: nn.npln.gamesync.v1.Gamesync.LazyWriteDocuments:output_type -> nn.npln.gamesync.v1.LazyWriteDocumentsResponse
	16, // 45: nn.npln.gamesync.v1.Gamesync.BeginTransaction:output_type -> nn.npln.gamesync.v1.BeginTransactionResponse
	18, // 46: nn.npln.gamesync.v1.Gamesync.CommitTransaction:output_type -> nn.npln.gamesync.v1.CommitTransactionResponse
	38, // 47: nn.npln.gamesync.v1.Gamesync.RollbackTransaction:output_type -> google.protobuf.Empty
	21, // 48: nn.npln.gamesync.v1.Gamesync.KeepUserSession:output_type -> nn.npln.gamesync.v1.KeepUserSessionResponse
	37, // 49: nn.npln.gamesync.v1.Gamesync.CreateRound:output_type -> nn.npln.gamesync.v1.Round
	37, // [37:50] is the sub-list for method output_type
	24, // [24:37] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_proto_gamesync_v1_gamesync_proto_init() }
func file_proto_gamesync_v1_gamesync_proto_init() {
	if File_proto_gamesync_v1_gamesync_proto != nil {
		return
	}
	file_proto_gamesync_v1_resources_proto_init()
	file_proto_gamesync_v1_gamesync_proto_msgTypes[20].OneofWrappers = []any{
		(*KeepUserSessionRequest_Echo)(nil),
		(*KeepUserSessionRequest_UpdateTarget)(nil),
		(*KeepUserSessionRequest_DeleteTarget)(nil),
	}
	file_proto_gamesync_v1_gamesync_proto_msgTypes[21].OneofWrappers = []any{
		(*KeepUserSessionResponse_Echo)(nil),
		(*KeepUserSessionResponse_DocumentChange)(nil),
		(*KeepUserSessionResponse_TargetChange)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gamesync_v1_gamesync_proto_rawDesc), len(file_proto_gamesync_v1_gamesync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_gamesync_v1_gamesync_proto_goTypes,
		DependencyIndexes: file_proto_gamesync_v1_gamesync_proto_depIdxs,
		MessageInfos:      file_proto_gamesync_v1_gamesync_proto_msgTypes,
	}.Build()
	File_proto_gamesync_v1_gamesync_proto = out.File
	file_proto_gamesync_v1_gamesync_proto_goTypes = nil
	file_proto_gamesync_v1_gamesync_proto_depIdxs = nil
}
