// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: proto/toyohr/v1/resources.proto

package toyohr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	common "openpak/splatoon-3/proto/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegularSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stages        []int32                `protobuf:"varint,1,rep,packed,name=stages,proto3" json:"stages,omitempty"`
	Attributes    *common.MapValue       `protobuf:"bytes,2,opt,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegularSettings) Reset() {
	*x = RegularSettings{}
	mi := &file_proto_toyohr_v1_resources_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegularSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegularSettings) ProtoMessage() {}

func (x *RegularSettings) ProtoReflect() protoreflect.Message {
	mi := &file_proto_toyohr_v1_resources_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegularSettings.ProtoReflect.Descriptor instead.
func (*RegularSettings) Descriptor() ([]byte, []int) {
	return file_proto_toyohr_v1_resources_proto_rawDescGZIP(), []int{0}
}

func (x *RegularSettings) GetStages() []int32 {
	if x != nil {
		return x.Stages
	}
	return nil
}

func (x *RegularSettings) GetAttributes() *common.MapValue {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type BankaraSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          int32                  `protobuf:"varint,1,opt,name=rule,proto3" json:"rule,omitempty"`
	Stages        []int32                `protobuf:"varint,2,rep,packed,name=stages,proto3" json:"stages,omitempty"`
	Attributes    *common.MapValue       `protobuf:"bytes,3,opt,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BankaraSettings) Reset() {
	*x = BankaraSettings{}
	mi := &file_proto_toyohr_v1_resources_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BankaraSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BankaraSettings) ProtoMessage() {}

func (x *BankaraSettings) ProtoReflect() protoreflect.Message {
	mi := &file_proto_toyohr_v1_resources_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BankaraSettings.ProtoReflect.Descriptor instead.
func (*BankaraSettings) Descriptor() ([]byte, []int) {
	return file_proto_toyohr_v1_resources_proto_rawDescGZIP(), []int{1}
}

func (x *BankaraSettings) GetRule() int32 {
	if x != nil {
		return x.Rule
	}
	return 0
}

func (x *BankaraSettings) GetStages() []int32 {
	if x != nil {
		return x.Stages
	}
	return nil
}

func (x *BankaraSettings) GetAttributes() *common.MapValue {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type XSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          int32                  `protobuf:"varint,1,opt,name=rule,proto3" json:"rule,omitempty"`
	Stages        []int32                `protobuf:"varint,2,rep,packed,name=stages,proto3" json:"stages,omitempty"`
	Attributes    *common.MapValue       `protobuf:"bytes,3,opt,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XSettings) Reset() {
	*x = XSettings{}
	mi := &file_proto_toyohr_v1_resources_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XSettings) ProtoMessage() {}

func (x *XSettings) ProtoReflect() protoreflect.Message {
	mi := &file_proto_toyohr_v1_resources_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XSettings.ProtoReflect.Descriptor instead.
func (*XSettings) Descriptor() ([]byte, []int) {
	return file_proto_toyohr_v1_resources_proto_rawDescGZIP(), []int{2}
}

func (x *XSettings) GetRule() int32 {
	if x != nil {
		return x.Rule
	}
	return 0
}

func (x *XSettings) GetStages() []int32 {
	if x != nil {
		return x.Stages
	}
	return nil
}

func (x *XSettings) GetAttributes() *common.MapValue {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type LeagueSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field_1       int32                  `protobuf:"varint,1,opt,name=field_1,json=field1,proto3" json:"field_1,omitempty"`
	Rule          int32                  `protobuf:"varint,2,opt,name=rule,proto3" json:"rule,omitempty"`
	Stages        []int32                `protobuf:"varint,3,rep,packed,name=stages,proto3" json:"stages,omitempty"`
	Field_4       *common.MapValue       `protobuf:"bytes,4,opt,name=field_4,json=field4,proto3" json:"field_4,omitempty"`
	Field_5       *common.MapValue       `protobuf:"bytes,5,opt,name=field_5,json=field5,proto3" json:"field_5,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeagueSettings) Reset() {
	*x = LeagueSettings{}
	mi := &file_proto_toyohr_v1_resources_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeagueSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeagueSettings) ProtoMessage() {}

func (x *LeagueSettings) ProtoReflect() protoreflect.Message {
	mi := &file_proto_toyohr_v1_resources_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeagueSettings.ProtoReflect.Descriptor instead.
func (*LeagueSettings) Descriptor() ([]byte, []int) {
	return file_proto_toyohr_v1_resources_proto_rawDescGZIP(), []int{3}
}

func (x *LeagueSettings) GetField_1() int32 {
	if x != nil {
		return x.Field_1
	}
	return 0
}

func (x *LeagueSettings) GetRule() int32 {
	if x != nil {
		return x.Rule
	}
	return 0
}

func (x *LeagueSettings) GetStages() []int32 {
	if x != nil {
		return x.Stages
	}
	return nil
}

func (x *LeagueSettings) GetField_4() *common.MapValue {
	if x != nil {
		return x.Field_4
	}
	return nil
}

func (x *LeagueSettings) GetField_5() *common.MapValue {
	if x != nil {
		return x.Field_5
	}
	return nil
}

type VsSchedule struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	StartTime       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	RegularSettings *RegularSettings       `protobuf:"bytes,4,opt,name=regular_settings,json=regularSettings,proto3" json:"regular_settings,omitempty"`
	BankaraSettings []*BankaraSettings     `protobuf:"bytes,5,rep,name=bankara_settings,json=bankaraSettings,proto3" json:"bankara_settings,omitempty"`
	XSettings       *XSettings             `protobuf:"bytes,6,opt,name=x_settings,json=xSettings,proto3" json:"x_settings,omitempty"`
	LeagueSettings  *LeagueSettings        `protobuf:"bytes,7,opt,name=league_settings,json=leagueSettings,proto3" json:"league_settings,omitempty"`
	ScheduleSetId   string                 `protobuf:"bytes,8,opt,name=schedule_set_id,json=scheduleSetId,proto3" json:"schedule_set_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VsSchedule) Reset() {
	*x = VsSchedule{}
	mi := &file_proto_toyohr_v1_resources_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VsSchedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VsSchedule) ProtoMessage() {}

func (x *VsSchedule) ProtoReflect() protoreflect.Message {
	mi := &file_proto_toyohr_v1_resources_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VsSchedule.ProtoReflect.Descriptor instead.
func (*VsSchedule) Descriptor() ([]byte, []int) {
	return file_proto_toyohr_v1_resources_proto_rawDescGZIP(), []int{4}
}

func (x *VsSchedule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VsSchedule) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *VsSchedule) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *VsSchedule) GetRegularSettings() *RegularSettings {
	if x != nil {
		return x.RegularSettings
	}
	return nil
}

func (x *VsSchedule) GetBankaraSettings() []*BankaraSettings {
	if x != nil {
		return x.BankaraSettings
	}
	return nil
}

func (x *VsSchedule) GetXSettings() *XSettings {
	if x != nil {
		return x.XSettings
	}
	return nil
}

func (x *VsSchedule) GetLeagueSettings() *LeagueSettings {
	if x != nil {
		return x.LeagueSettings
	}
	return nil
}

func (x *VsSchedule) GetScheduleSetId() string {
	if x != nil {
		return x.ScheduleSetId
	}
	return ""
}

type CoopSchedule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Field_2       int32                  `protobuf:"varint,2,opt,name=field_2,json=field2,proto3" json:"field_2,omitempty"`
	ScheduleSetId string                 `protobuf:"bytes,3,opt,name=schedule_set_id,json=scheduleSetId,proto3" json:"schedule_set_id,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Normal        *CoopSchedule_Normal   `protobuf:"bytes,6,opt,name=normal,proto3" json:"normal,omitempty"`
	ShiftId       string                 `protobuf:"bytes,9,opt,name=shift_id,json=shiftId,proto3" json:"shift_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoopSchedule) Reset() {
	*x = CoopSchedule{}
	mi := &file_proto_toyohr_v1_resources_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoopSchedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoopSchedule) ProtoMessage() {}

func (x *CoopSchedule) ProtoReflect() protoreflect.Message {
	mi := &file_proto_toyohr_v1_resources_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoopSchedule.ProtoReflect.Descriptor instead.
func (*CoopSchedule) Descriptor() ([]byte, []int) {
	return file_proto_toyohr_v1_resources_proto_rawDescGZIP(), []int{5}
}

func (x *CoopSchedule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CoopSchedule) GetField_2() int32 {
	if x != nil {
		return x.Field_2
	}
	return 0
}

func (x *CoopSchedule) GetScheduleSetId() string {
	if x != nil {
		return x.ScheduleSetId
	}
	return ""
}

func (x *CoopSchedule) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *CoopSchedule) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *CoopSchedule) GetNormal() *CoopSchedule_Normal {
	if x != nil {
		return x.Normal
	}
	return nil
}

func (x *CoopSchedule) GetShiftId() string {
	if x != nil {
		return x.ShiftId
	}
	return ""
}

func (x *CoopSchedule) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type SeasonSchedule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Field_2       int32                  `protobuf:"varint,2,opt,name=field_2,json=field2,proto3" json:"field_2,omitempty"`
	Field_3       int32                  `protobuf:"varint,3,opt,name=field_3,json=field3,proto3" json:"field_3,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Attributes    *common.MapValue       `protobuf:"bytes,6,opt,name=attributes,proto3" json:"attributes,omitempty"`
	ScheduleSetId string                 `protobuf:"bytes,7,opt,name=schedule_set_id,json=scheduleSetId,proto3" json:"schedule_set_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeasonSchedule) Reset() {
	*x = SeasonSchedule{}
	mi := &file_proto_toyohr_v1_resources_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeasonSchedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeasonSchedule) ProtoMessage() {}

func (x *SeasonSchedule) ProtoReflect() protoreflect.Message {
	mi := &file_proto_toyohr_v1_resources_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeasonSchedule.ProtoReflect.Descriptor instead.
func (*SeasonSchedule) Descriptor() ([]byte, []int) {
	return file_proto_toyohr_v1_resources_proto_rawDescGZIP(), []int{6}
}

func (x *SeasonSchedule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SeasonSchedule) GetField_2() int32 {
	if x != nil {
		return x.Field_2
	}
	return 0
}

func (x *SeasonSchedule) GetField_3() int32 {
	if x != nil {
		return x.Field_3
	}
	return 0
}

func (x *SeasonSchedule) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *SeasonSchedule) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *SeasonSchedule) GetAttributes() *common.MapValue {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *SeasonSchedule) GetScheduleSetId() string {
	if x != nil {
		return x.ScheduleSetId
	}
	return ""
}

type LeagueSchedule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Rule          int32                  `protobuf:"varint,2,opt,name=rule,proto3" json:"rule,omitempty"`
	Stages        []int32                `protobuf:"varint,3,rep,packed,name=stages,proto3" json:"stages,omitempty"`
	Attributes    *common.MapValue       `protobuf:"bytes,4,opt,name=attributes,proto3" json:"attributes,omitempty"`
	ScheduleSetId string                 `protobuf:"bytes,5,opt,name=schedule_set_id,json=scheduleSetId,proto3" json:"schedule_set_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Slots         []*LeagueSchedule_Slot `protobuf:"bytes,7,rep,name=slots,proto3" json:"slots,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeagueSchedule) Reset() {
	*x = LeagueSchedule{}
	mi := &file_proto_toyohr_v1_resources_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeagueSchedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeagueSchedule) ProtoMessage() {}

func (x *LeagueSchedule) ProtoReflect() protoreflect.Message {
	mi := &file_proto_toyohr_v1_resources_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeagueSchedule.ProtoReflect.Descriptor instead.
func (*LeagueSchedule) Descriptor() ([]byte, []int) {
	return file_proto_toyohr_v1_resources_proto_rawDescGZIP(), []int{7}
}

func (x *LeagueSchedule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LeagueSchedule) GetRule() int32 {
	if x != nil {
		return x.Rule
	}
	return 0
}

func (x *LeagueSchedule) GetStages() []int32 {
	if x != nil {
		return x.Stages
	}
	return nil
}

func (x *LeagueSchedule) GetAttributes() *common.MapValue {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *LeagueSchedule) GetScheduleSetId() string {
	if x != nil {
		return x.ScheduleSetId
	}
	return ""
}

func (x *LeagueSchedule) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LeagueSchedule) GetSlots() []*LeagueSchedule_Slot {
	if x != nil {
		return x.Slots
	}
	return nil
}

func (x *LeagueSchedule) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *LeagueSchedule) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type VsParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Timestamp_1   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp_1,json=timestamp1,proto3" json:"timestamp_1,omitempty"`
	Timestamp_2   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp_2,json=timestamp2,proto3" json:"timestamp_2,omitempty"`
	Attributes    *common.MapValue       `protobuf:"bytes,4,opt,name=attributes,proto3" json:"attributes,omitempty"`
	ParamsSetId   string                 `protobuf:"bytes,5,opt,name=params_set_id,json=paramsSetId,proto3" json:"params_set_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VsParams) Reset() {
	*x = VsParams{}
	mi := &file_proto_toyohr_v1_resources_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VsParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VsParams) ProtoMessage() {}

func (x *VsParams) ProtoReflect() protoreflect.Message {
	mi := &file_proto_toyohr_v1_resources_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VsParams.ProtoReflect.Descriptor instead.
func (*VsParams) Descriptor() ([]byte, []int) {
	return file_proto_toyohr_v1_resources_proto_rawDescGZIP(), []int{8}
}

func (x *VsParams) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VsParams) GetTimestamp_1() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp_1
	}
	return nil
}

func (x *VsParams) GetTimestamp_2() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp_2
	}
	return nil
}

func (x *VsParams) GetAttributes() *common.MapValue {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *VsParams) GetParamsSetId() string {
	if x != nil {
		return x.ParamsSetId
	}
	return ""
}

type CoopSchedule_Normal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stage         int32                  `protobuf:"varint,1,opt,name=stage,proto3" json:"stage,omitempty"`
	Boss          string                 `protobuf:"bytes,2,opt,name=boss,proto3" json:"boss,omitempty"`
	MainWeapons   []int64                `protobuf:"varint,3,rep,packed,name=main_weapons,json=mainWeapons,proto3" json:"main_weapons,omitempty"`
	KumaWeapon    int32                  `protobuf:"varint,4,opt,name=kuma_weapon,json=kumaWeapon,proto3" json:"kuma_weapon,omitempty"`
	RewardType    string                 `protobuf:"bytes,5,opt,name=reward_type,json=rewardType,proto3" json:"reward_type,omitempty"`
	RewardGearId  int32                  `protobuf:"varint,6,opt,name=reward_gear_id,json=rewardGearId,proto3" json:"reward_gear_id,omitempty"`
	Attributes    *common.MapValue       `protobuf:"bytes,7,opt,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoopSchedule_Normal) Reset() {
	*x = CoopSchedule_Normal{}
	mi := &file_proto_toyohr_v1_resources_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoopSchedule_Normal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoopSchedule_Normal) ProtoMessage() {}

func (x *CoopSchedule_Normal) ProtoReflect() protoreflect.Message {
	mi := &file_proto_toyohr_v1_resources_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoopSchedule_Normal.ProtoReflect.Descriptor instead.
func (*CoopSchedule_Normal) Descriptor() ([]byte, []int) {
	return file_proto_toyohr_v1_resources_proto_rawDescGZIP(), []int{5, 0}
}

func (x *CoopSchedule_Normal) GetStage() int32 {
	if x != nil {
		return x.Stage
	}
	return 0
}

func (x *CoopSchedule_Normal) GetBoss() string {
	if x != nil {
		return x.Boss
	}
	return ""
}

func (x *CoopSchedule_Normal) GetMainWeapons() []int64 {
	if x != nil {
		return x.MainWeapons
	}
	return nil
}

func (x *CoopSchedule_Normal) GetKumaWeapon() int32 {
	if x != nil {
		return x.KumaWeapon
	}
	return 0
}

func (x *CoopSchedule_Normal) GetRewardType() string {
	if x != nil {
		return x.RewardType
	}
	return ""
}

func (x *CoopSchedule_Normal) GetRewardGearId() int32 {
	if x != nil {
		return x.RewardGearId
	}
	return 0
}

func (x *CoopSchedule_Normal) GetAttributes() *common.MapValue {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type LeagueSchedule_Slot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeagueSchedule_Slot) Reset() {
	*x = LeagueSchedule_Slot{}
	mi := &file_proto_toyohr_v1_resources_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeagueSchedule_Slot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeagueSchedule_Slot) ProtoMessage() {}

func (x *LeagueSchedule_Slot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_toyohr_v1_resources_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeagueSchedule_Slot.ProtoReflect.Descriptor instead.
func (*LeagueSchedule_Slot) Descriptor() ([]byte, []int) {
	return file_proto_toyohr_v1_resources_proto_rawDescGZIP(), []int{7, 0}
}

func (x *LeagueSchedule_Slot) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LeagueSchedule_Slot) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *LeagueSchedule_Slot) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

var File_proto_toyohr_v1_resources_proto protoreflect.FileDescriptor

const file_proto_toyohr_v1_resources_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/toyohr/v1/resources.proto\x12\x11nn.npln.toyohr.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x18proto/common/value.proto\"g\n" +
	"\x0fRegularSettings\x12\x1a\n" +
	"\x06stages\x18\x01 \x03(\x05B\x02\x10\x01R\x06stages\x128\n" +
	"\n" +
	"attributes\x18\x02 \x01(\v2\x18.nn.npln.common.MapValueR\n" +
	"attributes\"{\n" +
	"\x0fBankaraSettings\x12\x12\n" +
	"\x04rule\x18\x01 \x01(\x05R\x04rule\x12\x1a\n" +
	"\x06stages\x18\x02 \x03(\x05B\x02\x10\x01R\x06stages\x128\n" +
	"\n" +
	"attributes\x18\x03 \x01(\v2\x18.nn.npln.common.MapValueR\n" +
	"attributes\"u\n" +
	"\tXSettings\x12\x12\n" +
	"\x04rule\x18\x01 \x01(\x05R\x04rule\x12\x1a\n" +
	"\x06stages\x18\x02 \x03(\x05B\x02\x10\x01R\x06stages\x128\n" +
	"\n" +
	"attributes\x18\x03 \x01(\v2\x18.nn.npln.common.MapValueR\n" +
	"attributes\"\xbf\x01\n" +
	"\x0eLeagueSettings\x12\x17\n" +
	"\afield_1\x18\x01 \x01(\x05R\x06field1\x12\x12\n" +
	"\x04rule\x18\x02 \x01(\x05R\x04rule\x12\x1a\n" +
	"\x06stages\x18\x03 \x03(\x05B\x02\x10\x01R\x06stages\x121\n" +
	"\afield_4\x18\x04 \x01(\v2\x18.nn.npln.common.MapValueR\x06field4\x121\n" +
	"\afield_5\x18\x05 \x01(\v2\x18.nn.npln.common.MapValueR\x06field5\"\xe1\x03\n" +
	"\n" +
	"VsSchedule\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x129\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12M\n" +
	"\x10regular_settings\x18\x04 \x01(\v2\".nn.npln.toyohr.v1.RegularSettingsR\x0fregularSettings\x12M\n" +
	"\x10bankara_settings\x18\x05 \x03(\v2\".nn.npln.toyohr.v1.BankaraSettingsR\x0fbankaraSettings\x12;\n" +
	"\n" +
	"x_settings\x18\x06 \x01(\v2\x1c.nn.npln.toyohr.v1.XSettingsR\txSettings\x12J\n" +
	"\x0fleague_settings\x18\a \x01(\v2!.nn.npln.toyohr.v1.LeagueSettingsR\x0eleagueSettings\x12&\n" +
	"\x0fschedule_set_id\x18\b \x01(\tR\rscheduleSetId\"\xe8\x04\n" +
	"\fCoopSchedule\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x17\n" +
	"\afield_2\x18\x02 \x01(\x05R\x06field2\x12&\n" +
	"\x0fschedule_set_id\x18\x03 \x01(\tR\rscheduleSetId\x129\n" +
	"\n" +
	"start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12>\n" +
	"\x06normal\x18\x06 \x01(\v2&.nn.npln.toyohr.v1.CoopSchedule.NormalR\x06normal\x12\x19\n" +
	"\bshift_id\x18\t \x01(\tR\ashiftId\x128\n" +
	"\ttimestamp\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x1a\xfb\x01\n" +
	"\x06Normal\x12\x14\n" +
	"\x05stage\x18\x01 \x01(\x05R\x05stage\x12\x12\n" +
	"\x04boss\x18\x02 \x01(\tR\x04boss\x12%\n" +
	"\fmain_weapons\x18\x03 \x03(\x03B\x02\x10\x01R\vmainWeapons\x12\x1f\n" +
	"\vkuma_weapon\x18\x04 \x01(\x05R\n" +
	"kumaWeapon\x12\x1f\n" +
	"\vreward_type\x18\x05 \x01(\tR\n" +
	"rewardType\x12$\n" +
	"\x0ereward_gear_id\x18\x06 \x01(\x05R\frewardGearId\x128\n" +
	"\n" +
	"attributes\x18\a \x01(\v2\x18.nn.npln.common.MapValueR\n" +
	"attributes\"\xaa\x02\n" +
	"\x0eSeasonSchedule\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x17\n" +
	"\afield_2\x18\x02 \x01(\x05R\x06field2\x12\x17\n" +
	"\afield_3\x18\x03 \x01(\x05R\x06field3\x129\n" +
	"\n" +
	"start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x128\n" +
	"\n" +
	"attributes\x18\x06 \x01(\v2\x18.nn.npln.common.MapValueR\n" +
	"attributes\x12&\n" +
	"\x0fschedule_set_id\x18\a \x01(\tR\rscheduleSetId\"\xaf\x04\n" +
	"\x0eLeagueSchedule\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04rule\x18\x02 \x01(\x05R\x04rule\x12\x1a\n" +
	"\x06stages\x18\x03 \x03(\x05B\x02\x10\x01R\x06stages\x128\n" +
	"\n" +
	"attributes\x18\x04 \x01(\v2\x18.nn.npln.common.MapValueR\n" +
	"attributes\x12&\n" +
	"\x0fschedule_set_id\x18\x05 \x01(\tR\rscheduleSetId\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12<\n" +
	"\x05slots\x18\a \x03(\v2&.nn.npln.toyohr.v1.LeagueSchedule.SlotR\x05slots\x129\n" +
	"\n" +
	"start_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x1a\x8c\x01\n" +
	"\x04Slot\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x129\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"\xf6\x01\n" +
	"\bVsParams\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12;\n" +
	"\vtimestamp_1\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"timestamp1\x12;\n" +
	"\vtimestamp_2\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"timestamp2\x128\n" +
	"\n" +
	"attributes\x18\x04 \x01(\v2\x18.nn.npln.common.MapValueR\n" +
	"attributes\x12\"\n" +
	"\rparams_set_id\x18\x05 \x01(\tR\vparamsSetIdB+Z)openpak/splatoon-3/proto/toyohr/v1;toyohrb\x06proto3"

var (
	file_proto_toyohr_v1_resources_proto_rawDescOnce sync.Once
	file_proto_toyohr_v1_resources_proto_rawDescData []byte
)

func file_proto_toyohr_v1_resources_proto_rawDescGZIP() []byte {
	file_proto_toyohr_v1_resources_proto_rawDescOnce.Do(func() {
		file_proto_toyohr_v1_resources_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_toyohr_v1_resources_proto_rawDesc), len(file_proto_toyohr_v1_resources_proto_rawDesc)))
	})
	return file_proto_toyohr_v1_resources_proto_rawDescData
}

var file_proto_toyohr_v1_resources_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_toyohr_v1_resources_proto_goTypes = []any{
	(*RegularSettings)(nil),       // 0: nn.npln.toyohr.v1.RegularSettings
	(*BankaraSettings)(nil),       // 1: nn.npln.toyohr.v1.BankaraSettings
	(*XSettings)(nil),             // 2: nn.npln.toyohr.v1.XSettings
	(*LeagueSettings)(nil),        // 3: nn.npln.toyohr.v1.LeagueSettings
	(*VsSchedule)(nil),            // 4: nn.npln.toyohr.v1.VsSchedule
	(*CoopSchedule)(nil),          // 5: nn.npln.toyohr.v1.CoopSchedule
	(*SeasonSchedule)(nil),        // 6: nn.npln.toyohr.v1.SeasonSchedule
	(*LeagueSchedule)(nil),        // 7: nn.npln.toyohr.v1.LeagueSchedule
	(*VsParams)(nil),              // 8: nn.npln.toyohr.v1.VsParams
	(*CoopSchedule_Normal)(nil),   // 9: nn.npln.toyohr.v1.CoopSchedule.Normal
	(*LeagueSchedule_Slot)(nil),   // 10: nn.npln.toyohr.v1.LeagueSchedule.Slot
	(*common.MapValue)(nil),       // 11: nn.npln.common.MapValue
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
}
var file_proto_toyohr_v1_resources_proto_depIdxs = []int32{
	11, // 0: nn.npln.toyohr.v1.RegularSettings.attributes:type_name -> nn.npln.common.MapValue
	11, // 1: nn.npln.toyohr.v1.BankaraSettings.attributes:type_name -> nn.npln.common.MapValue
	11, // 2: nn.npln.toyohr.v1.XSettings.attributes:type_name -> nn.npln.common.MapValue
	11, // 3: nn.npln.toyohr.v1.LeagueSettings.field_4:type_name -> nn.npln.common.MapValue
	11, // 4: nn.npln.toyohr.v1.LeagueSettings.field_5:type_name -> nn.npln.common.MapValue
	12, // 5: nn.npln.toyohr.v1.VsSchedule.start_time:type_name -> google.protobuf.Timestamp
	12, // 6: nn.npln.toyohr.v1.VsSchedule.end_time:type_name -> google.protobuf.Timestamp
	0,  // 7: nn.npln.toyohr.v1.VsSchedule.regular_settings:type_name -> nn.npln.toyohr.v1.RegularSettings
	1,  // 8: nn.npln.toyohr.v1.VsSchedule.bankara_settings:type_name -> nn.npln.toyohr.v1.BankaraSettings
	2,  // 9: nn.npln.toyohr.v1.VsSchedule.x_settings:type_name -> nn.npln.toyohr.v1.XSettings
	3,  // 10: nn.npln.toyohr.v1.VsSchedule.league_settings:type_name -> nn.npln.toyohr.v1.LeagueSettings
	12, // 11: nn.npln.toyohr.v1.CoopSchedule.start_time:type_name -> google.protobuf.Timestamp
	12, // 12: nn.npln.toyohr.v1.CoopSchedule.end_time:type_name -> google.protobuf.Timestamp
	9,  // 13: nn.npln.toyohr.v1.CoopSchedule.normal:type_name -> nn.npln.toyohr.v1.CoopSchedule.Normal
	12, // 14: nn.npln.toyohr.v1.CoopSchedule.timestamp:type_name -> google.protobuf.Timestamp
	12, // 15: nn.npln.toyohr.v1.SeasonSchedule.start_time:type_name -> google.protobuf.Timestamp
	12, // 16: nn.npln.toyohr.v1.SeasonSchedule.end_time:type_name -> google.protobuf.Timestamp
	11, // 17: nn.npln.toyohr.v1.SeasonSchedule.attributes:type_name -> nn.npln.common.MapValue
	11, // 18: nn.npln.toyohr.v1.LeagueSchedule.attributes:type_name -> nn.npln.common.MapValue
	12, // 19: nn.npln.toyohr.v1.LeagueSchedule.timestamp:type_name -> google.protobuf.Timestamp
	10, // 20: nn.npln.toyohr.v1.LeagueSchedule.slots:type_name -> nn.npln.toyohr.v1.LeagueSchedule.Slot
	12, // 21: nn.npln.toyohr.v1.LeagueSchedule.start_time:type_name -> google.protobuf.Timestamp
	12, // 22: nn.npln.toyohr.v1.LeagueSchedule.end_time:type_name -> google.protobuf.Timestamp
	12, // 23: nn.npln.toyohr.v1.VsParams.timestamp_1:type_name -> google.protobuf.Timestamp
	12, // 24: nn.npln.toyohr.v1.VsParams.timestamp_2:type_name -> google.protobuf.Timestamp
	11, // 25: nn.npln.toyohr.v1.VsParams.attributes:type_name -> nn.npln.common.MapValue
	11, // 26: nn.npln.toyohr.v1.CoopSchedule.Normal.attributes:type_name -> nn.npln.common.MapValue
	12, // 27: nn.npln.toyohr.v1.LeagueSchedule.Slot.start_time:type_name -> google.protobuf.Timestamp
	12, // 28: nn.npln.toyohr.v1.LeagueSchedule.Slot.end_time:type_name -> google.protobuf.Timestamp
	29, // [29:29] is the sub-list for method output_type
	29, // [29:29] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_proto_toyohr_v1_resources_proto_init() }
func file_proto_toyohr_v1_resources_proto_init() {
	if File_proto_toyohr_v1_resources_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_toyohr_v1_resources_proto_rawDesc), len(file_proto_toyohr_v1_resources_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_toyohr_v1_resources_proto_goTypes,
		DependencyIndexes: file_proto_toyohr_v1_resources_proto_depIdxs,
		MessageInfos:      file_proto_toyohr_v1_resources_proto_msgTypes,
	}.Build()
	File_proto_toyohr_v1_resources_proto = out.File
	file_proto_toyohr_v1_resources_proto_goTypes = nil
	file_proto_toyohr_v1_resources_proto_depIdxs = nil
}
