// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: proto/matchmaking/v1/game_session_service.proto

package matchmaking

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GameSessionService_CreateGameSessionCreationTicket_FullMethodName = "/nn.npln.matchmaking.v1.GameSessionService/CreateGameSessionCreationTicket"
	GameSessionService_TrackGameSessionCreationTicket_FullMethodName  = "/nn.npln.matchmaking.v1.GameSessionService/TrackGameSessionCreationTicket"
	GameSessionService_CancelGameSessionCreationTicket_FullMethodName = "/nn.npln.matchmaking.v1.GameSessionService/CancelGameSessionCreationTicket"
	GameSessionService_GetGameSession_FullMethodName                  = "/nn.npln.matchmaking.v1.GameSessionService/GetGameSession"
	GameSessionService_BatchGetGameSessions_FullMethodName            = "/nn.npln.matchmaking.v1.GameSessionService/BatchGetGameSessions"
	GameSessionService_QueryGameSessions_FullMethodName               = "/nn.npln.matchmaking.v1.GameSessionService/QueryGameSessions"
	GameSessionService_JoinGameSession_FullMethodName                 = "/nn.npln.matchmaking.v1.GameSessionService/JoinGameSession"
	GameSessionService_SyncGameSession_FullMethodName                 = "/nn.npln.matchmaking.v1.GameSessionService/SyncGameSession"
	GameSessionService_ListUserSessions_FullMethodName                = "/nn.npln.matchmaking.v1.GameSessionService/ListUserSessions"
	GameSessionService_GetUserSession_FullMethodName                  = "/nn.npln.matchmaking.v1.GameSessionService/GetUserSession"
	GameSessionService_IssueMatchmakingIdToken_FullMethodName         = "/nn.npln.matchmaking.v1.GameSessionService/IssueMatchmakingIdToken"
	GameSessionService_IssueUserDelegationToken_FullMethodName        = "/nn.npln.matchmaking.v1.GameSessionService/IssueUserDelegationToken"
	GameSessionService_IssuePublicKey_FullMethodName                  = "/nn.npln.matchmaking.v1.GameSessionService/IssuePublicKey"
	GameSessionService_CreateGameSessionShortAlias_FullMethodName     = "/nn.npln.matchmaking.v1.GameSessionService/CreateGameSessionShortAlias"
	GameSessionService_GetGameSessionShortAlias_FullMethodName        = "/nn.npln.matchmaking.v1.GameSessionService/GetGameSessionShortAlias"
	GameSessionService_AllocateIceServerSet_FullMethodName            = "/nn.npln.matchmaking.v1.GameSessionService/AllocateIceServerSet"
	GameSessionService_ListLatencyMeasurementServers_FullMethodName   = "/nn.npln.matchmaking.v1.GameSessionService/ListLatencyMeasurementServers"
)

// GameSessionServiceClient is the client API for GameSessionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameSessionServiceClient interface {
	CreateGameSessionCreationTicket(ctx context.Context, in *CreateGameSessionCreationTicketRequest, opts ...grpc.CallOption) (*GameSessionCreationTicket, error)
	TrackGameSessionCreationTicket(ctx context.Context, in *TrackGameSessionCreationTicketRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GameSessionCreationTicket], error)
	CancelGameSessionCreationTicket(ctx context.Context, in *CancelGameSessionCreationTicketRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetGameSession(ctx context.Context, in *GetGameSessionRequest, opts ...grpc.CallOption) (*GameSession, error)
	BatchGetGameSessions(ctx context.Context, in *BatchGetGameSessionsRequest, opts ...grpc.CallOption) (*BatchGetGameSessionsResponse, error)
	QueryGameSessions(ctx context.Context, in *QueryGameSessionsRequest, opts ...grpc.CallOption) (*QueryGameSessionsResponse, error)
	JoinGameSession(ctx context.Context, in *JoinGameSessionRequest, opts ...grpc.CallOption) (*JoinGameSessionResponse, error)
	SyncGameSession(ctx context.Context, in *SyncGameSessionRequest, opts ...grpc.CallOption) (*SyncGameSessionResponse, error)
	ListUserSessions(ctx context.Context, in *ListUserSessionsRequest, opts ...grpc.CallOption) (*ListUserSessionsResponse, error)
	GetUserSession(ctx context.Context, in *GetUserSessionRequest, opts ...grpc.CallOption) (*UserSession, error)
	IssueMatchmakingIdToken(ctx context.Context, in *IssueMatchmakingIdTokenRequest, opts ...grpc.CallOption) (*IssueMatchmakingIdTokenResponse, error)
	IssueUserDelegationToken(ctx context.Context, in *IssueUserDelegationTokenRequest, opts ...grpc.CallOption) (*IssueUserDelegationTokenResponse, error)
	IssuePublicKey(ctx context.Context, in *IssuePublicKeyRequest, opts ...grpc.CallOption) (*IssuePublicKeyResponse, error)
	CreateGameSessionShortAlias(ctx context.Context, in *CreateGameSessionShortAliasRequest, opts ...grpc.CallOption) (*GameSessionShortAlias, error)
	GetGameSessionShortAlias(ctx context.Context, in *GetGameSessionShortAliasRequest, opts ...grpc.CallOption) (*GameSessionShortAlias, error)
	AllocateIceServerSet(ctx context.Context, in *AllocateIceServerSetRequest, opts ...grpc.CallOption) (*IceServerSet, error)
	ListLatencyMeasurementServers(ctx context.Context, in *ListLatencyMeasurementServersRequest, opts ...grpc.CallOption) (*ListLatencyMeasurementServersResponse, error)
}

type gameSessionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGameSessionServiceClient(cc grpc.ClientConnInterface) GameSessionServiceClient {
	return &gameSessionServiceClient{cc}
}

func (c *gameSessionServiceClient) CreateGameSessionCreationTicket(ctx context.Context, in *CreateGameSessionCreationTicketRequest, opts ...grpc.CallOption) (*GameSessionCreationTicket, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GameSessionCreationTicket)
	err := c.cc.Invoke(ctx, GameSessionService_CreateGameSessionCreationTicket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameSessionServiceClient) TrackGameSessionCreationTicket(ctx context.Context, in *TrackGameSessionCreationTicketRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GameSessionCreationTicket], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GameSessionService_ServiceDesc.Streams[0], GameSessionService_TrackGameSessionCreationTicket_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TrackGameSessionCreationTicketRequest, GameSessionCreationTicket]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GameSessionService_TrackGameSessionCreationTicketClient = grpc.ServerStreamingClient[GameSessionCreationTicket]

func (c *gameSessionServiceClient) CancelGameSessionCreationTicket(ctx context.Context, in *CancelGameSessionCreationTicketRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, GameSessionService_CancelGameSessionCreationTicket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameSessionServiceClient) GetGameSession(ctx context.Context, in *GetGameSessionRequest, opts ...grpc.CallOption) (*GameSession, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GameSession)
	err := c.cc.Invoke(ctx, GameSessionService_GetGameSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameSessionServiceClient) BatchGetGameSessions(ctx context.Context, in *BatchGetGameSessionsRequest, opts ...grpc.CallOption) (*BatchGetGameSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchGetGameSessionsResponse)
	err := c.cc.Invoke(ctx, GameSessionService_BatchGetGameSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameSessionServiceClient) QueryGameSessions(ctx context.Context, in *QueryGameSessionsRequest, opts ...grpc.CallOption) (*QueryGameSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryGameSessionsResponse)
	err := c.cc.Invoke(ctx, GameSessionService_QueryGameSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameSessionServiceClient) JoinGameSession(ctx context.Context, in *JoinGameSessionRequest, opts ...grpc.CallOption) (*JoinGameSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinGameSessionResponse)
	err := c.cc.Invoke(ctx, GameSessionService_JoinGameSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameSessionServiceClient) SyncGameSession(ctx context.Context, in *SyncGameSessionRequest, opts ...grpc.CallOption) (*SyncGameSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncGameSessionResponse)
	err := c.cc.Invoke(ctx, GameSessionService_SyncGameSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameSessionServiceClient) ListUserSessions(ctx context.Context, in *ListUserSessionsRequest, opts ...grpc.CallOption) (*ListUserSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUserSessionsResponse)
	err := c.cc.Invoke(ctx, GameSessionService_ListUserSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameSessionServiceClient) GetUserSession(ctx context.Context, in *GetUserSessionRequest, opts ...grpc.CallOption) (*UserSession, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserSession)
	err := c.cc.Invoke(ctx, GameSessionService_GetUserSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameSessionServiceClient) IssueMatchmakingIdToken(ctx context.Context, in *IssueMatchmakingIdTokenRequest, opts ...grpc.CallOption) (*IssueMatchmakingIdTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssueMatchmakingIdTokenResponse)
	err := c.cc.Invoke(ctx, GameSessionService_IssueMatchmakingIdToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameSessionServiceClient) IssueUserDelegationToken(ctx context.Context, in *IssueUserDelegationTokenRequest, opts ...grpc.CallOption) (*IssueUserDelegationTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssueUserDelegationTokenResponse)
	err := c.cc.Invoke(ctx, GameSessionService_IssueUserDelegationToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameSessionServiceClient) IssuePublicKey(ctx context.Context, in *IssuePublicKeyRequest, opts ...grpc.CallOption) (*IssuePublicKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssuePublicKeyResponse)
	err := c.cc.Invoke(ctx, GameSessionService_IssuePublicKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameSessionServiceClient) CreateGameSessionShortAlias(ctx context.Context, in *CreateGameSessionShortAliasRequest, opts ...grpc.CallOption) (*GameSessionShortAlias, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GameSessionShortAlias)
	err := c.cc.Invoke(ctx, GameSessionService_CreateGameSessionShortAlias_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameSessionServiceClient) GetGameSessionShortAlias(ctx context.Context, in *GetGameSessionShortAliasRequest, opts ...grpc.CallOption) (*GameSessionShortAlias, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GameSessionShortAlias)
	err := c.cc.Invoke(ctx, GameSessionService_GetGameSessionShortAlias_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameSessionServiceClient) AllocateIceServerSet(ctx context.Context, in *AllocateIceServerSetRequest, opts ...grpc.CallOption) (*IceServerSet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IceServerSet)
	err := c.cc.Invoke(ctx, GameSessionService_AllocateIceServerSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameSessionServiceClient) ListLatencyMeasurementServers(ctx context.Context, in *ListLatencyMeasurementServersRequest, opts ...grpc.CallOption) (*ListLatencyMeasurementServersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLatencyMeasurementServersResponse)
	err := c.cc.Invoke(ctx, GameSessionService_ListLatencyMeasurementServers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameSessionServiceServer is the server API for GameSessionService service.
// All implementations must embed UnimplementedGameSessionServiceServer
// for forward compatibility.
type GameSessionServiceServer interface {
	CreateGameSessionCreationTicket(context.Context, *CreateGameSessionCreationTicketRequest) (*GameSessionCreationTicket, error)
	TrackGameSessionCreationTicket(*TrackGameSessionCreationTicketRequest, grpc.ServerStreamingServer[GameSessionCreationTicket]) error
	CancelGameSessionCreationTicket(context.Context, *CancelGameSessionCreationTicketRequest) (*emptypb.Empty, error)
	GetGameSession(context.Context, *GetGameSessionRequest) (*GameSession, error)
	BatchGetGameSessions(context.Context, *BatchGetGameSessionsRequest) (*BatchGetGameSessionsResponse, error)
	QueryGameSessions(context.Context, *QueryGameSessionsRequest) (*QueryGameSessionsResponse, error)
	JoinGameSession(context.Context, *JoinGameSessionRequest) (*JoinGameSessionResponse, error)
	SyncGameSession(context.Context, *SyncGameSessionRequest) (*SyncGameSessionResponse, error)
	ListUserSessions(context.Context, *ListUserSessionsRequest) (*ListUserSessionsResponse, error)
	GetUserSession(context.Context, *GetUserSessionRequest) (*UserSession, error)
	IssueMatchmakingIdToken(context.Context, *IssueMatchmakingIdTokenRequest) (*IssueMatchmakingIdTokenResponse, error)
	IssueUserDelegationToken(context.Context, *IssueUserDelegationTokenRequest) (*IssueUserDelegationTokenResponse, error)
	IssuePublicKey(context.Context, *IssuePublicKeyRequest) (*IssuePublicKeyResponse, error)
	CreateGameSessionShortAlias(context.Context, *CreateGameSessionShortAliasRequest) (*GameSessionShortAlias, error)
	GetGameSessionShortAlias(context.Context, *GetGameSessionShortAliasRequest) (*GameSessionShortAlias, error)
	AllocateIceServerSet(context.Context, *AllocateIceServerSetRequest) (*IceServerSet, error)
	ListLatencyMeasurementServers(context.Context, *ListLatencyMeasurementServersRequest) (*ListLatencyMeasurementServersResponse, error)
	mustEmbedUnimplementedGameSessionServiceServer()
}

// UnimplementedGameSessionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGameSessionServiceServer struct{}

func (UnimplementedGameSessionServiceServer) CreateGameSessionCreationTicket(context.Context, *CreateGameSessionCreationTicketRequest) (*GameSessionCreationTicket, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGameSessionCreationTicket not implemented")
}
func (UnimplementedGameSessionServiceServer) TrackGameSessionCreationTicket(*TrackGameSessionCreationTicketRequest, grpc.ServerStreamingServer[GameSessionCreationTicket]) error {
	return status.Error(codes.Unimplemented, "method TrackGameSessionCreationTicket not implemented")
}
func (UnimplementedGameSessionServiceServer) CancelGameSessionCreationTicket(context.Context, *CancelGameSessionCreationTicketRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelGameSessionCreationTicket not implemented")
}
func (UnimplementedGameSessionServiceServer) GetGameSession(context.Context, *GetGameSessionRequest) (*GameSession, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGameSession not implemented")
}
func (UnimplementedGameSessionServiceServer) BatchGetGameSessions(context.Context, *BatchGetGameSessionsRequest) (*BatchGetGameSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchGetGameSessions not implemented")
}
func (UnimplementedGameSessionServiceServer) QueryGameSessions(context.Context, *QueryGameSessionsRequest) (*QueryGameSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryGameSessions not implemented")
}
func (UnimplementedGameSessionServiceServer) JoinGameSession(context.Context, *JoinGameSessionRequest) (*JoinGameSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method JoinGameSession not implemented")
}
func (UnimplementedGameSessionServiceServer) SyncGameSession(context.Context, *SyncGameSessionRequest) (*SyncGameSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncGameSession not implemented")
}
func (UnimplementedGameSessionServiceServer) ListUserSessions(context.Context, *ListUserSessionsRequest) (*ListUserSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUserSessions not implemented")
}
func (UnimplementedGameSessionServiceServer) GetUserSession(context.Context, *GetUserSessionRequest) (*UserSession, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserSession not implemented")
}
func (UnimplementedGameSessionServiceServer) IssueMatchmakingIdToken(context.Context, *IssueMatchmakingIdTokenRequest) (*IssueMatchmakingIdTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IssueMatchmakingIdToken not implemented")
}
func (UnimplementedGameSessionServiceServer) IssueUserDelegationToken(context.Context, *IssueUserDelegationTokenRequest) (*IssueUserDelegationTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IssueUserDelegationToken not implemented")
}
func (UnimplementedGameSessionServiceServer) IssuePublicKey(context.Context, *IssuePublicKeyRequest) (*IssuePublicKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IssuePublicKey not implemented")
}
func (UnimplementedGameSessionServiceServer) CreateGameSessionShortAlias(context.Context, *CreateGameSessionShortAliasRequest) (*GameSessionShortAlias, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGameSessionShortAlias not implemented")
}
func (UnimplementedGameSessionServiceServer) GetGameSessionShortAlias(context.Context, *GetGameSessionShortAliasRequest) (*GameSessionShortAlias, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGameSessionShortAlias not implemented")
}
func (UnimplementedGameSessionServiceServer) AllocateIceServerSet(context.Context, *AllocateIceServerSetRequest) (*IceServerSet, error) {
	return nil, status.Error(codes.Unimplemented, "method AllocateIceServerSet not implemented")
}
func (UnimplementedGameSessionServiceServer) ListLatencyMeasurementServers(context.Context, *ListLatencyMeasurementServersRequest) (*ListLatencyMeasurementServersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLatencyMeasurementServers not implemented")
}
func (UnimplementedGameSessionServiceServer) mustEmbedUnimplementedGameSessionServiceServer() {}
func (UnimplementedGameSessionServiceServer) testEmbeddedByValue()                            {}

// UnsafeGameSessionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameSessionServiceServer will
// result in compilation errors.
type UnsafeGameSessionServiceServer interface {
	mustEmbedUnimplementedGameSessionServiceServer()
}

func RegisterGameSessionServiceServer(s grpc.ServiceRegistrar, srv GameSessionServiceServer) {
	// If the following call panics, it indicates UnimplementedGameSessionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GameSessionService_ServiceDesc, srv)
}

func _GameSessionService_CreateGameSessionCreationTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGameSessionCreationTicketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameSessionServiceServer).CreateGameSessionCreationTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameSessionService_CreateGameSessionCreationTicket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameSessionServiceServer).CreateGameSessionCreationTicket(ctx, req.(*CreateGameSessionCreationTicketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameSessionService_TrackGameSessionCreationTicket_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TrackGameSessionCreationTicketRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GameSessionServiceServer).TrackGameSessionCreationTicket(m, &grpc.GenericServerStream[TrackGameSessionCreationTicketRequest, GameSessionCreationTicket]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GameSessionService_TrackGameSessionCreationTicketServer = grpc.ServerStreamingServer[GameSessionCreationTicket]

func _GameSessionService_CancelGameSessionCreationTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelGameSessionCreationTicketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameSessionServiceServer).CancelGameSessionCreationTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameSessionService_CancelGameSessionCreationTicket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameSessionServiceServer).CancelGameSessionCreationTicket(ctx, req.(*CancelGameSessionCreationTicketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameSessionService_GetGameSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGameSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameSessionServiceServer).GetGameSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameSessionService_GetGameSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameSessionServiceServer).GetGameSession(ctx, req.(*GetGameSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameSessionService_BatchGetGameSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetGameSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameSessionServiceServer).BatchGetGameSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameSessionService_BatchGetGameSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameSessionServiceServer).BatchGetGameSessions(ctx, req.(*BatchGetGameSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameSessionService_QueryGameSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGameSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameSessionServiceServer).QueryGameSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameSessionService_QueryGameSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameSessionServiceServer).QueryGameSessions(ctx, req.(*QueryGameSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameSessionService_JoinGameSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinGameSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameSessionServiceServer).JoinGameSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameSessionService_JoinGameSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameSessionServiceServer).JoinGameSession(ctx, req.(*JoinGameSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameSessionService_SyncGameSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncGameSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameSessionServiceServer).SyncGameSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameSessionService_SyncGameSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameSessionServiceServer).SyncGameSession(ctx, req.(*SyncGameSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameSessionService_ListUserSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameSessionServiceServer).ListUserSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameSessionService_ListUserSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameSessionServiceServer).ListUserSessions(ctx, req.(*ListUserSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameSessionService_GetUserSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameSessionServiceServer).GetUserSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameSessionService_GetUserSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameSessionServiceServer).GetUserSession(ctx, req.(*GetUserSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameSessionService_IssueMatchmakingIdToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueMatchmakingIdTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameSessionServiceServer).IssueMatchmakingIdToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameSessionService_IssueMatchmakingIdToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameSessionServiceServer).IssueMatchmakingIdToken(ctx, req.(*IssueMatchmakingIdTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameSessionService_IssueUserDelegationToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueUserDelegationTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameSessionServiceServer).IssueUserDelegationToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameSessionService_IssueUserDelegationToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameSessionServiceServer).IssueUserDelegationToken(ctx, req.(*IssueUserDelegationTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameSessionService_IssuePublicKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssuePublicKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameSessionServiceServer).IssuePublicKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameSessionService_IssuePublicKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameSessionServiceServer).IssuePublicKey(ctx, req.(*IssuePublicKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameSessionService_CreateGameSessionShortAlias_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGameSessionShortAliasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameSessionServiceServer).CreateGameSessionShortAlias(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameSessionService_CreateGameSessionShortAlias_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameSessionServiceServer).CreateGameSessionShortAlias(ctx, req.(*CreateGameSessionShortAliasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameSessionService_GetGameSessionShortAlias_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGameSessionShortAliasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameSessionServiceServer).GetGameSessionShortAlias(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameSessionService_GetGameSessionShortAlias_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameSessionServiceServer).GetGameSessionShortAlias(ctx, req.(*GetGameSessionShortAliasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameSessionService_AllocateIceServerSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllocateIceServerSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameSessionServiceServer).AllocateIceServerSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameSessionService_AllocateIceServerSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameSessionServiceServer).AllocateIceServerSet(ctx, req.(*AllocateIceServerSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameSessionService_ListLatencyMeasurementServers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLatencyMeasurementServersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameSessionServiceServer).ListLatencyMeasurementServers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameSessionService_ListLatencyMeasurementServers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameSessionServiceServer).ListLatencyMeasurementServers(ctx, req.(*ListLatencyMeasurementServersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GameSessionService_ServiceDesc is the grpc.ServiceDesc for GameSessionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameSessionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nn.npln.matchmaking.v1.GameSessionService",
	HandlerType: (*GameSessionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateGameSessionCreationTicket",
			Handler:    _GameSessionService_CreateGameSessionCreationTicket_Handler,
		},
		{
			MethodName: "CancelGameSessionCreationTicket",
			Handler:    _GameSessionService_CancelGameSessionCreationTicket_Handler,
		},
		{
			MethodName: "GetGameSession",
			Handler:    _GameSessionService_GetGameSession_Handler,
		},
		{
			MethodName: "BatchGetGameSessions",
			Handler:    _GameSessionService_BatchGetGameSessions_Handler,
		},
		{
			MethodName: "QueryGameSessions",
			Handler:    _GameSessionService_QueryGameSessions_Handler,
		},
		{
			MethodName: "JoinGameSession",
			Handler:    _GameSessionService_JoinGameSession_Handler,
		},
		{
			MethodName: "SyncGameSession",
			Handler:    _GameSessionService_SyncGameSession_Handler,
		},
		{
			MethodName: "ListUserSessions",
			Handler:    _GameSessionService_ListUserSessions_Handler,
		},
		{
			MethodName: "GetUserSession",
			Handler:    _GameSessionService_GetUserSession_Handler,
		},
		{
			MethodName: "IssueMatchmakingIdToken",
			Handler:    _GameSessionService_IssueMatchmakingIdToken_Handler,
		},
		{
			MethodName: "IssueUserDelegationToken",
			Handler:    _GameSessionService_IssueUserDelegationToken_Handler,
		},
		{
			MethodName: "IssuePublicKey",
			Handler:    _GameSessionService_IssuePublicKey_Handler,
		},
		{
			MethodName: "CreateGameSessionShortAlias",
			Handler:    _GameSessionService_CreateGameSessionShortAlias_Handler,
		},
		{
			MethodName: "GetGameSessionShortAlias",
			Handler:    _GameSessionService_GetGameSessionShortAlias_Handler,
		},
		{
			MethodName: "AllocateIceServerSet",
			Handler:    _GameSessionService_AllocateIceServerSet_Handler,
		},
		{
			MethodName: "ListLatencyMeasurementServers",
			Handler:    _GameSessionService_ListLatencyMeasurementServers_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TrackGameSessionCreationTicket",
			Handler:       _GameSessionService_TrackGameSessionCreationTicket_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/matchmaking/v1/game_session_service.proto",
}
