// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: proto/matchmaking/v1/game_session_service.proto

package matchmaking

import (
	common "github.com/openpak/npln/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GameSessionView int32

const (
	GameSessionView_GAME_SESSION_VIEW_UNSPECIFIED GameSessionView = 0
	GameSessionView_BASIC                         GameSessionView = 1
	GameSessionView_FULL                          GameSessionView = 2
	GameSessionView_USER_SESSION_BASIC            GameSessionView = 3
)

// Enum value maps for GameSessionView.
var (
	GameSessionView_name = map[int32]string{
		0: "GAME_SESSION_VIEW_UNSPECIFIED",
		1: "BASIC",
		2: "FULL",
		3: "USER_SESSION_BASIC",
	}
	GameSessionView_value = map[string]int32{
		"GAME_SESSION_VIEW_UNSPECIFIED": 0,
		"BASIC":                         1,
		"FULL":                          2,
		"USER_SESSION_BASIC":            3,
	}
)

func (x GameSessionView) Enum() *GameSessionView {
	p := new(GameSessionView)
	*p = x
	return p
}

func (x GameSessionView) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameSessionView) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_matchmaking_v1_game_session_service_proto_enumTypes[0].Descriptor()
}

func (GameSessionView) Type() protoreflect.EnumType {
	return &file_proto_matchmaking_v1_game_session_service_proto_enumTypes[0]
}

func (x GameSessionView) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameSessionView.Descriptor instead.
func (GameSessionView) EnumDescriptor() ([]byte, []int) {
	return file_proto_matchmaking_v1_game_session_service_proto_rawDescGZIP(), []int{0}
}

type CreateGameSessionCreationTicketRequest struct {
	state                     protoimpl.MessageState     `protogen:"open.v1"`
	Parent                    string                     `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	GameSessionCreationTicket *GameSessionCreationTicket `protobuf:"bytes,2,opt,name=game_session_creation_ticket,json=gameSessionCreationTicket,proto3" json:"game_session_creation_ticket,omitempty"`
	UserDelegationTokens      []string                   `protobuf:"bytes,3,rep,name=user_delegation_tokens,json=userDelegationTokens,proto3" json:"user_delegation_tokens,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *CreateGameSessionCreationTicketRequest) Reset() {
	*x = CreateGameSessionCreationTicketRequest{}
	mi := &file_proto_matchmaking_v1_game_session_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGameSessionCreationTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameSessionCreationTicketRequest) ProtoMessage() {}

func (x *CreateGameSessionCreationTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matchmaking_v1_game_session_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameSessionCreationTicketRequest.ProtoReflect.Descriptor instead.
func (*CreateGameSessionCreationTicketRequest) Descriptor() ([]byte, []int) {
	return file_proto_matchmaking_v1_game_session_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateGameSessionCreationTicketRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *CreateGameSessionCreationTicketRequest) GetGameSessionCreationTicket() *GameSessionCreationTicket {
	if x != nil {
		return x.GameSessionCreationTicket
	}
	return nil
}

func (x *CreateGameSessionCreationTicketRequest) GetUserDelegationTokens() []string {
	if x != nil {
		return x.UserDelegationTokens
	}
	return nil
}

type TrackGameSessionCreationTicketRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Name                 string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	UserDelegationTokens []string               `protobuf:"bytes,2,rep,name=user_delegation_tokens,json=userDelegationTokens,proto3" json:"user_delegation_tokens,omitempty"`
	IncludeIdTokenUsers  []string               `protobuf:"bytes,3,rep,name=include_id_token_users,json=includeIdTokenUsers,proto3" json:"include_id_token_users,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TrackGameSessionCreationTicketRequest) Reset() {
	*x = TrackGameSessionCreationTicketRequest{}
	mi := &file_proto_matchmaking_v1_game_session_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackGameSessionCreationTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackGameSessionCreationTicketRequest) ProtoMessage() {}

func (x *TrackGameSessionCreationTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matchmaking_v1_game_session_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackGameSessionCreationTicketRequest.ProtoReflect.Descriptor instead.
func (*TrackGameSessionCreationTicketRequest) Descriptor() ([]byte, []int) {
	return file_proto_matchmaking_v1_game_session_service_proto_rawDescGZIP(), []int{1}
}

func (x *TrackGameSessionCreationTicketRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TrackGameSessionCreationTicketRequest) GetUserDelegationTokens() []string {
	if x != nil {
		return x.UserDelegationTokens
	}
	return nil
}

func (x *TrackGameSessionCreationTicketRequest) GetIncludeIdTokenUsers() []string {
	if x != nil {
		return x.IncludeIdTokenUsers
	}
	return nil
}

type CancelGameSessionCreationTicketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelGameSessionCreationTicketRequest) Reset() {
	*x = CancelGameSessionCreationTicketRequest{}
	mi := &file_proto_matchmaking_v1_game_session_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelGameSessionCreationTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelGameSessionCreationTicketRequest) ProtoMessage() {}

func (x *CancelGameSessionCreationTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matchmaking_v1_game_session_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelGameSessionCreationTicketRequest.ProtoReflect.Descriptor instead.
func (*CancelGameSessionCreationTicketRequest) Descriptor() ([]byte, []int) {
	return file_proto_matchmaking_v1_game_session_service_proto_rawDescGZIP(), []int{2}
}

func (x *CancelGameSessionCreationTicketRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetGameSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	View          GameSessionView        `protobuf:"varint,2,opt,name=view,proto3,enum=nn.npln.matchmaking.v1.GameSessionView" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameSessionRequest) Reset() {
	*x = GetGameSessionRequest{}
	mi := &file_proto_matchmaking_v1_game_session_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameSessionRequest) ProtoMessage() {}

func (x *GetGameSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matchmaking_v1_game_session_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameSessionRequest.ProtoReflect.Descriptor instead.
func (*GetGameSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_matchmaking_v1_game_session_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetGameSessionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetGameSessionRequest) GetView() GameSessionView {
	if x != nil {
		return x.View
	}
	return GameSessionView_GAME_SESSION_VIEW_UNSPECIFIED
}

type BatchGetGameSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parent        string                 `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	Names         []string               `protobuf:"bytes,2,rep,name=names,proto3" json:"names,omitempty"`
	View          GameSessionView        `protobuf:"varint,3,opt,name=view,proto3,enum=nn.npln.matchmaking.v1.GameSessionView" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetGameSessionsRequest) Reset() {
	*x = BatchGetGameSessionsRequest{}
	mi := &file_proto_matchmaking_v1_game_session_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetGameSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetGameSessionsRequest) ProtoMessage() {}

func (x *BatchGetGameSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matchmaking_v1_game_session_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetGameSessionsRequest.ProtoReflect.Descriptor instead.
func (*BatchGetGameSessionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_matchmaking_v1_game_session_service_proto_rawDescGZIP(), []int{4}
}

func (x *BatchGetGameSessionsRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *BatchGetGameSessionsRequest) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

func (x *BatchGetGameSessionsRequest) GetView() GameSessionView {
	if x != nil {
		return x.View
	}
	return GameSessionView_GAME_SESSION_VIEW_UNSPECIFIED
}

type BatchGetGameSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameSessions  []*GameSession         `protobuf:"bytes,1,rep,name=game_sessions,json=gameSessions,proto3" json:"game_sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetGameSessionsResponse) Reset() {
	*x = BatchGetGameSessionsResponse{}
	mi := &file_proto_matchmaking_v1_game_session_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetGameSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetGameSessionsResponse) ProtoMessage() {}

func (x *BatchGetGameSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matchmaking_v1_game_session_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetGameSessionsResponse.ProtoReflect.Descriptor instead.
func (*BatchGetGameSessionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_matchmaking_v1_game_session_service_proto_rawDescGZIP(), []int{5}
}

func (x *BatchGetGameSessionsResponse) GetGameSessions() []*GameSession {
	if x != nil {
		return x.GameSessions
	}
	return nil
}

type QueryGameSessionsRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Tenant                  string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	View                    GameSessionView        `protobuf:"varint,2,opt,name=view,proto3,enum=nn.npln.matchmaking.v1.GameSessionView" json:"view,omitempty"`
	GameSessionSearchConfig string                 `protobuf:"bytes,3,opt,name=game_session_search_config,json=gameSessionSearchConfig,proto3" json:"game_session_search_config,omitempty"`
	MinVacancyCount         int32                  `protobuf:"varint,4,opt,name=min_vacancy_count,json=minVacancyCount,proto3" json:"min_vacancy_count,omitempty"`
	// Deprecated: Marked as deprecated in proto/matchmaking/v1/game_session_service.proto.
	MinParticipantCount int32            `protobuf:"varint,5,opt,name=min_participant_count,json=minParticipantCount,proto3" json:"min_participant_count,omitempty"`
	Properties          *common.MapValue `protobuf:"bytes,6,opt,name=properties,proto3" json:"properties,omitempty"`
	Users               []string         `protobuf:"bytes,7,rep,name=users,proto3" json:"users,omitempty"`
	PageSize            int32            `protobuf:"varint,8,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken           string           `protobuf:"bytes,9,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *QueryGameSessionsRequest) Reset() {
	*x = QueryGameSessionsRequest{}
	mi := &file_proto_matchmaking_v1_game_session_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryGameSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryGameSessionsRequest) ProtoMessage() {}

func (x *QueryGameSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matchmaking_v1_game_session_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryGameSessionsRequest.ProtoReflect.Descriptor instead.
func (*QueryGameSessionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_matchmaking_v1_game_session_service_proto_rawDescGZIP(), []int{6}
}

func (x *QueryGameSessionsRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *QueryGameSessionsRequest) GetView() GameSessionView {
	if x != nil {
		return x.View
	}
	return GameSessionView_GAME_SESSION_VIEW_UNSPECIFIED
}

func (x *QueryGameSessionsRequest) GetGameSessionSearchConfig() string {
	if x != nil {
		return x.GameSessionSearchConfig
	}
	return ""
}

func (x *QueryGameSessionsRequest) GetMinVacancyCount() int32 {
	if x != nil {
		return x.MinVacancyCount
	}
	return 0
}

// Deprecated: Marked as deprecated in proto/matchmaking/v1/game_session_service.proto.
func (x *QueryGameSessionsRequest) GetMinParticipantCount() int32 {
	if x != nil {
		return x.MinParticipantCount
	}
	return 0
}

func (x *QueryGameSessionsRequest) GetProperties() *common.MapValue {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *QueryGameSessionsRequest) GetUsers() []string {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *QueryGameSessionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *QueryGameSessionsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type QueryGameSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameSessions  []*GameSession         `protobuf:"bytes,1,rep,name=game_sessions,json=gameSessions,proto3" json:"game_sessions,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryGameSessionsResponse) Reset() {
	*x = QueryGameSessionsResponse{}
	mi := &file_proto_matchmaking_v1_game_session_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryGameSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryGameSessionsResponse) ProtoMessage() {}

func (x *QueryGameSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matchmaking_v1_game_session_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryGameSessionsResponse.ProtoReflect.Descriptor instead.
func (*QueryGameSessionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_matchmaking_v1_game_session_service_proto_rawDescGZIP(), []int{7}
}

func (x *QueryGameSessionsResponse) GetGameSessions() []*GameSession {
	if x != nil {
		return x.GameSessions
	}
	return nil
}

func (x *QueryGameSessionsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type JoinGameSessionRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Name                 string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Password             string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	UserDefinitions      []*UserDefinition      `protobuf:"bytes,3,rep,name=user_definitions,json=userDefinitions,proto3" json:"user_definitions,omitempty"`
	UserDelegationTokens []string               `protobuf:"bytes,4,rep,name=user_delegation_tokens,json=userDelegationTokens,proto3" json:"user_delegation_tokens,omitempty"`
	IncludeIdTokenUsers  []string               `protobuf:"bytes,5,rep,name=include_id_token_users,json=includeIdTokenUsers,proto3" json:"include_id_token_users,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *JoinGameSessionRequest) Reset() {
	*x = JoinGameSessionRequest{}
	mi := &file_proto_matchmaking_v1_game_session_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinGameSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGameSessionRequest) ProtoMessage() {}

func (x *JoinGameSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matchmaking_v1_game_session_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGameSessionRequest.ProtoReflect.Descriptor instead.
func (*JoinGameSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_matchmaking_v1_game_session_service_proto_rawDescGZIP(), []int{8}
}

func (x *JoinGameSessionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *JoinGameSessionRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *JoinGameSessionRequest) GetUserDefinitions() []*UserDefinition {
	if x != nil {
		return x.UserDefinitions
	}
	return nil
}

func (x *JoinGameSessionRequest) GetUserDelegationTokens() []string {
	if x != nil {
		return x.UserDelegationTokens
	}
	return nil
}

func (x *JoinGameSessionRequest) GetIncludeIdTokenUsers() []string {
	if x != nil {
		return x.IncludeIdTokenUsers
	}
	return nil
}

type JoinGameSessionResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	MatchedUserSessions []*MatchedUserSession  `protobuf:"bytes,1,rep,name=matched_user_sessions,json=matchedUserSessions,proto3" json:"matched_user_sessions,omitempty"`
	GameSession         *GameSession           `protobuf:"bytes,2,opt,name=game_session,json=gameSession,proto3" json:"game_session,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *JoinGameSessionResponse) Reset() {
	*x = JoinGameSessionResponse{}
	mi := &file_proto_matchmaking_v1_game_session_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinGameSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGameSessionResponse) ProtoMessage() {}

func (x *JoinGameSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matchmaking_v1_game_session_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGameSessionResponse.ProtoReflect.Descriptor instead.
func (*JoinGameSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_matchmaking_v1_game_session_service_proto_rawDescGZIP(), []int{9}
}

func (x *JoinGameSessionResponse) GetMatchedUserSessions() []*MatchedUserSession {
	if x != nil {
		return x.MatchedUserSessions
	}
	return nil
}

func (x *JoinGameSessionResponse) GetGameSession() *GameSession {
	if x != nil {
		return x.GameSession
	}
	return nil
}

type SyncGameSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameSession   *GameSession           `protobuf:"bytes,1,opt,name=game_session,json=gameSession,proto3" json:"game_session,omitempty"`
	KeepAliveOnly bool                   `protobuf:"varint,2,opt,name=keep_alive_only,json=keepAliveOnly,proto3" json:"keep_alive_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncGameSessionRequest) Reset() {
	*x = SyncGameSessionRequest{}
	mi := &file_proto_matchmaking_v1_game_session_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncGameSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncGameSessionRequest) ProtoMessage() {}

func (x *SyncGameSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matchmaking_v1_game_session_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncGameSessionRequest.ProtoReflect.Descriptor instead.
func (*SyncGameSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_matchmaking_v1_game_session_service_proto_rawDescGZIP(), []int{10}
}

func (x *SyncGameSessionRequest) GetGameSession() *GameSession {
	if x != nil {
		return x.GameSession
	}
	return nil
}

func (x *SyncGameSessionRequest) GetKeepAliveOnly() bool {
	if x != nil {
		return x.KeepAliveOnly
	}
	return false
}

type SyncGameSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserSessions  []*UserSession         `protobuf:"bytes,1,rep,name=user_sessions,json=userSessions,proto3" json:"user_sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncGameSessionResponse) Reset() {
	*x = SyncGameSessionResponse{}
	mi := &file_proto_matchmaking_v1_game_session_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncGameSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncGameSessionResponse) ProtoMessage() {}

func (x *SyncGameSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matchmaking_v1_game_session_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncGameSessionResponse.ProtoReflect.Descriptor instead.
func (*SyncGameSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_matchmaking_v1_game_session_service_proto_rawDescGZIP(), []int{11}
}

func (x *SyncGameSessionResponse) GetUserSessions() []*UserSession {
	if x != nil {
		return x.UserSessions
	}
	return nil
}

type ListUserSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parent        string                 `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserSessionsRequest) Reset() {
	*x = ListUserSessionsRequest{}
	mi := &file_proto_matchmaking_v1_game_session_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserSessionsRequest) ProtoMessage() {}

func (x *ListUserSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matchmaking_v1_game_session_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListUserSessionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_matchmaking_v1_game_session_service_proto_rawDescGZIP(), []int{12}
}

func (x *ListUserSessionsRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ListUserSessionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListUserSessionsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListUserSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserSessions  []*UserSession         `protobuf:"bytes,1,rep,name=user_sessions,json=userSessions,proto3" json:"user_sessions,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserSessionsResponse) Reset() {
	*x = ListUserSessionsResponse{}
	mi := &file_proto_matchmaking_v1_game_session_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserSessionsResponse) ProtoMessage() {}

func (x *ListUserSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matchmaking_v1_game_session_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListUserSessionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_matchmaking_v1_game_session_service_proto_rawDescGZIP(), []int{13}
}

func (x *ListUserSessionsResponse) GetUserSessions() []*UserSession {
	if x != nil {
		return x.UserSessions
	}
	return nil
}

func (x *ListUserSessionsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetUserSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserSessionRequest) Reset() {
	*x = GetUserSessionRequest{}
	mi := &file_proto_matchmaking_v1_game_session_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSessionRequest) ProtoMessage() {}

func (x *GetUserSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matchmaking_v1_game_session_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSessionRequest.ProtoReflect.Descriptor instead.
func (*GetUserSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_matchmaking_v1_game_session_service_proto_rawDescGZIP(), []int{14}
}

func (x *GetUserSessionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type IssueMatchmakingIdTokenRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	GameSession          string                 `protobuf:"bytes,1,opt,name=game_session,json=gameSession,proto3" json:"game_session,omitempty"`
	Users                []string               `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	UserDelegationTokens []string               `protobuf:"bytes,3,rep,name=user_delegation_tokens,json=userDelegationTokens,proto3" json:"user_delegation_tokens,omitempty"`
	IncludeIdTokenUsers  []string               `protobuf:"bytes,4,rep,name=include_id_token_users,json=includeIdTokenUsers,proto3" json:"include_id_token_users,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *IssueMatchmakingIdTokenRequest) Reset() {
	*x = IssueMatchmakingIdTokenRequest{}
	mi := &file_proto_matchmaking_v1_game_session_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueMatchmakingIdTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueMatchmakingIdTokenRequest) ProtoMessage() {}

func (x *IssueMatchmakingIdTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matchmaking_v1_game_session_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueMatchmakingIdTokenRequest.ProtoReflect.Descriptor instead.
func (*IssueMatchmakingIdTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_matchmaking_v1_game_session_service_proto_rawDescGZIP(), []int{15}
}

func (x *IssueMatchmakingIdTokenRequest) GetGameSession() string {
	if x != nil {
		return x.GameSession
	}
	return ""
}

func (x *IssueMatchmakingIdTokenRequest) GetUsers() []string {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *IssueMatchmakingIdTokenRequest) GetUserDelegationTokens() []string {
	if x != nil {
		return x.UserDelegationTokens
	}
	return nil
}

func (x *IssueMatchmakingIdTokenRequest) GetIncludeIdTokenUsers() []string {
	if x != nil {
		return x.IncludeIdTokenUsers
	}
	return nil
}

type IssueMatchmakingIdTokenResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	MatchedUserSessions []*MatchedUserSession  `protobuf:"bytes,1,rep,name=matched_user_sessions,json=matchedUserSessions,proto3" json:"matched_user_sessions,omitempty"`
	GameSession         *GameSession           `protobuf:"bytes,2,opt,name=game_session,json=gameSession,proto3" json:"game_session,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *IssueMatchmakingIdTokenResponse) Reset() {
	*x = IssueMatchmakingIdTokenResponse{}
	mi := &file_proto_matchmaking_v1_game_session_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueMatchmakingIdTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueMatchmakingIdTokenResponse) ProtoMessage() {}

func (x *IssueMatchmakingIdTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matchmaking_v1_game_session_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueMatchmakingIdTokenResponse.ProtoReflect.Descriptor instead.
func (*IssueMatchmakingIdTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_matchmaking_v1_game_session_service_proto_rawDescGZIP(), []int{16}
}

func (x *IssueMatchmakingIdTokenResponse) GetMatchedUserSessions() []*MatchedUserSession {
	if x != nil {
		return x.MatchedUserSessions
	}
	return nil
}

func (x *IssueMatchmakingIdTokenResponse) GetGameSession() *GameSession {
	if x != nil {
		return x.GameSession
	}
	return nil
}

type IssuePublicKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parent        string                 `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssuePublicKeyRequest) Reset() {
	*x = IssuePublicKeyRequest{}
	mi := &file_proto_matchmaking_v1_game_session_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssuePublicKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssuePublicKeyRequest) ProtoMessage() {}

func (x *IssuePublicKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matchmaking_v1_game_session_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssuePublicKeyRequest.ProtoReflect.Descriptor instead.
func (*IssuePublicKeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_matchmaking_v1_game_session_service_proto_rawDescGZIP(), []int{17}
}

func (x *IssuePublicKeyRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

type IssuePublicKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssuePublicKeyResponse) Reset() {
	*x = IssuePublicKeyResponse{}
	mi := &file_proto_matchmaking_v1_game_session_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssuePublicKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssuePublicKeyResponse) ProtoMessage() {}

func (x *IssuePublicKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matchmaking_v1_game_session_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssuePublicKeyResponse.ProtoReflect.Descriptor instead.
func (*IssuePublicKeyResponse) Descriptor() ([]byte, []int) {
	return file_proto_matchmaking_v1_game_session_service_proto_rawDescGZIP(), []int{18}
}

func (x *IssuePublicKeyResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type IssueUserDelegationTokenRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Parent            string                 `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	DelegatorUser     string                 `protobuf:"bytes,2,opt,name=delegator_user,json=delegatorUser,proto3" json:"delegator_user,omitempty"`
	MandataryUser     string                 `protobuf:"bytes,3,opt,name=mandatary_user,json=mandataryUser,proto3" json:"mandatary_user,omitempty"`
	Attributes        *common.MapValue       `protobuf:"bytes,4,opt,name=attributes,proto3" json:"attributes,omitempty"`
	DelegationActions []DelegationAction     `protobuf:"varint,5,rep,packed,name=delegation_actions,json=delegationActions,proto3,enum=nn.npln.matchmaking.v1.DelegationAction" json:"delegation_actions,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *IssueUserDelegationTokenRequest) Reset() {
	*x = IssueUserDelegationTokenRequest{}
	mi := &file_proto_matchmaking_v1_game_session_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueUserDelegationTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueUserDelegationTokenRequest) ProtoMessage() {}

func (x *IssueUserDelegationTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matchmaking_v1_game_session_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueUserDelegationTokenRequest.ProtoReflect.Descriptor instead.
func (*IssueUserDelegationTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_matchmaking_v1_game_session_service_proto_rawDescGZIP(), []int{19}
}

func (x *IssueUserDelegationTokenRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *IssueUserDelegationTokenRequest) GetDelegatorUser() string {
	if x != nil {
		return x.DelegatorUser
	}
	return ""
}

func (x *IssueUserDelegationTokenRequest) GetMandataryUser() string {
	if x != nil {
		return x.MandataryUser
	}
	return ""
}

func (x *IssueUserDelegationTokenRequest) GetAttributes() *common.MapValue {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *IssueUserDelegationTokenRequest) GetDelegationActions() []DelegationAction {
	if x != nil {
		return x.DelegationActions
	}
	return nil
}

type IssueUserDelegationTokenResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	UserDelegationDetail *UserDelegationDetail  `protobuf:"bytes,1,opt,name=user_delegation_detail,json=userDelegationDetail,proto3" json:"user_delegation_detail,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *IssueUserDelegationTokenResponse) Reset() {
	*x = IssueUserDelegationTokenResponse{}
	mi := &file_proto_matchmaking_v1_game_session_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueUserDelegationTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueUserDelegationTokenResponse) ProtoMessage() {}

func (x *IssueUserDelegationTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matchmaking_v1_game_session_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueUserDelegationTokenResponse.ProtoReflect.Descriptor instead.
func (*IssueUserDelegationTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_matchmaking_v1_game_session_service_proto_rawDescGZIP(), []int{20}
}

func (x *IssueUserDelegationTokenResponse) GetUserDelegationDetail() *UserDelegationDetail {
	if x != nil {
		return x.UserDelegationDetail
	}
	return nil
}

type CreateGameSessionShortAliasRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Parent                string                 `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	GameSessionShortAlias *GameSessionShortAlias `protobuf:"bytes,2,opt,name=game_session_short_alias,json=gameSessionShortAlias,proto3" json:"game_session_short_alias,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CreateGameSessionShortAliasRequest) Reset() {
	*x = CreateGameSessionShortAliasRequest{}
	mi := &file_proto_matchmaking_v1_game_session_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGameSessionShortAliasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameSessionShortAliasRequest) ProtoMessage() {}

func (x *CreateGameSessionShortAliasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matchmaking_v1_game_session_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameSessionShortAliasRequest.ProtoReflect.Descriptor instead.
func (*CreateGameSessionShortAliasRequest) Descriptor() ([]byte, []int) {
	return file_proto_matchmaking_v1_game_session_service_proto_rawDescGZIP(), []int{21}
}

func (x *CreateGameSessionShortAliasRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *CreateGameSessionShortAliasRequest) GetGameSessionShortAlias() *GameSessionShortAlias {
	if x != nil {
		return x.GameSessionShortAlias
	}
	return nil
}

type GetGameSessionShortAliasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameSessionShortAliasRequest) Reset() {
	*x = GetGameSessionShortAliasRequest{}
	mi := &file_proto_matchmaking_v1_game_session_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameSessionShortAliasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameSessionShortAliasRequest) ProtoMessage() {}

func (x *GetGameSessionShortAliasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matchmaking_v1_game_session_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameSessionShortAliasRequest.ProtoReflect.Descriptor instead.
func (*GetGameSessionShortAliasRequest) Descriptor() ([]byte, []int) {
	return file_proto_matchmaking_v1_game_session_service_proto_rawDescGZIP(), []int{22}
}

func (x *GetGameSessionShortAliasRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AllocateIceServerSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	User          string                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateIceServerSetRequest) Reset() {
	*x = AllocateIceServerSetRequest{}
	mi := &file_proto_matchmaking_v1_game_session_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateIceServerSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateIceServerSetRequest) ProtoMessage() {}

func (x *AllocateIceServerSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matchmaking_v1_game_session_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateIceServerSetRequest.ProtoReflect.Descriptor instead.
func (*AllocateIceServerSetRequest) Descriptor() ([]byte, []int) {
	return file_proto_matchmaking_v1_game_session_service_proto_rawDescGZIP(), []int{23}
}

func (x *AllocateIceServerSetRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *AllocateIceServerSetRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

type ListLatencyMeasurementServersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parent        string                 `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLatencyMeasurementServersRequest) Reset() {
	*x = ListLatencyMeasurementServersRequest{}
	mi := &file_proto_matchmaking_v1_game_session_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLatencyMeasurementServersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLatencyMeasurementServersRequest) ProtoMessage() {}

func (x *ListLatencyMeasurementServersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matchmaking_v1_game_session_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLatencyMeasurementServersRequest.ProtoReflect.Descriptor instead.
func (*ListLatencyMeasurementServersRequest) Descriptor() ([]byte, []int) {
	return file_proto_matchmaking_v1_game_session_service_proto_rawDescGZIP(), []int{24}
}

func (x *ListLatencyMeasurementServersRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ListLatencyMeasurementServersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListLatencyMeasurementServersRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListLatencyMeasurementServersResponse struct {
	state                     protoimpl.MessageState      `protogen:"open.v1"`
	LatencyMeasurementServers []*LatencyMeasurementServer `protobuf:"bytes,1,rep,name=latency_measurement_servers,json=latencyMeasurementServers,proto3" json:"latency_measurement_servers,omitempty"`
	NextPageToken             string                      `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ListLatencyMeasurementServersResponse) Reset() {
	*x = ListLatencyMeasurementServersResponse{}
	mi := &file_proto_matchmaking_v1_game_session_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLatencyMeasurementServersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLatencyMeasurementServersResponse) ProtoMessage() {}

func (x *ListLatencyMeasurementServersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matchmaking_v1_game_session_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLatencyMeasurementServersResponse.ProtoReflect.Descriptor instead.
func (*ListLatencyMeasurementServersResponse) Descriptor() ([]byte, []int) {
	return file_proto_matchmaking_v1_game_session_service_proto_rawDescGZIP(), []int{25}
}

func (x *ListLatencyMeasurementServersResponse) GetLatencyMeasurementServers() []*LatencyMeasurementServer {
	if x != nil {
		return x.LatencyMeasurementServers
	}
	return nil
}

func (x *ListLatencyMeasurementServersResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_proto_matchmaking_v1_game_session_service_proto protoreflect.FileDescriptor

const file_proto_matchmaking_v1_game_session_service_proto_rawDesc = "" +
	"\n" +
	"/proto/matchmaking/v1/game_session_service.proto\x12\x16nn.npln.matchmaking.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x18proto/common/value.proto\x1a$proto/matchmaking/v1/resources.proto\"\xea\x01\n" +
	"&CreateGameSessionCreationTicketRequest\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\tR\x06parent\x12r\n" +
	"\x1cgame_session_creation_ticket\x18\x02 \x01(\v21.nn.npln.matchmaking.v1.GameSessionCreationTicketR\x19gameSessionCreationTicket\x124\n" +
	"\x16user_delegation_tokens\x18\x03 \x03(\tR\x14userDelegationTokens\"\xa6\x01\n" +
	"%TrackGameSessionCreationTicketRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x124\n" +
	"\x16user_delegation_tokens\x18\x02 \x03(\tR\x14userDelegationTokens\x123\n" +
	"\x16include_id_token_users\x18\x03 \x03(\tR\x13includeIdTokenUsers\"<\n" +
	"&CancelGameSessionCreationTicketRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"h\n" +
	"\x15GetGameSessionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12;\n" +
	"\x04view\x18\x02 \x01(\x0e2'.nn.npln.matchmaking.v1.GameSessionViewR\x04view\"\x88\x01\n" +
	"\x1bBatchGetGameSessionsRequest\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\tR\x06parent\x12\x14\n" +
	"\x05names\x18\x02 \x03(\tR\x05names\x12;\n" +
	"\x04view\x18\x03 \x01(\x0e2'.nn.npln.matchmaking.v1.GameSessionViewR\x04view\"h\n" +
	"\x1cBatchGetGameSessionsResponse\x12H\n" +
	"\rgame_sessions\x18\x01 \x03(\v2#.nn.npln.matchmaking.v1.GameSessionR\fgameSessions\"\x9c\x03\n" +
	"\x18QueryGameSessionsRequest\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12;\n" +
	"\x04view\x18\x02 \x01(\x0e2'.nn.npln.matchmaking.v1.GameSessionViewR\x04view\x12;\n" +
	"\x1agame_session_search_config\x18\x03 \x01(\tR\x17gameSessionSearchConfig\x12*\n" +
	"\x11min_vacancy_count\x18\x04 \x01(\x05R\x0fminVacancyCount\x126\n" +
	"\x15min_participant_count\x18\x05 \x01(\x05B\x02\x18\x01R\x13minParticipantCount\x128\n" +
	"\n" +
	"properties\x18\x06 \x01(\v2\x18.nn.npln.common.MapValueR\n" +
	"properties\x12\x14\n" +
	"\x05users\x18\a \x03(\tR\x05users\x12\x1b\n" +
	"\tpage_size\x18\b \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\t \x01(\tR\tpageToken\"\x8d\x01\n" +
	"\x19QueryGameSessionsResponse\x12H\n" +
	"\rgame_sessions\x18\x01 \x03(\v2#.nn.npln.matchmaking.v1.GameSessionR\fgameSessions\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x86\x02\n" +
	"\x16JoinGameSessionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12Q\n" +
	"\x10user_definitions\x18\x03 \x03(\v2&.nn.npln.matchmaking.v1.UserDefinitionR\x0fuserDefinitions\x124\n" +
	"\x16user_delegation_tokens\x18\x04 \x03(\tR\x14userDelegationTokens\x123\n" +
	"\x16include_id_token_users\x18\x05 \x03(\tR\x13includeIdTokenUsers\"\xc1\x01\n" +
	"\x17JoinGameSessionResponse\x12^\n" +
	"\x15matched_user_sessions\x18\x01 \x03(\v2*.nn.npln.matchmaking.v1.MatchedUserSessionR\x13matchedUserSessions\x12F\n" +
	"\fgame_session\x18\x02 \x01(\v2#.nn.npln.matchmaking.v1.GameSessionR\vgameSession\"\x88\x01\n" +
	"\x16SyncGameSessionRequest\x12F\n" +
	"\fgame_session\x18\x01 \x01(\v2#.nn.npln.matchmaking.v1.GameSessionR\vgameSession\x12&\n" +
	"\x0fkeep_alive_only\x18\x02 \x01(\bR\rkeepAliveOnly\"c\n" +
	"\x17SyncGameSessionResponse\x12H\n" +
	"\ruser_sessions\x18\x01 \x03(\v2#.nn.npln.matchmaking.v1.UserSessionR\fuserSessions\"m\n" +
	"\x17ListUserSessionsRequest\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\tR\x06parent\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"\x8c\x01\n" +
	"\x18ListUserSessionsResponse\x12H\n" +
	"\ruser_sessions\x18\x01 \x03(\v2#.nn.npln.matchmaking.v1.UserSessionR\fuserSessions\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"+\n" +
	"\x15GetUserSessionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xc4\x01\n" +
	"\x1eIssueMatchmakingIdTokenRequest\x12!\n" +
	"\fgame_session\x18\x01 \x01(\tR\vgameSession\x12\x14\n" +
	"\x05users\x18\x02 \x03(\tR\x05users\x124\n" +
	"\x16user_delegation_tokens\x18\x03 \x03(\tR\x14userDelegationTokens\x123\n" +
	"\x16include_id_token_users\x18\x04 \x03(\tR\x13includeIdTokenUsers\"\xc9\x01\n" +
	"\x1fIssueMatchmakingIdTokenResponse\x12^\n" +
	"\x15matched_user_sessions\x18\x01 \x03(\v2*.nn.npln.matchmaking.v1.MatchedUserSessionR\x13matchedUserSessions\x12F\n" +
	"\fgame_session\x18\x02 \x01(\v2#.nn.npln.matchmaking.v1.GameSessionR\vgameSession\"/\n" +
	"\x15IssuePublicKeyRequest\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\tR\x06parent\"*\n" +
	"\x16IssuePublicKeyResponse\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"\x9a\x02\n" +
	"\x1fIssueUserDelegationTokenRequest\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\tR\x06parent\x12%\n" +
	"\x0edelegator_user\x18\x02 \x01(\tR\rdelegatorUser\x12%\n" +
	"\x0emandatary_user\x18\x03 \x01(\tR\rmandataryUser\x128\n" +
	"\n" +
	"attributes\x18\x04 \x01(\v2\x18.nn.npln.common.MapValueR\n" +
	"attributes\x12W\n" +
	"\x12delegation_actions\x18\x05 \x03(\x0e2(.nn.npln.matchmaking.v1.DelegationActionR\x11delegationActions\"\x86\x01\n" +
	" IssueUserDelegationTokenResponse\x12b\n" +
	"\x16user_delegation_detail\x18\x01 \x01(\v2,.nn.npln.matchmaking.v1.UserDelegationDetailR\x14userDelegationDetail\"\xa4\x01\n" +
	"\"CreateGameSessionShortAliasRequest\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\tR\x06parent\x12f\n" +
	"\x18game_session_short_alias\x18\x02 \x01(\v2-.nn.npln.matchmaking.v1.GameSessionShortAliasR\x15gameSessionShortAlias\"5\n" +
	"\x1fGetGameSessionShortAliasRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"I\n" +
	"\x1bAllocateIceServerSetRequest\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\"z\n" +
	"$ListLatencyMeasurementServersRequest\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\tR\x06parent\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"\xc1\x01\n" +
	"%ListLatencyMeasurementServersResponse\x12p\n" +
	"\x1blatency_measurement_servers\x18\x01 \x03(\v20.nn.npln.matchmaking.v1.LatencyMeasurementServerR\x19latencyMeasurementServers\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken*a\n" +
	"\x0fGameSessionView\x12!\n" +
	"\x1dGAME_SESSION_VIEW_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05BASIC\x10\x01\x12\b\n" +
	"\x04FULL\x10\x02\x12\x16\n" +
	"\x12USER_SESSION_BASIC\x10\x032\x96\x11\n" +
	"\x12GameSessionService\x12\x94\x01\n" +
	"\x1fCreateGameSessionCreationTicket\x12>.nn.npln.matchmaking.v1.CreateGameSessionCreationTicketRequest\x1a1.nn.npln.matchmaking.v1.GameSessionCreationTicket\x12\x94\x01\n" +
	"\x1eTrackGameSessionCreationTicket\x12=.nn.npln.matchmaking.v1.TrackGameSessionCreationTicketRequest\x1a1.nn.npln.matchmaking.v1.GameSessionCreationTicket0\x01\x12y\n" +
	"\x1fCancelGameSessionCreationTicket\x12>.nn.npln.matchmaking.v1.CancelGameSessionCreationTicketRequest\x1a\x16.google.protobuf.Empty\x12d\n" +
	"\x0eGetGameSession\x12-.nn.npln.matchmaking.v1.GetGameSessionRequest\x1a#.nn.npln.matchmaking.v1.GameSession\x12\x81\x01\n" +
	"\x14BatchGetGameSessions\x123.nn.npln.matchmaking.v1.BatchGetGameSessionsRequest\x1a4.nn.npln.matchmaking.v1.BatchGetGameSessionsResponse\x12x\n" +
	"\x11QueryGameSessions\x120.nn.npln.matchmaking.v1.QueryGameSessionsRequest\x1a1.nn.npln.matchmaking.v1.QueryGameSessionsResponse\x12r\n" +
	"\x0fJoinGameSession\x12..nn.npln.matchmaking.v1.JoinGameSessionRequest\x1a/.nn.npln.matchmaking.v1.JoinGameSessionResponse\x12r\n" +
	"\x0fSyncGameSession\x12..nn.npln.matchmaking.v1.SyncGameSessionRequest\x1a/.nn.npln.matchmaking.v1.SyncGameSessionResponse\x12u\n" +
	"\x10ListUserSessions\x12/.nn.npln.matchmaking.v1.ListUserSessionsRequest\x1a0.nn.npln.matchmaking.v1.ListUserSessionsResponse\x12d\n" +
	"\x0eGetUserSession\x12-.nn.npln.matchmaking.v1.GetUserSessionRequest\x1a#.nn.npln.matchmaking.v1.UserSession\x12\x8a\x01\n" +
	"\x17IssueMatchmakingIdToken\x126.nn.npln.matchmaking.v1.IssueMatchmakingIdTokenRequest\x1a7.nn.npln.matchmaking.v1.IssueMatchmakingIdTokenResponse\x12\x8d\x01\n" +
	"\x18IssueUserDelegationToken\x127.nn.npln.matchmaking.v1.IssueUserDelegationTokenRequest\x1a8.nn.npln.matchmaking.v1.IssueUserDelegationTokenResponse\x12o\n" +
	"\x0eIssuePublicKey\x12-.nn.npln.matchmaking.v1.IssuePublicKeyRequest\x1a..nn.npln.matchmaking.v1.IssuePublicKeyResponse\x12\x88\x01\n" +
	"\x1bCreateGameSessionShortAlias\x12:.nn.npln.matchmaking.v1.CreateGameSessionShortAliasRequest\x1a-.nn.npln.matchmaking.v1.GameSessionShortAlias\x12\x82\x01\n" +
	"\x18GetGameSessionShortAlias\x127.nn.npln.matchmaking.v1.GetGameSessionShortAliasRequest\x1a-.nn.npln.matchmaking.v1.GameSessionShortAlias\x12q\n" +
	"\x14AllocateIceServerSet\x123.nn.npln.matchmaking.v1.AllocateIceServerSetRequest\x1a$.nn.npln.matchmaking.v1.IceServerSet\x12\x9c\x01\n" +
	"\x1dListLatencyMeasurementServers\x12<.nn.npln.matchmaking.v1.ListLatencyMeasurementServersRequest\x1a=.nn.npln.matchmaking.v1.ListLatencyMeasurementServersResponseB:Z8github.com/openpak/npln/proto/matchmaking/v1;matchmakingb\x06proto3"

var (
	file_proto_matchmaking_v1_game_session_service_proto_rawDescOnce sync.Once
	file_proto_matchmaking_v1_game_session_service_proto_rawDescData []byte
)

func file_proto_matchmaking_v1_game_session_service_proto_rawDescGZIP() []byte {
	file_proto_matchmaking_v1_game_session_service_proto_rawDescOnce.Do(func() {
		file_proto_matchmaking_v1_game_session_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_matchmaking_v1_game_session_service_proto_rawDesc), len(file_proto_matchmaking_v1_game_session_service_proto_rawDesc)))
	})
	return file_proto_matchmaking_v1_game_session_service_proto_rawDescData
}

var file_proto_matchmaking_v1_game_session_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_matchmaking_v1_game_session_service_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_proto_matchmaking_v1_game_session_service_proto_goTypes = []any{
	(GameSessionView)(0),                           // 0: nn.npln.matchmaking.v1.GameSessionView
	(*CreateGameSessionCreationTicketRequest)(nil), // 1: nn.npln.matchmaking.v1.CreateGameSessionCreationTicketRequest
	(*TrackGameSessionCreationTicketRequest)(nil),  // 2: nn.npln.matchmaking.v1.TrackGameSessionCreationTicketRequest
	(*CancelGameSessionCreationTicketRequest)(nil), // 3: nn.npln.matchmaking.v1.CancelGameSessionCreationTicketRequest
	(*GetGameSessionRequest)(nil),                  // 4: nn.npln.matchmaking.v1.GetGameSessionRequest
	(*BatchGetGameSessionsRequest)(nil),            // 5: nn.npln.matchmaking.v1.BatchGetGameSessionsRequest
	(*BatchGetGameSessionsResponse)(nil),           // 6: nn.npln.matchmaking.v1.BatchGetGameSessionsResponse
	(*QueryGameSessionsRequest)(nil),               // 7: nn.npln.matchmaking.v1.QueryGameSessionsRequest
	(*QueryGameSessionsResponse)(nil),              // 8: nn.npln.matchmaking.v1.QueryGameSessionsResponse
	(*JoinGameSessionRequest)(nil),                 // 9: nn.npln.matchmaking.v1.JoinGameSessionRequest
	(*JoinGameSessionResponse)(nil),                // 10: nn.npln.matchmaking.v1.JoinGameSessionResponse
	(*SyncGameSessionRequest)(nil),                 // 11: nn.npln.matchmaking.v1.SyncGameSessionRequest
	(*SyncGameSessionResponse)(nil),                // 12: nn.npln.matchmaking.v1.SyncGameSessionResponse
	(*ListUserSessionsRequest)(nil),                // 13: nn.npln.matchmaking.v1.ListUserSessionsRequest
	(*ListUserSessionsResponse)(nil),               // 14: nn.npln.matchmaking.v1.ListUserSessionsResponse
	(*GetUserSessionRequest)(nil),                  // 15: nn.npln.matchmaking.v1.GetUserSessionRequest
	(*IssueMatchmakingIdTokenRequest)(nil),         // 16: nn.npln.matchmaking.v1.IssueMatchmakingIdTokenRequest
	(*IssueMatchmakingIdTokenResponse)(nil),        // 17: nn.npln.matchmaking.v1.IssueMatchmakingIdTokenResponse
	(*IssuePublicKeyRequest)(nil),                  // 18: nn.npln.matchmaking.v1.IssuePublicKeyRequest
	(*IssuePublicKeyResponse)(nil),                 // 19: nn.npln.matchmaking.v1.IssuePublicKeyResponse
	(*IssueUserDelegationTokenRequest)(nil),        // 20: nn.npln.matchmaking.v1.IssueUserDelegationTokenRequest
	(*IssueUserDelegationTokenResponse)(nil),       // 21: nn.npln.matchmaking.v1.IssueUserDelegationTokenResponse
	(*CreateGameSessionShortAliasRequest)(nil),     // 22: nn.npln.matchmaking.v1.CreateGameSessionShortAliasRequest
	(*GetGameSessionShortAliasRequest)(nil),        // 23: nn.npln.matchmaking.v1.GetGameSessionShortAliasRequest
	(*AllocateIceServerSetRequest)(nil),            // 24: nn.npln.matchmaking.v1.AllocateIceServerSetRequest
	(*ListLatencyMeasurementServersRequest)(nil),   // 25: nn.npln.matchmaking.v1.ListLatencyMeasurementServersRequest
	(*ListLatencyMeasurementServersResponse)(nil),  // 26: nn.npln.matchmaking.v1.ListLatencyMeasurementServersResponse
	(*GameSessionCreationTicket)(nil),              // 27: nn.npln.matchmaking.v1.GameSessionCreationTicket
	(*GameSession)(nil),                            // 28: nn.npln.matchmaking.v1.GameSession
	(*common.MapValue)(nil),                        // 29: nn.npln.common.MapValue
	(*UserDefinition)(nil),                         // 30: nn.npln.matchmaking.v1.UserDefinition
	(*MatchedUserSession)(nil),                     // 31: nn.npln.matchmaking.v1.MatchedUserSession
	(*UserSession)(nil),                            // 32: nn.npln.matchmaking.v1.UserSession
	(DelegationAction)(0),                          // 33: nn.npln.matchmaking.v1.DelegationAction
	(*UserDelegationDetail)(nil),                   // 34: nn.npln.matchmaking.v1.UserDelegationDetail
	(*GameSessionShortAlias)(nil),                  // 35: nn.npln.matchmaking.v1.GameSessionShortAlias
	(*LatencyMeasurementServer)(nil),               // 36: nn.npln.matchmaking.v1.LatencyMeasurementServer
	(*emptypb.Empty)(nil),                          // 37: google.protobuf.Empty
	(*IceServerSet)(nil),                           // 38: nn.npln.matchmaking.v1.IceServerSet
}
var file_proto_matchmaking_v1_game_session_service_proto_depIdxs = []int32{
	27, // 0: nn.npln.matchmaking.v1.CreateGameSessionCreationTicketRequest.game_session_creation_ticket:type_name -> nn.npln.matchmaking.v1.GameSessionCreationTicket
	0,  // 1: nn.npln.matchmaking.v1.GetGameSessionRequest.view:type_name -> nn.npln.matchmaking.v1.GameSessionView
	0,  // 2: nn.npln.matchmaking.v1.BatchGetGameSessionsRequest.view:type_name -> nn.npln.matchmaking.v1.GameSessionView
	28, // 3: nn.npln.matchmaking.v1.BatchGetGameSessionsResponse.game_sessions:type_name -> nn.npln.matchmaking.v1.GameSession
	0,  // 4: nn.npln.matchmaking.v1.QueryGameSessionsRequest.view:type_name -> nn.npln.matchmaking.v1.GameSessionView
	29, // 5: nn.npln.matchmaking.v1.QueryGameSessionsRequest.properties:type_name -> nn.npln.common.MapValue
	28, // 6: nn.npln.matchmaking.v1.QueryGameSessionsResponse.game_sessions:type_name -> nn.npln.matchmaking.v1.GameSession
	30, // 7: nn.npln.matchmaking.v1.JoinGameSessionRequest.user_definitions:type_name -> nn.npln.matchmaking.v1.UserDefinition
	31, // 8: nn.npln.matchmaking.v1.JoinGameSessionResponse.matched_user_sessions:type_name -> nn.npln.matchmaking.v1.MatchedUserSession
	28, // 9: nn.npln.matchmaking.v1.JoinGameSessionResponse.game_session:type_name -> nn.npln.matchmaking.v1.GameSession
	28, // 10: nn.npln.matchmaking.v1.SyncGameSessionRequest.game_session:type_name -> nn.npln.matchmaking.v1.GameSession
	32, // 11: nn.npln.matchmaking.v1.SyncGameSessionResponse.user_sessions:type_name -> nn.npln.matchmaking.v1.UserSession
	32, // 12: nn.npln.matchmaking.v1.ListUserSessionsResponse.user_sessions:type_name -> nn.npln.matchmaking.v1.UserSession
	31, // 13: nn.npln.matchmaking.v1.IssueMatchmakingIdTokenResponse.matched_user_sessions:type_name -> nn.npln.matchmaking.v1.MatchedUserSession
	28, // 14: nn.npln.matchmaking.v1.IssueMatchmakingIdTokenResponse.game_session:type_name -> nn.npln.matchmaking.v1.GameSession
	29, // 15: nn.npln.matchmaking.v1.IssueUserDelegationTokenRequest.attributes:type_name -> nn.npln.common.MapValue
	33, // 16: nn.npln.matchmaking.v1.IssueUserDelegationTokenRequest.delegation_actions:type_name -> nn.npln.matchmaking.v1.DelegationAction
	34, // 17: nn.npln.matchmaking.v1.IssueUserDelegationTokenResponse.user_delegation_detail:type_name -> nn.npln.matchmaking.v1.UserDelegationDetail
	35, // 18: nn.npln.matchmaking.v1.CreateGameSessionShortAliasRequest.game_session_short_alias:type_name -> nn.npln.matchmaking.v1.GameSessionShortAlias
	36, // 19: nn.npln.matchmaking.v1.ListLatencyMeasurementServersResponse.latency_measurement_servers:type_name -> nn.npln.matchmaking.v1.LatencyMeasurementServer
	1,  // 20: nn.npln.matchmaking.v1.GameSessionService.CreateGameSessionCreationTicket:input_type -> nn.npln.matchmaking.v1.CreateGameSessionCreationTicketRequest
	2,  // 21: nn.npln.matchmaking.v1.GameSessionService.TrackGameSessionCreationTicket:input_type -> nn.npln.matchmaking.v1.TrackGameSessionCreationTicketRequest
	3,  // 22: nn.npln.matchmaking.v1.GameSessionService.CancelGameSessionCreationTicket:input_type -> nn.npln.matchmaking.v1.CancelGameSessionCreationTicketRequest
	4,  // 23: nn.npln.matchmaking.v1.GameSessionService.GetGameSession:input_type -> nn.npln.matchmaking.v1.GetGameSessionRequest
	5,  // 24: nn.npln.matchmaking.v1.GameSessionService.BatchGetGameSessions:input_type -> nn.npln.matchmaking.v1.BatchGetGameSessionsRequest
	7,  // 25: nn.npln.matchmaking.v1.GameSessionService.QueryGameSessions:input_type -> nn.npln.matchmaking.v1.QueryGameSessionsRequest
	9,  // 26: nn.npln.matchmaking.v1.GameSessionService.JoinGameSession:input_type -> nn.npln.matchmaking.v1.JoinGameSessionRequest
	11, // 27: nn.npln.matchmaking.v1.GameSessionService.SyncGameSession:input_type -> nn.npln.matchmaking.v1.SyncGameSessionRequest
	13, // 28: nn.npln.matchmaking.v1.GameSessionService.ListUserSessions:input_type -> nn.npln.matchmaking.v1.ListUserSessionsRequest
	15, // 29: nn.npln.matchmaking.v1.GameSessionService.GetUserSession:input_type -> nn.npln.matchmaking.v1.GetUserSessionRequest
	16, // 30: nn.npln.matchmaking.v1.GameSessionService.IssueMatchmakingIdToken:input_type -> nn.npln.matchmaking.v1.IssueMatchmakingIdTokenRequest
	20, // 31: nn.npln.matchmaking.v1.GameSessionService.IssueUserDelegationToken:input_type -> nn.npln.matchmaking.v1.IssueUserDelegationTokenRequest
	18, // 32: nn.npln.matchmaking.v1.GameSessionService.IssuePublicKey:input_type -> nn.npln.matchmaking.v1.IssuePublicKeyRequest
	22, // 33: nn.npln.matchmaking.v1.GameSessionService.CreateGameSessionShortAlias:input_type -> nn.npln.matchmaking.v1.CreateGameSessionShortAliasRequest
	23, // 34: nn.npln.matchmaking.v1.GameSessionService.GetGameSessionShortAlias:input_type -> nn.npln.matchmaking.v1.GetGameSessionShortAliasRequest
	24, // 35: nn.npln.matchmaking.v1.GameSessionService.AllocateIceServerSet:input_type -> nn.npln.matchmaking.v1.AllocateIceServerSetRequest
	25, // 36: nn.npln.matchmaking.v1.GameSessionService.ListLatencyMeasurementServers:input_type -> nn.npln.matchmaking.v1.ListLatencyMeasurementServersRequest
	27, // 37: nn.npln.matchmaking.v1.GameSessionService.CreateGameSessionCreationTicket:output_type -> nn.npln.matchmaking.v1.GameSessionCreationTicket
	27, // 38: nn.npln.matchmaking.v1.GameSessionService.TrackGameSessionCreationTicket:output_type -> nn.npln.matchmaking.v1.GameSessionCreationTicket
	37, // 39: nn.npln.matchmaking.v1.GameSessionService.CancelGameSessionCreationTicket:output_type -> google.protobuf.Empty
	28, // 40: nn.npln.matchmaking.v1.GameSessionService.GetGameSession:output_type -> nn.npln.matchmaking.v1.GameSession
	6,  // 41: nn.npln.matchmaking.v1.GameSessionService.BatchGetGameSessions:output_type -> nn.npln.matchmaking.v1.BatchGetGameSessionsResponse
	8,  // 42: nn.npln.matchmaking.v1.GameSessionService.QueryGameSessions:output_type -> nn.npln.matchmaking.v1.QueryGameSessionsResponse
	10, // 43: nn.npln.matchmaking.v1.GameSessionService.JoinGameSession:output_type -> nn.npln.matchmaking.v1.JoinGameSessionResponse
	12, // 44: nn.npln.matchmaking.v1.GameSessionService.SyncGameSession:output_type -> nn.npln.matchmaking.v1.SyncGameSessionResponse
	14, // 45: nn.npln.matchmaking.v1.GameSessionService.ListUserSessions:output_type -> nn.npln.matchmaking.v1.ListUserSessionsResponse
	32, // 46: nn.npln.matchmaking.v1.GameSessionService.GetUserSession:output_type -> nn.npln.matchmaking.v1.UserSession
	17, // 47: nn.npln.matchmaking.v1.GameSessionService.IssueMatchmakingIdToken:output_type -> nn.npln.matchmaking.v1.IssueMatchmakingIdTokenResponse
	21, // 48: nn.npln.matchmaking.v1.GameSessionService.IssueUserDelegationToken:output_type -> nn.npln.matchmaking.v1.IssueUserDelegationTokenResponse
	19, // 49: nn.npln.matchmaking.v1.GameSessionService.IssuePublicKey:output_type -> nn.npln.matchmaking.v1.IssuePublicKeyResponse
	35, // 50: nn.npln.matchmaking.v1.GameSessionService.CreateGameSessionShortAlias:output_type -> nn.npln.matchmaking.v1.GameSessionShortAlias
	35, // 51: nn.npln.matchmaking.v1.GameSessionService.GetGameSessionShortAlias:output_type -> nn.npln.matchmaking.v1.GameSessionShortAlias
	38, // 52: nn.npln.matchmaking.v1.GameSessionService.AllocateIceServerSet:output_type -> nn.npln.matchmaking.v1.IceServerSet
	26, // 53: nn.npln.matchmaking.v1.GameSessionService.ListLatencyMeasurementServers:output_type -> nn.npln.matchmaking.v1.ListLatencyMeasurementServersResponse
	37, // [37:54] is the sub-list for method output_type
	20, // [20:37] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_proto_matchmaking_v1_game_session_service_proto_init() }
func file_proto_matchmaking_v1_game_session_service_proto_init() {
	if File_proto_matchmaking_v1_game_session_service_proto != nil {
		return
	}
	file_proto_matchmaking_v1_resources_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_matchmaking_v1_game_session_service_proto_rawDesc), len(file_proto_matchmaking_v1_game_session_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_matchmaking_v1_game_session_service_proto_goTypes,
		DependencyIndexes: file_proto_matchmaking_v1_game_session_service_proto_depIdxs,
		EnumInfos:         file_proto_matchmaking_v1_game_session_service_proto_enumTypes,
		MessageInfos:      file_proto_matchmaking_v1_game_session_service_proto_msgTypes,
	}.Build()
	File_proto_matchmaking_v1_game_session_service_proto = out.File
	file_proto_matchmaking_v1_game_session_service_proto_goTypes = nil
	file_proto_matchmaking_v1_game_session_service_proto_depIdxs = nil
}
