// genrotation writes a rotation file for the server to serve.
//
//	go run ./cmd/genrotation -o rotation.json
//
// The rotation is generated, not recorded: nothing captured from the real service is in this
// repository or in what this writes. It is anchored to real time — the window containing "now"
// is always present — because a rotation that does not describe the present is rejected by the
// game and the lobby reports that stage information is unavailable.
//
// Output is deterministic for a given -at and -seed, so regenerating twice gives the same file
// and a diff shows only the time move.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"math/rand"
	"os"
	"time"

	"openpak/splatoon-3/internal/rotation"
)

// The versus rotation turns on a two-hour boundary. Co-op shifts and seasons are longer; the
// exact real-world cadence of each is not something this repository has established, and it does
// not have to match — what matters is that every kind is current and the windows are consistent.
const (
	vsPeriod     = 2 * time.Hour
	coopPeriod   = 24 * time.Hour
	seasonPeriod = 90 * 24 * time.Hour
)

func main() {
	out := flag.String("o", "rotation.json", "file to write")
	hours := flag.Int("hours", 72, "how many hours of rotation to generate, from now")
	stages := flag.Int("stages", 24, "number of stage ids to rotate through (see -h note)")
	seed := flag.Int64("seed", 1, "seed, so output is reproducible")
	atStr := flag.String("at", "", "anchor time (RFC3339); default now")
	flag.Parse()

	at := time.Now().UTC()
	if *atStr != "" {
		t, err := time.Parse(time.RFC3339, *atStr)
		if err != nil {
			fail("bad -at: %v", err)
		}
		at = t.UTC()
	}
	if *stages < 4 {
		fail("-stages must be at least 4: a versus window needs distinct stages for four ladders")
	}
	if *hours < 3 {
		fail("-hours must be at least 3: a rotation has to stay defined past the present")
	}

	f := generate(at, *hours, *stages, rand.New(rand.NewSource(*seed)))
	if err := f.Validate(at); err != nil {
		// The generator is held to the same rule as the loader: it must not be possible to write
		// a file the server would then refuse.
		fail("generated an invalid rotation (this is a bug in genrotation): %v", err)
	}
	b, err := json.MarshalIndent(f, "", "  ")
	if err != nil {
		fail("%v", err)
	}
	header := fmt.Sprintf("// Generated by cmd/genrotation, anchored at %s.\n"+
		"// Regenerate before it expires: the last versus window ends %s.\n",
		at.Format(time.RFC3339), lastVsEnd(f).Format(time.RFC3339))
	if err := os.WriteFile(*out, append([]byte(header), b...), 0o644); err != nil {
		fail("%v", err)
	}
	fmt.Printf("wrote %s: %d versus windows to %s\n", *out, len(f.Vs), lastVsEnd(f).Format(time.RFC3339))
}

func fail(format string, a ...any) {
	fmt.Fprintf(os.Stderr, "genrotation: "+format+"\n", a...)
	os.Exit(1)
}

func lastVsEnd(f *rotation.File) time.Time {
	if len(f.Vs) == 0 {
		return time.Time{}
	}
	return f.Vs[len(f.Vs)-1].End.UTC()
}

// generate builds a consistent set: every kind starts on or before `at`, and all of them are
// derived from the same anchor so they cannot disagree about the present.
func generate(at time.Time, hours, stages int, rng *rand.Rand) *rotation.File {
	f := &rotation.File{Version: rotation.Version}

	// Versus: aligned to the period boundary at or before the anchor, so "now" is always inside
	// the first window rather than in a gap before it.
	start := at.Truncate(vsPeriod)
	for i := 0; time.Duration(i)*vsPeriod < time.Duration(hours)*time.Hour; i++ {
		s := start.Add(time.Duration(i) * vsPeriod)
		f.Vs = append(f.Vs, rotation.VsWindow{
			Window:  rotation.Window{Start: s, End: s.Add(vsPeriod)},
			Regular: pick(rng, stages, 2),
			Bankara: []rotation.Mode{
				{Rule: rule(rng), Stages: pick(rng, stages, 2)},
				{Rule: rule(rng), Stages: pick(rng, stages, 2)},
			},
			X:      rotation.Mode{Rule: rule(rng), Stages: pick(rng, stages, 2)},
			League: rotation.Mode{Rule: rule(rng), Stages: pick(rng, stages, 2)},
		})
	}

	// Co-op: same treatment, longer period.
	coopStart := at.Truncate(coopPeriod)
	for i := 0; time.Duration(i)*coopPeriod < time.Duration(hours)*time.Hour+coopPeriod; i++ {
		s := coopStart.Add(time.Duration(i) * coopPeriod)
		f.Coop = append(f.Coop, rotation.CoopWindow{
			Window:      rotation.Window{Start: s, End: s.Add(coopPeriod)},
			Stage:       int32(rng.Intn(stages) + 1),
			Boss:        "boss-1",
			MainWeapons: []int64{1, 2, 3, 4},
			KumaWeapon:  1,
		})
	}

	// Season: one window wide enough that the anchor is comfortably inside it.
	seasonStart := at.Add(-seasonPeriod / 2).Truncate(24 * time.Hour)
	f.Season = []rotation.Window{{Start: seasonStart, End: seasonStart.Add(seasonPeriod)}}

	// League: one event spanning the generated range, with a slot per versus window so the game
	// has something inside it. The event must cover the anchor like every other kind.
	leagueEnd := start.Add(time.Duration(hours) * time.Hour)
	ev := rotation.LeagueWindow{
		Window: rotation.Window{Start: start, End: leagueEnd},
		Rule:   rule(rng),
		Stages: pick(rng, stages, 2),
	}
	for _, w := range f.Vs {
		ev.Slots = append(ev.Slots, rotation.Window{Start: w.Start, End: w.End})
	}
	f.League = []rotation.LeagueWindow{ev}

	f.Sort()
	return f
}

// rule picks one of the five versus rules. The numbering (0 turf war, then the four ranked
// rules) is the public SplatNet 3 ordering; see docs/provenance.md for what is and is not
// verified about these ids.
func rule(rng *rand.Rand) int32 { return int32(rng.Intn(5)) }

// pick chooses n distinct stage ids in 1..stages.
func pick(rng *rand.Rand, stages, n int) []int32 {
	seen := map[int]bool{}
	out := make([]int32, 0, n)
	for len(out) < n {
		v := rng.Intn(stages) + 1
		if seen[v] {
			continue
		}
		seen[v] = true
		out = append(out, int32(v))
	}
	return out
}
