// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/common/resources.proto

package common

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_proto_common_resources_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50000,
		Name:          "nn.npln.common.imported",
		Tag:           "varint,50000,opt,name=imported",
		Filename:      "proto/common/resources.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// optional bool imported = 50000;
	E_Imported = &file_proto_common_resources_proto_extTypes[0]
)

var File_proto_common_resources_proto protoreflect.FileDescriptor

const file_proto_common_resources_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/common/resources.proto\x12\x0enn.npln.common\x1a google/protobuf/descriptor.proto\x1a\x19google/api/resource.proto::\n" +
	"\bimported\x12\x1c.google.protobuf.FileOptions\x18І\x03 \x01(\bR\bimportedB8Z3npln.nintendo.net/npln-practice/proto/common;common\xf8\x01\x01b\x06proto3"

var file_proto_common_resources_proto_goTypes = []any{
	(*descriptorpb.FileOptions)(nil), // 0: google.protobuf.FileOptions
}
var file_proto_common_resources_proto_depIdxs = []int32{
	0, // 0: nn.npln.common.imported:extendee -> google.protobuf.FileOptions
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_common_resources_proto_init() }
func file_proto_common_resources_proto_init() {
	if File_proto_common_resources_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_common_resources_proto_rawDesc), len(file_proto_common_resources_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_proto_common_resources_proto_goTypes,
		DependencyIndexes: file_proto_common_resources_proto_depIdxs,
		ExtensionInfos:    file_proto_common_resources_proto_extTypes,
	}.Build()
	File_proto_common_resources_proto = out.File
	file_proto_common_resources_proto_goTypes = nil
	file_proto_common_resources_proto_depIdxs = nil
}
