// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: proto/matchmaking/v1/resources.proto

package matchmaking

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	common "openpak/stardew-valley/proto/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DelegationAction int32

const (
	DelegationAction_DELEGATION_ACTION_UNSPECIFIED    DelegationAction = 0
	DelegationAction_ANY_PARTICIPATION                DelegationAction = 1
	DelegationAction_ACCEPTANCE                       DelegationAction = 2
	DelegationAction_INCLUDE_ID_TOKEN_FOR_SAME_CLIENT DelegationAction = 3
)

// Enum value maps for DelegationAction.
var (
	DelegationAction_name = map[int32]string{
		0: "DELEGATION_ACTION_UNSPECIFIED",
		1: "ANY_PARTICIPATION",
		2: "ACCEPTANCE",
		3: "INCLUDE_ID_TOKEN_FOR_SAME_CLIENT",
	}
	DelegationAction_value = map[string]int32{
		"DELEGATION_ACTION_UNSPECIFIED":    0,
		"ANY_PARTICIPATION":                1,
		"ACCEPTANCE":                       2,
		"INCLUDE_ID_TOKEN_FOR_SAME_CLIENT": 3,
	}
)

func (x DelegationAction) Enum() *DelegationAction {
	p := new(DelegationAction)
	*p = x
	return p
}

func (x DelegationAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DelegationAction) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_matchmaking_v1_resources_proto_enumTypes[0].Descriptor()
}

func (DelegationAction) Type() protoreflect.EnumType {
	return &file_proto_matchmaking_v1_resources_proto_enumTypes[0]
}

func (x DelegationAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DelegationAction.Descriptor instead.
func (DelegationAction) EnumDescriptor() ([]byte, []int) {
	return file_proto_matchmaking_v1_resources_proto_rawDescGZIP(), []int{0}
}

type GameSessionCreationTicket_State int32

const (
	GameSessionCreationTicket_STATE_UNSPECIFIED GameSessionCreationTicket_State = 0
	GameSessionCreationTicket_PENDING           GameSessionCreationTicket_State = 1
	GameSessionCreationTicket_SUCCEEDED         GameSessionCreationTicket_State = 2
	GameSessionCreationTicket_CANCELLED         GameSessionCreationTicket_State = 3
	GameSessionCreationTicket_TIMED_OUT         GameSessionCreationTicket_State = 4
	GameSessionCreationTicket_FAILED            GameSessionCreationTicket_State = 5
)

// Enum value maps for GameSessionCreationTicket_State.
var (
	GameSessionCreationTicket_State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "PENDING",
		2: "SUCCEEDED",
		3: "CANCELLED",
		4: "TIMED_OUT",
		5: "FAILED",
	}
	GameSessionCreationTicket_State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"PENDING":           1,
		"SUCCEEDED":         2,
		"CANCELLED":         3,
		"TIMED_OUT":         4,
		"FAILED":            5,
	}
)

func (x GameSessionCreationTicket_State) Enum() *GameSessionCreationTicket_State {
	p := new(GameSessionCreationTicket_State)
	*p = x
	return p
}

func (x GameSessionCreationTicket_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameSessionCreationTicket_State) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_matchmaking_v1_resources_proto_enumTypes[1].Descriptor()
}

func (GameSessionCreationTicket_State) Type() protoreflect.EnumType {
	return &file_proto_matchmaking_v1_resources_proto_enumTypes[1]
}

func (x GameSessionCreationTicket_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameSessionCreationTicket_State.Descriptor instead.
func (GameSessionCreationTicket_State) EnumDescriptor() ([]byte, []int) {
	return file_proto_matchmaking_v1_resources_proto_rawDescGZIP(), []int{0, 0}
}

type UserSession_State int32

const (
	UserSession_STATE_UNSPECIFIED UserSession_State = 0
	UserSession_RESERVED          UserSession_State = 1
	UserSession_ACTIVE            UserSession_State = 2
)

// Enum value maps for UserSession_State.
var (
	UserSession_State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "RESERVED",
		2: "ACTIVE",
	}
	UserSession_State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"RESERVED":          1,
		"ACTIVE":            2,
	}
)

func (x UserSession_State) Enum() *UserSession_State {
	p := new(UserSession_State)
	*p = x
	return p
}

func (x UserSession_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserSession_State) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_matchmaking_v1_resources_proto_enumTypes[2].Descriptor()
}

func (UserSession_State) Type() protoreflect.EnumType {
	return &file_proto_matchmaking_v1_resources_proto_enumTypes[2]
}

func (x UserSession_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserSession_State.Descriptor instead.
func (UserSession_State) EnumDescriptor() ([]byte, []int) {
	return file_proto_matchmaking_v1_resources_proto_rawDescGZIP(), []int{2, 0}
}

type MatchmakingTicket_State int32

const (
	MatchmakingTicket_STATE_UNSPECIFIED    MatchmakingTicket_State = 0
	MatchmakingTicket_SEARCHING            MatchmakingTicket_State = 1
	MatchmakingTicket_PLACING              MatchmakingTicket_State = 2
	MatchmakingTicket_SUCCEEDED            MatchmakingTicket_State = 3
	MatchmakingTicket_TIMED_OUT            MatchmakingTicket_State = 4
	MatchmakingTicket_FAILED               MatchmakingTicket_State = 5
	MatchmakingTicket_CANCELLED            MatchmakingTicket_State = 6
	MatchmakingTicket_REQUIRING_ACCEPTANCE MatchmakingTicket_State = 7
	MatchmakingTicket_DECLINED             MatchmakingTicket_State = 8
)

// Enum value maps for MatchmakingTicket_State.
var (
	MatchmakingTicket_State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "SEARCHING",
		2: "PLACING",
		3: "SUCCEEDED",
		4: "TIMED_OUT",
		5: "FAILED",
		6: "CANCELLED",
		7: "REQUIRING_ACCEPTANCE",
		8: "DECLINED",
	}
	MatchmakingTicket_State_value = map[string]int32{
		"STATE_UNSPECIFIED":    0,
		"SEARCHING":            1,
		"PLACING":              2,
		"SUCCEEDED":            3,
		"TIMED_OUT":            4,
		"FAILED":               5,
		"CANCELLED":            6,
		"REQUIRING_ACCEPTANCE": 7,
		"DECLINED":             8,
	}
)

func (x MatchmakingTicket_State) Enum() *MatchmakingTicket_State {
	p := new(MatchmakingTicket_State)
	*p = x
	return p
}

func (x MatchmakingTicket_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MatchmakingTicket_State) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_matchmaking_v1_resources_proto_enumTypes[3].Descriptor()
}

func (MatchmakingTicket_State) Type() protoreflect.EnumType {
	return &file_proto_matchmaking_v1_resources_proto_enumTypes[3]
}

func (x MatchmakingTicket_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MatchmakingTicket_State.Descriptor instead.
func (MatchmakingTicket_State) EnumDescriptor() ([]byte, []int) {
	return file_proto_matchmaking_v1_resources_proto_rawDescGZIP(), []int{4, 0}
}

type GameSession_State int32

const (
	GameSession_STATE_UNSPECIFIED GameSession_State = 0
	GameSession_CREATING          GameSession_State = 1
	GameSession_ACTIVE            GameSession_State = 2
	GameSession_TERMINATING       GameSession_State = 3
	GameSession_TERMINATED        GameSession_State = 4
)

// Enum value maps for GameSession_State.
var (
	GameSession_State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "CREATING",
		2: "ACTIVE",
		3: "TERMINATING",
		4: "TERMINATED",
	}
	GameSession_State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"CREATING":          1,
		"ACTIVE":            2,
		"TERMINATING":       3,
		"TERMINATED":        4,
	}
)

func (x GameSession_State) Enum() *GameSession_State {
	p := new(GameSession_State)
	*p = x
	return p
}

func (x GameSession_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameSession_State) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_matchmaking_v1_resources_proto_enumTypes[4].Descriptor()
}

func (GameSession_State) Type() protoreflect.EnumType {
	return &file_proto_matchmaking_v1_resources_proto_enumTypes[4]
}

func (x GameSession_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameSession_State.Descriptor instead.
func (GameSession_State) EnumDescriptor() ([]byte, []int) {
	return file_proto_matchmaking_v1_resources_proto_rawDescGZIP(), []int{6, 0}
}

type StunServer_Protocol int32

const (
	StunServer_PROTOCOL_UNSPECIFIED StunServer_Protocol = 0
	StunServer_UDP                  StunServer_Protocol = 1
	StunServer_TCP                  StunServer_Protocol = 2
	StunServer_TLS                  StunServer_Protocol = 3
)

// Enum value maps for StunServer_Protocol.
var (
	StunServer_Protocol_name = map[int32]string{
		0: "PROTOCOL_UNSPECIFIED",
		1: "UDP",
		2: "TCP",
		3: "TLS",
	}
	StunServer_Protocol_value = map[string]int32{
		"PROTOCOL_UNSPECIFIED": 0,
		"UDP":                  1,
		"TCP":                  2,
		"TLS":                  3,
	}
)

func (x StunServer_Protocol) Enum() *StunServer_Protocol {
	p := new(StunServer_Protocol)
	*p = x
	return p
}

func (x StunServer_Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StunServer_Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_matchmaking_v1_resources_proto_enumTypes[5].Descriptor()
}

func (StunServer_Protocol) Type() protoreflect.EnumType {
	return &file_proto_matchmaking_v1_resources_proto_enumTypes[5]
}

func (x StunServer_Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StunServer_Protocol.Descriptor instead.
func (StunServer_Protocol) EnumDescriptor() ([]byte, []int) {
	return file_proto_matchmaking_v1_resources_proto_rawDescGZIP(), []int{12, 0}
}

type TurnServer_Protocol int32

const (
	TurnServer_PROTOCOL_UNSPECIFIED TurnServer_Protocol = 0
	TurnServer_UDP                  TurnServer_Protocol = 1
	TurnServer_TCP                  TurnServer_Protocol = 2
	TurnServer_TLS                  TurnServer_Protocol = 3
)

// Enum value maps for TurnServer_Protocol.
var (
	TurnServer_Protocol_name = map[int32]string{
		0: "PROTOCOL_UNSPECIFIED",
		1: "UDP",
		2: "TCP",
		3: "TLS",
	}
	TurnServer_Protocol_value = map[string]int32{
		"PROTOCOL_UNSPECIFIED": 0,
		"UDP":                  1,
		"TCP":                  2,
		"TLS":                  3,
	}
)

func (x TurnServer_Protocol) Enum() *TurnServer_Protocol {
	p := new(TurnServer_Protocol)
	*p = x
	return p
}

func (x TurnServer_Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TurnServer_Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_matchmaking_v1_resources_proto_enumTypes[6].Descriptor()
}

func (TurnServer_Protocol) Type() protoreflect.EnumType {
	return &file_proto_matchmaking_v1_resources_proto_enumTypes[6]
}

func (x TurnServer_Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TurnServer_Protocol.Descriptor instead.
func (TurnServer_Protocol) EnumDescriptor() ([]byte, []int) {
	return file_proto_matchmaking_v1_resources_proto_rawDescGZIP(), []int{13, 0}
}

type LatencyMeasurementServer_Protocol int32

const (
	LatencyMeasurementServer_PROTOCOL_UNSPECIFIED LatencyMeasurementServer_Protocol = 0
	LatencyMeasurementServer_UDP                  LatencyMeasurementServer_Protocol = 1
	LatencyMeasurementServer_TCP                  LatencyMeasurementServer_Protocol = 2
	LatencyMeasurementServer_HTTP                 LatencyMeasurementServer_Protocol = 3
)

// Enum value maps for LatencyMeasurementServer_Protocol.
var (
	LatencyMeasurementServer_Protocol_name = map[int32]string{
		0: "PROTOCOL_UNSPECIFIED",
		1: "UDP",
		2: "TCP",
		3: "HTTP",
	}
	LatencyMeasurementServer_Protocol_value = map[string]int32{
		"PROTOCOL_UNSPECIFIED": 0,
		"UDP":                  1,
		"TCP":                  2,
		"HTTP":                 3,
	}
)

func (x LatencyMeasurementServer_Protocol) Enum() *LatencyMeasurementServer_Protocol {
	p := new(LatencyMeasurementServer_Protocol)
	*p = x
	return p
}

func (x LatencyMeasurementServer_Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LatencyMeasurementServer_Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_matchmaking_v1_resources_proto_enumTypes[7].Descriptor()
}

func (LatencyMeasurementServer_Protocol) Type() protoreflect.EnumType {
	return &file_proto_matchmaking_v1_resources_proto_enumTypes[7]
}

func (x LatencyMeasurementServer_Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LatencyMeasurementServer_Protocol.Descriptor instead.
func (LatencyMeasurementServer_Protocol) EnumDescriptor() ([]byte, []int) {
	return file_proto_matchmaking_v1_resources_proto_rawDescGZIP(), []int{14, 0}
}

type GameSessionCreationTicket struct {
	state               protoimpl.MessageState          `protogen:"open.v1"`
	Name                string                          `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MatchmakingConfig   string                          `protobuf:"bytes,2,opt,name=matchmaking_config,json=matchmakingConfig,proto3" json:"matchmaking_config,omitempty"`
	UserDefinitions     []*UserDefinition               `protobuf:"bytes,3,rep,name=user_definitions,json=userDefinitions,proto3" json:"user_definitions,omitempty"`
	State               GameSessionCreationTicket_State `protobuf:"varint,4,opt,name=state,proto3,enum=nn.npln.matchmaking.v1.GameSessionCreationTicket_State" json:"state,omitempty"`
	MatchedUserSessions []*MatchedUserSession           `protobuf:"bytes,5,rep,name=matched_user_sessions,json=matchedUserSessions,proto3" json:"matched_user_sessions,omitempty"`
	GameSession         *GameSession                    `protobuf:"bytes,6,opt,name=game_session,json=gameSession,proto3" json:"game_session,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GameSessionCreationTicket) Reset() {
	*x = GameSessionCreationTicket{}
	mi := &file_proto_matchmaking_v1_resources_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameSessionCreationTicket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameSessionCreationTicket) ProtoMessage() {}

func (x *GameSessionCreationTicket) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matchmaking_v1_resources_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameSessionCreationTicket.ProtoReflect.Descriptor instead.
func (*GameSessionCreationTicket) Descriptor() ([]byte, []int) {
	return file_proto_matchmaking_v1_resources_proto_rawDescGZIP(), []int{0}
}

func (x *GameSessionCreationTicket) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GameSessionCreationTicket) GetMatchmakingConfig() string {
	if x != nil {
		return x.MatchmakingConfig
	}
	return ""
}

func (x *GameSessionCreationTicket) GetUserDefinitions() []*UserDefinition {
	if x != nil {
		return x.UserDefinitions
	}
	return nil
}

func (x *GameSessionCreationTicket) GetState() GameSessionCreationTicket_State {
	if x != nil {
		return x.State
	}
	return GameSessionCreationTicket_STATE_UNSPECIFIED
}

func (x *GameSessionCreationTicket) GetMatchedUserSessions() []*MatchedUserSession {
	if x != nil {
		return x.MatchedUserSessions
	}
	return nil
}

func (x *GameSessionCreationTicket) GetGameSession() *GameSession {
	if x != nil {
		return x.GameSession
	}
	return nil
}

type UserDelegationDetail struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	DelegatorUser       string                 `protobuf:"bytes,1,opt,name=delegator_user,json=delegatorUser,proto3" json:"delegator_user,omitempty"`
	MandataryUser       string                 `protobuf:"bytes,2,opt,name=mandatary_user,json=mandataryUser,proto3" json:"mandatary_user,omitempty"`
	Attributes          *common.MapValue       `protobuf:"bytes,3,opt,name=attributes,proto3" json:"attributes,omitempty"`
	DelegationActions   []DelegationAction     `protobuf:"varint,4,rep,packed,name=delegation_actions,json=delegationActions,proto3,enum=nn.npln.matchmaking.v1.DelegationAction" json:"delegation_actions,omitempty"`
	UserDelegationToken string                 `protobuf:"bytes,5,opt,name=user_delegation_token,json=userDelegationToken,proto3" json:"user_delegation_token,omitempty"`
	Ttl                 *durationpb.Duration   `protobuf:"bytes,6,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UserDelegationDetail) Reset() {
	*x = UserDelegationDetail{}
	mi := &file_proto_matchmaking_v1_resources_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDelegationDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDelegationDetail) ProtoMessage() {}

func (x *UserDelegationDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matchmaking_v1_resources_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDelegationDetail.ProtoReflect.Descriptor instead.
func (*UserDelegationDetail) Descriptor() ([]byte, []int) {
	return file_proto_matchmaking_v1_resources_proto_rawDescGZIP(), []int{1}
}

func (x *UserDelegationDetail) GetDelegatorUser() string {
	if x != nil {
		return x.DelegatorUser
	}
	return ""
}

func (x *UserDelegationDetail) GetMandataryUser() string {
	if x != nil {
		return x.MandataryUser
	}
	return ""
}

func (x *UserDelegationDetail) GetAttributes() *common.MapValue {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *UserDelegationDetail) GetDelegationActions() []DelegationAction {
	if x != nil {
		return x.DelegationActions
	}
	return nil
}

func (x *UserDelegationDetail) GetUserDelegationToken() string {
	if x != nil {
		return x.UserDelegationToken
	}
	return ""
}

func (x *UserDelegationDetail) GetTtl() *durationpb.Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

type UserSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	User          string                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	LatencyData   *LatencyData           `protobuf:"bytes,3,opt,name=latency_data,json=latencyData,proto3" json:"latency_data,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	State         UserSession_State      `protobuf:"varint,5,opt,name=state,proto3,enum=nn.npln.matchmaking.v1.UserSession_State" json:"state,omitempty"`
	Team          string                 `protobuf:"bytes,6,opt,name=team,proto3" json:"team,omitempty"`
	Attributes    *common.MapValue       `protobuf:"bytes,7,opt,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSession) Reset() {
	*x = UserSession{}
	mi := &file_proto_matchmaking_v1_resources_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSession) ProtoMessage() {}

func (x *UserSession) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matchmaking_v1_resources_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSession.ProtoReflect.Descriptor instead.
func (*UserSession) Descriptor() ([]byte, []int) {
	return file_proto_matchmaking_v1_resources_proto_rawDescGZIP(), []int{2}
}

func (x *UserSession) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserSession) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *UserSession) GetLatencyData() *LatencyData {
	if x != nil {
		return x.LatencyData
	}
	return nil
}

func (x *UserSession) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *UserSession) GetState() UserSession_State {
	if x != nil {
		return x.State
	}
	return UserSession_STATE_UNSPECIFIED
}

func (x *UserSession) GetTeam() string {
	if x != nil {
		return x.Team
	}
	return ""
}

func (x *UserSession) GetAttributes() *common.MapValue {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type GameSessionShortAlias struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	GameSession   string                 `protobuf:"bytes,2,opt,name=game_session,json=gameSession,proto3" json:"game_session,omitempty"`
	ExpireTime    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameSessionShortAlias) Reset() {
	*x = GameSessionShortAlias{}
	mi := &file_proto_matchmaking_v1_resources_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameSessionShortAlias) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameSessionShortAlias) ProtoMessage() {}

func (x *GameSessionShortAlias) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matchmaking_v1_resources_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameSessionShortAlias.ProtoReflect.Descriptor instead.
func (*GameSessionShortAlias) Descriptor() ([]byte, []int) {
	return file_proto_matchmaking_v1_resources_proto_rawDescGZIP(), []int{3}
}

func (x *GameSessionShortAlias) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GameSessionShortAlias) GetGameSession() string {
	if x != nil {
		return x.GameSession
	}
	return ""
}

func (x *GameSessionShortAlias) GetExpireTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpireTime
	}
	return nil
}

type MatchmakingTicket struct {
	state               protoimpl.MessageState  `protogen:"open.v1"`
	Name                string                  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MatchmakingConfig   string                  `protobuf:"bytes,2,opt,name=matchmaking_config,json=matchmakingConfig,proto3" json:"matchmaking_config,omitempty"`
	Backfill            *Backfill               `protobuf:"bytes,3,opt,name=backfill,proto3" json:"backfill,omitempty"`
	UserDefinitions     []*UserDefinition       `protobuf:"bytes,4,rep,name=user_definitions,json=userDefinitions,proto3" json:"user_definitions,omitempty"`
	State               MatchmakingTicket_State `protobuf:"varint,5,opt,name=state,proto3,enum=nn.npln.matchmaking.v1.MatchmakingTicket_State" json:"state,omitempty"`
	MatchedUserSessions []*MatchedUserSession   `protobuf:"bytes,6,rep,name=matched_user_sessions,json=matchedUserSessions,proto3" json:"matched_user_sessions,omitempty"`
	GameSession         *GameSession            `protobuf:"bytes,7,opt,name=game_session,json=gameSession,proto3" json:"game_session,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MatchmakingTicket) Reset() {
	*x = MatchmakingTicket{}
	mi := &file_proto_matchmaking_v1_resources_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchmakingTicket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchmakingTicket) ProtoMessage() {}

func (x *MatchmakingTicket) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matchmaking_v1_resources_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchmakingTicket.ProtoReflect.Descriptor instead.
func (*MatchmakingTicket) Descriptor() ([]byte, []int) {
	return file_proto_matchmaking_v1_resources_proto_rawDescGZIP(), []int{4}
}

func (x *MatchmakingTicket) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MatchmakingTicket) GetMatchmakingConfig() string {
	if x != nil {
		return x.MatchmakingConfig
	}
	return ""
}

func (x *MatchmakingTicket) GetBackfill() *Backfill {
	if x != nil {
		return x.Backfill
	}
	return nil
}

func (x *MatchmakingTicket) GetUserDefinitions() []*UserDefinition {
	if x != nil {
		return x.UserDefinitions
	}
	return nil
}

func (x *MatchmakingTicket) GetState() MatchmakingTicket_State {
	if x != nil {
		return x.State
	}
	return MatchmakingTicket_STATE_UNSPECIFIED
}

func (x *MatchmakingTicket) GetMatchedUserSessions() []*MatchedUserSession {
	if x != nil {
		return x.MatchedUserSessions
	}
	return nil
}

func (x *MatchmakingTicket) GetGameSession() *GameSession {
	if x != nil {
		return x.GameSession
	}
	return nil
}

type Backfill struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameSession   string                 `protobuf:"bytes,1,opt,name=game_session,json=gameSession,proto3" json:"game_session,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Backfill) Reset() {
	*x = Backfill{}
	mi := &file_proto_matchmaking_v1_resources_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Backfill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Backfill) ProtoMessage() {}

func (x *Backfill) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matchmaking_v1_resources_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Backfill.ProtoReflect.Descriptor instead.
func (*Backfill) Descriptor() ([]byte, []int) {
	return file_proto_matchmaking_v1_resources_proto_rawDescGZIP(), []int{5}
}

func (x *Backfill) GetGameSession() string {
	if x != nil {
		return x.GameSession
	}
	return ""
}

func (x *Backfill) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Backfill) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type GameSession struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Name                    string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MaxParticipantCount     int32                  `protobuf:"varint,2,opt,name=max_participant_count,json=maxParticipantCount,proto3" json:"max_participant_count,omitempty"`
	CurrentParticipantCount int32                  `protobuf:"varint,3,opt,name=current_participant_count,json=currentParticipantCount,proto3" json:"current_participant_count,omitempty"`
	CanParticipate          bool                   `protobuf:"varint,4,opt,name=can_participate,json=canParticipate,proto3" json:"can_participate,omitempty"`
	IsPublic                bool                   `protobuf:"varint,5,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	Password                string                 `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	State                   GameSession_State      `protobuf:"varint,7,opt,name=state,proto3,enum=nn.npln.matchmaking.v1.GameSession_State" json:"state,omitempty"`
	Host                    string                 `protobuf:"bytes,8,opt,name=host,proto3" json:"host,omitempty"`
	Port                    int32                  `protobuf:"varint,9,opt,name=port,proto3" json:"port,omitempty"`
	CreateTime              *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	Properties              *common.MapValue       `protobuf:"bytes,11,opt,name=properties,proto3" json:"properties,omitempty"`
	UserSessions            []*UserSession         `protobuf:"bytes,12,rep,name=user_sessions,json=userSessions,proto3" json:"user_sessions,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *GameSession) Reset() {
	*x = GameSession{}
	mi := &file_proto_matchmaking_v1_resources_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameSession) ProtoMessage() {}

func (x *GameSession) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matchmaking_v1_resources_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameSession.ProtoReflect.Descriptor instead.
func (*GameSession) Descriptor() ([]byte, []int) {
	return file_proto_matchmaking_v1_resources_proto_rawDescGZIP(), []int{6}
}

func (x *GameSession) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GameSession) GetMaxParticipantCount() int32 {
	if x != nil {
		return x.MaxParticipantCount
	}
	return 0
}

func (x *GameSession) GetCurrentParticipantCount() int32 {
	if x != nil {
		return x.CurrentParticipantCount
	}
	return 0
}

func (x *GameSession) GetCanParticipate() bool {
	if x != nil {
		return x.CanParticipate
	}
	return false
}

func (x *GameSession) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

func (x *GameSession) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *GameSession) GetState() GameSession_State {
	if x != nil {
		return x.State
	}
	return GameSession_STATE_UNSPECIFIED
}

func (x *GameSession) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *GameSession) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *GameSession) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *GameSession) GetProperties() *common.MapValue {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *GameSession) GetUserSessions() []*UserSession {
	if x != nil {
		return x.UserSessions
	}
	return nil
}

type MatchedUserSession struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	UserDefinition     *UserDefinition        `protobuf:"bytes,1,opt,name=user_definition,json=userDefinition,proto3" json:"user_definition,omitempty"`
	UserSession        string                 `protobuf:"bytes,2,opt,name=user_session,json=userSession,proto3" json:"user_session,omitempty"`
	MatchmakingIdToken string                 `protobuf:"bytes,3,opt,name=matchmaking_id_token,json=matchmakingIdToken,proto3" json:"matchmaking_id_token,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MatchedUserSession) Reset() {
	*x = MatchedUserSession{}
	mi := &file_proto_matchmaking_v1_resources_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchedUserSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchedUserSession) ProtoMessage() {}

func (x *MatchedUserSession) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matchmaking_v1_resources_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchedUserSession.ProtoReflect.Descriptor instead.
func (*MatchedUserSession) Descriptor() ([]byte, []int) {
	return file_proto_matchmaking_v1_resources_proto_rawDescGZIP(), []int{7}
}

func (x *MatchedUserSession) GetUserDefinition() *UserDefinition {
	if x != nil {
		return x.UserDefinition
	}
	return nil
}

func (x *MatchedUserSession) GetUserSession() string {
	if x != nil {
		return x.UserSession
	}
	return ""
}

func (x *MatchedUserSession) GetMatchmakingIdToken() string {
	if x != nil {
		return x.MatchmakingIdToken
	}
	return ""
}

type UserDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Attributes    *common.MapValue       `protobuf:"bytes,2,opt,name=attributes,proto3" json:"attributes,omitempty"`
	LatencyData   *LatencyData           `protobuf:"bytes,3,opt,name=latency_data,json=latencyData,proto3" json:"latency_data,omitempty"`
	Team          string                 `protobuf:"bytes,4,opt,name=team,proto3" json:"team,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDefinition) Reset() {
	*x = UserDefinition{}
	mi := &file_proto_matchmaking_v1_resources_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDefinition) ProtoMessage() {}

func (x *UserDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matchmaking_v1_resources_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDefinition.ProtoReflect.Descriptor instead.
func (*UserDefinition) Descriptor() ([]byte, []int) {
	return file_proto_matchmaking_v1_resources_proto_rawDescGZIP(), []int{8}
}

func (x *UserDefinition) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *UserDefinition) GetAttributes() *common.MapValue {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *UserDefinition) GetLatencyData() *LatencyData {
	if x != nil {
		return x.LatencyData
	}
	return nil
}

func (x *UserDefinition) GetTeam() string {
	if x != nil {
		return x.Team
	}
	return ""
}

type LatencyData struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Latencies     map[string]*durationpb.Duration `protobuf:"bytes,1,rep,name=latencies,proto3" json:"latencies,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LatencyData) Reset() {
	*x = LatencyData{}
	mi := &file_proto_matchmaking_v1_resources_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatencyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatencyData) ProtoMessage() {}

func (x *LatencyData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matchmaking_v1_resources_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatencyData.ProtoReflect.Descriptor instead.
func (*LatencyData) Descriptor() ([]byte, []int) {
	return file_proto_matchmaking_v1_resources_proto_rawDescGZIP(), []int{9}
}

func (x *LatencyData) GetLatencies() map[string]*durationpb.Duration {
	if x != nil {
		return x.Latencies
	}
	return nil
}

type Acceptance struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Name                 string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Users                []string               `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	Accepted             bool                   `protobuf:"varint,3,opt,name=accepted,proto3" json:"accepted,omitempty"`
	UserDelegationTokens []string               `protobuf:"bytes,4,rep,name=user_delegation_tokens,json=userDelegationTokens,proto3" json:"user_delegation_tokens,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Acceptance) Reset() {
	*x = Acceptance{}
	mi := &file_proto_matchmaking_v1_resources_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Acceptance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Acceptance) ProtoMessage() {}

func (x *Acceptance) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matchmaking_v1_resources_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Acceptance.ProtoReflect.Descriptor instead.
func (*Acceptance) Descriptor() ([]byte, []int) {
	return file_proto_matchmaking_v1_resources_proto_rawDescGZIP(), []int{10}
}

func (x *Acceptance) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Acceptance) GetUsers() []string {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *Acceptance) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *Acceptance) GetUserDelegationTokens() []string {
	if x != nil {
		return x.UserDelegationTokens
	}
	return nil
}

type IceServerSet struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Name                string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	StunServer          *StunServer            `protobuf:"bytes,2,opt,name=stun_server,json=stunServer,proto3" json:"stun_server,omitempty"`
	TurnServers         []*TurnServer          `protobuf:"bytes,3,rep,name=turn_servers,json=turnServers,proto3" json:"turn_servers,omitempty"`
	Ttl                 *durationpb.Duration   `protobuf:"bytes,4,opt,name=ttl,proto3" json:"ttl,omitempty"`
	UpdateTime          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	ClientCacheDuration *durationpb.Duration   `protobuf:"bytes,6,opt,name=client_cache_duration,json=clientCacheDuration,proto3" json:"client_cache_duration,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *IceServerSet) Reset() {
	*x = IceServerSet{}
	mi := &file_proto_matchmaking_v1_resources_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IceServerSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IceServerSet) ProtoMessage() {}

func (x *IceServerSet) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matchmaking_v1_resources_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IceServerSet.ProtoReflect.Descriptor instead.
func (*IceServerSet) Descriptor() ([]byte, []int) {
	return file_proto_matchmaking_v1_resources_proto_rawDescGZIP(), []int{11}
}

func (x *IceServerSet) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *IceServerSet) GetStunServer() *StunServer {
	if x != nil {
		return x.StunServer
	}
	return nil
}

func (x *IceServerSet) GetTurnServers() []*TurnServer {
	if x != nil {
		return x.TurnServers
	}
	return nil
}

func (x *IceServerSet) GetTtl() *durationpb.Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

func (x *IceServerSet) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *IceServerSet) GetClientCacheDuration() *durationpb.Duration {
	if x != nil {
		return x.ClientCacheDuration
	}
	return nil
}

type StunServer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Protocol      StunServer_Protocol    `protobuf:"varint,3,opt,name=protocol,proto3,enum=nn.npln.matchmaking.v1.StunServer_Protocol" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StunServer) Reset() {
	*x = StunServer{}
	mi := &file_proto_matchmaking_v1_resources_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StunServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StunServer) ProtoMessage() {}

func (x *StunServer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matchmaking_v1_resources_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StunServer.ProtoReflect.Descriptor instead.
func (*StunServer) Descriptor() ([]byte, []int) {
	return file_proto_matchmaking_v1_resources_proto_rawDescGZIP(), []int{12}
}

func (x *StunServer) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *StunServer) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *StunServer) GetProtocol() StunServer_Protocol {
	if x != nil {
		return x.Protocol
	}
	return StunServer_PROTOCOL_UNSPECIFIED
}

type TurnServer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Protocol      TurnServer_Protocol    `protobuf:"varint,3,opt,name=protocol,proto3,enum=nn.npln.matchmaking.v1.TurnServer_Protocol" json:"protocol,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TurnServer) Reset() {
	*x = TurnServer{}
	mi := &file_proto_matchmaking_v1_resources_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TurnServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurnServer) ProtoMessage() {}

func (x *TurnServer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matchmaking_v1_resources_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TurnServer.ProtoReflect.Descriptor instead.
func (*TurnServer) Descriptor() ([]byte, []int) {
	return file_proto_matchmaking_v1_resources_proto_rawDescGZIP(), []int{13}
}

func (x *TurnServer) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *TurnServer) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *TurnServer) GetProtocol() TurnServer_Protocol {
	if x != nil {
		return x.Protocol
	}
	return TurnServer_PROTOCOL_UNSPECIFIED
}

func (x *TurnServer) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *TurnServer) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LatencyMeasurementServer struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Name          string                            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Region        string                            `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Host          string                            `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                             `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	Protocol      LatencyMeasurementServer_Protocol `protobuf:"varint,5,opt,name=protocol,proto3,enum=nn.npln.matchmaking.v1.LatencyMeasurementServer_Protocol" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LatencyMeasurementServer) Reset() {
	*x = LatencyMeasurementServer{}
	mi := &file_proto_matchmaking_v1_resources_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatencyMeasurementServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatencyMeasurementServer) ProtoMessage() {}

func (x *LatencyMeasurementServer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matchmaking_v1_resources_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatencyMeasurementServer.ProtoReflect.Descriptor instead.
func (*LatencyMeasurementServer) Descriptor() ([]byte, []int) {
	return file_proto_matchmaking_v1_resources_proto_rawDescGZIP(), []int{14}
}

func (x *LatencyMeasurementServer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LatencyMeasurementServer) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *LatencyMeasurementServer) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *LatencyMeasurementServer) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *LatencyMeasurementServer) GetProtocol() LatencyMeasurementServer_Protocol {
	if x != nil {
		return x.Protocol
	}
	return LatencyMeasurementServer_PROTOCOL_UNSPECIFIED
}

var file_proto_matchmaking_v1_resources_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50005,
		Name:          "nn.npln.matchmaking.v1.imported",
		Tag:           "varint,50005,opt,name=imported",
		Filename:      "proto/matchmaking/v1/resources.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// optional bool imported = 50005;
	E_Imported = &file_proto_matchmaking_v1_resources_proto_extTypes[0]
)

var File_proto_matchmaking_v1_resources_proto protoreflect.FileDescriptor

const file_proto_matchmaking_v1_resources_proto_rawDesc = "" +
	"\n" +
	"$proto/matchmaking/v1/resources.proto\x12\x16nn.npln.matchmaking.v1\x1a google/protobuf/descriptor.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x18proto/common/value.proto\"\x8e\x04\n" +
	"\x19GameSessionCreationTicket\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12-\n" +
	"\x12matchmaking_config\x18\x02 \x01(\tR\x11matchmakingConfig\x12Q\n" +
	"\x10user_definitions\x18\x03 \x03(\v2&.nn.npln.matchmaking.v1.UserDefinitionR\x0fuserDefinitions\x12M\n" +
	"\x05state\x18\x04 \x01(\x0e27.nn.npln.matchmaking.v1.GameSessionCreationTicket.StateR\x05state\x12^\n" +
	"\x15matched_user_sessions\x18\x05 \x03(\v2*.nn.npln.matchmaking.v1.MatchedUserSessionR\x13matchedUserSessions\x12F\n" +
	"\fgame_session\x18\x06 \x01(\v2#.nn.npln.matchmaking.v1.GameSessionR\vgameSession\"d\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\r\n" +
	"\tSUCCEEDED\x10\x02\x12\r\n" +
	"\tCANCELLED\x10\x03\x12\r\n" +
	"\tTIMED_OUT\x10\x04\x12\n" +
	"\n" +
	"\x06FAILED\x10\x05\"\xd8\x02\n" +
	"\x14UserDelegationDetail\x12%\n" +
	"\x0edelegator_user\x18\x01 \x01(\tR\rdelegatorUser\x12%\n" +
	"\x0emandatary_user\x18\x02 \x01(\tR\rmandataryUser\x128\n" +
	"\n" +
	"attributes\x18\x03 \x01(\v2\x18.nn.npln.common.MapValueR\n" +
	"attributes\x12W\n" +
	"\x12delegation_actions\x18\x04 \x03(\x0e2(.nn.npln.matchmaking.v1.DelegationActionR\x11delegationActions\x122\n" +
	"\x15user_delegation_token\x18\x05 \x01(\tR\x13userDelegationToken\x12+\n" +
	"\x03ttl\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\x03ttl\"\x83\x03\n" +
	"\vUserSession\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\x12F\n" +
	"\flatency_data\x18\x03 \x01(\v2#.nn.npln.matchmaking.v1.LatencyDataR\vlatencyData\x12;\n" +
	"\vcreate_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12?\n" +
	"\x05state\x18\x05 \x01(\x0e2).nn.npln.matchmaking.v1.UserSession.StateR\x05state\x12\x12\n" +
	"\x04team\x18\x06 \x01(\tR\x04team\x128\n" +
	"\n" +
	"attributes\x18\a \x01(\v2\x18.nn.npln.common.MapValueR\n" +
	"attributes\"8\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bRESERVED\x10\x01\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x02\"\x8b\x01\n" +
	"\x15GameSessionShortAlias\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fgame_session\x18\x02 \x01(\tR\vgameSession\x12;\n" +
	"\vexpire_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"expireTime\"\xf4\x04\n" +
	"\x11MatchmakingTicket\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12-\n" +
	"\x12matchmaking_config\x18\x02 \x01(\tR\x11matchmakingConfig\x12<\n" +
	"\bbackfill\x18\x03 \x01(\v2 .nn.npln.matchmaking.v1.BackfillR\bbackfill\x12Q\n" +
	"\x10user_definitions\x18\x04 \x03(\v2&.nn.npln.matchmaking.v1.UserDefinitionR\x0fuserDefinitions\x12E\n" +
	"\x05state\x18\x05 \x01(\x0e2/.nn.npln.matchmaking.v1.MatchmakingTicket.StateR\x05state\x12^\n" +
	"\x15matched_user_sessions\x18\x06 \x03(\v2*.nn.npln.matchmaking.v1.MatchedUserSessionR\x13matchedUserSessions\x12F\n" +
	"\fgame_session\x18\a \x01(\v2#.nn.npln.matchmaking.v1.GameSessionR\vgameSession\"\x9b\x01\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tSEARCHING\x10\x01\x12\v\n" +
	"\aPLACING\x10\x02\x12\r\n" +
	"\tSUCCEEDED\x10\x03\x12\r\n" +
	"\tTIMED_OUT\x10\x04\x12\n" +
	"\n" +
	"\x06FAILED\x10\x05\x12\r\n" +
	"\tCANCELLED\x10\x06\x12\x18\n" +
	"\x14REQUIRING_ACCEPTANCE\x10\a\x12\f\n" +
	"\bDECLINED\x10\b\"U\n" +
	"\bBackfill\x12!\n" +
	"\fgame_session\x18\x01 \x01(\tR\vgameSession\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\"\xf8\x04\n" +
	"\vGameSession\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x122\n" +
	"\x15max_participant_count\x18\x02 \x01(\x05R\x13maxParticipantCount\x12:\n" +
	"\x19current_participant_count\x18\x03 \x01(\x05R\x17currentParticipantCount\x12'\n" +
	"\x0fcan_participate\x18\x04 \x01(\bR\x0ecanParticipate\x12\x1b\n" +
	"\tis_public\x18\x05 \x01(\bR\bisPublic\x12\x1a\n" +
	"\bpassword\x18\x06 \x01(\tR\bpassword\x12?\n" +
	"\x05state\x18\a \x01(\x0e2).nn.npln.matchmaking.v1.GameSession.StateR\x05state\x12\x12\n" +
	"\x04host\x18\b \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\t \x01(\x05R\x04port\x12;\n" +
	"\vcreate_time\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x128\n" +
	"\n" +
	"properties\x18\v \x01(\v2\x18.nn.npln.common.MapValueR\n" +
	"properties\x12H\n" +
	"\ruser_sessions\x18\f \x03(\v2#.nn.npln.matchmaking.v1.UserSessionR\fuserSessions\"Y\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bCREATING\x10\x01\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x02\x12\x0f\n" +
	"\vTERMINATING\x10\x03\x12\x0e\n" +
	"\n" +
	"TERMINATED\x10\x04\"\xba\x01\n" +
	"\x12MatchedUserSession\x12O\n" +
	"\x0fuser_definition\x18\x01 \x01(\v2&.nn.npln.matchmaking.v1.UserDefinitionR\x0euserDefinition\x12!\n" +
	"\fuser_session\x18\x02 \x01(\tR\vuserSession\x120\n" +
	"\x14matchmaking_id_token\x18\x03 \x01(\tR\x12matchmakingIdToken\"\xba\x01\n" +
	"\x0eUserDefinition\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x128\n" +
	"\n" +
	"attributes\x18\x02 \x01(\v2\x18.nn.npln.common.MapValueR\n" +
	"attributes\x12F\n" +
	"\flatency_data\x18\x03 \x01(\v2#.nn.npln.matchmaking.v1.LatencyDataR\vlatencyData\x12\x12\n" +
	"\x04team\x18\x04 \x01(\tR\x04team\"\xb8\x01\n" +
	"\vLatencyData\x12P\n" +
	"\tlatencies\x18\x01 \x03(\v22.nn.npln.matchmaking.v1.LatencyData.LatenciesEntryR\tlatencies\x1aW\n" +
	"\x0eLatenciesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x05value:\x028\x01\"\x88\x01\n" +
	"\n" +
	"Acceptance\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05users\x18\x02 \x03(\tR\x05users\x12\x1a\n" +
	"\baccepted\x18\x03 \x01(\bR\baccepted\x124\n" +
	"\x16user_delegation_tokens\x18\x04 \x03(\tR\x14userDelegationTokens\"\xe7\x02\n" +
	"\fIceServerSet\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12C\n" +
	"\vstun_server\x18\x02 \x01(\v2\".nn.npln.matchmaking.v1.StunServerR\n" +
	"stunServer\x12E\n" +
	"\fturn_servers\x18\x03 \x03(\v2\".nn.npln.matchmaking.v1.TurnServerR\vturnServers\x12+\n" +
	"\x03ttl\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\x03ttl\x12;\n" +
	"\vupdate_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\x12M\n" +
	"\x15client_cache_duration\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\x13clientCacheDuration\"\xbe\x01\n" +
	"\n" +
	"StunServer\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12G\n" +
	"\bprotocol\x18\x03 \x01(\x0e2+.nn.npln.matchmaking.v1.StunServer.ProtocolR\bprotocol\"?\n" +
	"\bProtocol\x12\x18\n" +
	"\x14PROTOCOL_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03UDP\x10\x01\x12\a\n" +
	"\x03TCP\x10\x02\x12\a\n" +
	"\x03TLS\x10\x03\"\xf6\x01\n" +
	"\n" +
	"TurnServer\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12G\n" +
	"\bprotocol\x18\x03 \x01(\x0e2+.nn.npln.matchmaking.v1.TurnServer.ProtocolR\bprotocol\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\"?\n" +
	"\bProtocol\x12\x18\n" +
	"\x14PROTOCOL_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03UDP\x10\x01\x12\a\n" +
	"\x03TCP\x10\x02\x12\a\n" +
	"\x03TLS\x10\x03\"\x87\x02\n" +
	"\x18LatencyMeasurementServer\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x12\n" +
	"\x04host\x18\x03 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x12U\n" +
	"\bprotocol\x18\x05 \x01(\x0e29.nn.npln.matchmaking.v1.LatencyMeasurementServer.ProtocolR\bprotocol\"@\n" +
	"\bProtocol\x12\x18\n" +
	"\x14PROTOCOL_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03UDP\x10\x01\x12\a\n" +
	"\x03TCP\x10\x02\x12\b\n" +
	"\x04HTTP\x10\x03*\x82\x01\n" +
	"\x10DelegationAction\x12!\n" +
	"\x1dDELEGATION_ACTION_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ANY_PARTICIPATION\x10\x01\x12\x0e\n" +
	"\n" +
	"ACCEPTANCE\x10\x02\x12$\n" +
	" INCLUDE_ID_TOKEN_FOR_SAME_CLIENT\x10\x03::\n" +
	"\bimported\x12\x1c.google.protobuf.FileOptions\x18Ն\x03 \x01(\bR\bimportedB9Z7openpak/stardew-valley/proto/matchmaking/v1;matchmakingb\x06proto3"

var (
	file_proto_matchmaking_v1_resources_proto_rawDescOnce sync.Once
	file_proto_matchmaking_v1_resources_proto_rawDescData []byte
)

func file_proto_matchmaking_v1_resources_proto_rawDescGZIP() []byte {
	file_proto_matchmaking_v1_resources_proto_rawDescOnce.Do(func() {
		file_proto_matchmaking_v1_resources_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_matchmaking_v1_resources_proto_rawDesc), len(file_proto_matchmaking_v1_resources_proto_rawDesc)))
	})
	return file_proto_matchmaking_v1_resources_proto_rawDescData
}

var file_proto_matchmaking_v1_resources_proto_enumTypes = make([]protoimpl.EnumInfo, 8)
var file_proto_matchmaking_v1_resources_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_matchmaking_v1_resources_proto_goTypes = []any{
	(DelegationAction)(0),                  // 0: nn.npln.matchmaking.v1.DelegationAction
	(GameSessionCreationTicket_State)(0),   // 1: nn.npln.matchmaking.v1.GameSessionCreationTicket.State
	(UserSession_State)(0),                 // 2: nn.npln.matchmaking.v1.UserSession.State
	(MatchmakingTicket_State)(0),           // 3: nn.npln.matchmaking.v1.MatchmakingTicket.State
	(GameSession_State)(0),                 // 4: nn.npln.matchmaking.v1.GameSession.State
	(StunServer_Protocol)(0),               // 5: nn.npln.matchmaking.v1.StunServer.Protocol
	(TurnServer_Protocol)(0),               // 6: nn.npln.matchmaking.v1.TurnServer.Protocol
	(LatencyMeasurementServer_Protocol)(0), // 7: nn.npln.matchmaking.v1.LatencyMeasurementServer.Protocol
	(*GameSessionCreationTicket)(nil),      // 8: nn.npln.matchmaking.v1.GameSessionCreationTicket
	(*UserDelegationDetail)(nil),           // 9: nn.npln.matchmaking.v1.UserDelegationDetail
	(*UserSession)(nil),                    // 10: nn.npln.matchmaking.v1.UserSession
	(*GameSessionShortAlias)(nil),          // 11: nn.npln.matchmaking.v1.GameSessionShortAlias
	(*MatchmakingTicket)(nil),              // 12: nn.npln.matchmaking.v1.MatchmakingTicket
	(*Backfill)(nil),                       // 13: nn.npln.matchmaking.v1.Backfill
	(*GameSession)(nil),                    // 14: nn.npln.matchmaking.v1.GameSession
	(*MatchedUserSession)(nil),             // 15: nn.npln.matchmaking.v1.MatchedUserSession
	(*UserDefinition)(nil),                 // 16: nn.npln.matchmaking.v1.UserDefinition
	(*LatencyData)(nil),                    // 17: nn.npln.matchmaking.v1.LatencyData
	(*Acceptance)(nil),                     // 18: nn.npln.matchmaking.v1.Acceptance
	(*IceServerSet)(nil),                   // 19: nn.npln.matchmaking.v1.IceServerSet
	(*StunServer)(nil),                     // 20: nn.npln.matchmaking.v1.StunServer
	(*TurnServer)(nil),                     // 21: nn.npln.matchmaking.v1.TurnServer
	(*LatencyMeasurementServer)(nil),       // 22: nn.npln.matchmaking.v1.LatencyMeasurementServer
	nil,                                    // 23: nn.npln.matchmaking.v1.LatencyData.LatenciesEntry
	(*common.MapValue)(nil),                // 24: nn.npln.common.MapValue
	(*durationpb.Duration)(nil),            // 25: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil),          // 26: google.protobuf.Timestamp
	(*descriptorpb.FileOptions)(nil),       // 27: google.protobuf.FileOptions
}
var file_proto_matchmaking_v1_resources_proto_depIdxs = []int32{
	16, // 0: nn.npln.matchmaking.v1.GameSessionCreationTicket.user_definitions:type_name -> nn.npln.matchmaking.v1.UserDefinition
	1,  // 1: nn.npln.matchmaking.v1.GameSessionCreationTicket.state:type_name -> nn.npln.matchmaking.v1.GameSessionCreationTicket.State
	15, // 2: nn.npln.matchmaking.v1.GameSessionCreationTicket.matched_user_sessions:type_name -> nn.npln.matchmaking.v1.MatchedUserSession
	14, // 3: nn.npln.matchmaking.v1.GameSessionCreationTicket.game_session:type_name -> nn.npln.matchmaking.v1.GameSession
	24, // 4: nn.npln.matchmaking.v1.UserDelegationDetail.attributes:type_name -> nn.npln.common.MapValue
	0,  // 5: nn.npln.matchmaking.v1.UserDelegationDetail.delegation_actions:type_name -> nn.npln.matchmaking.v1.DelegationAction
	25, // 6: nn.npln.matchmaking.v1.UserDelegationDetail.ttl:type_name -> google.protobuf.Duration
	17, // 7: nn.npln.matchmaking.v1.UserSession.latency_data:type_name -> nn.npln.matchmaking.v1.LatencyData
	26, // 8: nn.npln.matchmaking.v1.UserSession.create_time:type_name -> google.protobuf.Timestamp
	2,  // 9: nn.npln.matchmaking.v1.UserSession.state:type_name -> nn.npln.matchmaking.v1.UserSession.State
	24, // 10: nn.npln.matchmaking.v1.UserSession.attributes:type_name -> nn.npln.common.MapValue
	26, // 11: nn.npln.matchmaking.v1.GameSessionShortAlias.expire_time:type_name -> google.protobuf.Timestamp
	13, // 12: nn.npln.matchmaking.v1.MatchmakingTicket.backfill:type_name -> nn.npln.matchmaking.v1.Backfill
	16, // 13: nn.npln.matchmaking.v1.MatchmakingTicket.user_definitions:type_name -> nn.npln.matchmaking.v1.UserDefinition
	3,  // 14: nn.npln.matchmaking.v1.MatchmakingTicket.state:type_name -> nn.npln.matchmaking.v1.MatchmakingTicket.State
	15, // 15: nn.npln.matchmaking.v1.MatchmakingTicket.matched_user_sessions:type_name -> nn.npln.matchmaking.v1.MatchedUserSession
	14, // 16: nn.npln.matchmaking.v1.MatchmakingTicket.game_session:type_name -> nn.npln.matchmaking.v1.GameSession
	4,  // 17: nn.npln.matchmaking.v1.GameSession.state:type_name -> nn.npln.matchmaking.v1.GameSession.State
	26, // 18: nn.npln.matchmaking.v1.GameSession.create_time:type_name -> google.protobuf.Timestamp
	24, // 19: nn.npln.matchmaking.v1.GameSession.properties:type_name -> nn.npln.common.MapValue
	10, // 20: nn.npln.matchmaking.v1.GameSession.user_sessions:type_name -> nn.npln.matchmaking.v1.UserSession
	16, // 21: nn.npln.matchmaking.v1.MatchedUserSession.user_definition:type_name -> nn.npln.matchmaking.v1.UserDefinition
	24, // 22: nn.npln.matchmaking.v1.UserDefinition.attributes:type_name -> nn.npln.common.MapValue
	17, // 23: nn.npln.matchmaking.v1.UserDefinition.latency_data:type_name -> nn.npln.matchmaking.v1.LatencyData
	23, // 24: nn.npln.matchmaking.v1.LatencyData.latencies:type_name -> nn.npln.matchmaking.v1.LatencyData.LatenciesEntry
	20, // 25: nn.npln.matchmaking.v1.IceServerSet.stun_server:type_name -> nn.npln.matchmaking.v1.StunServer
	21, // 26: nn.npln.matchmaking.v1.IceServerSet.turn_servers:type_name -> nn.npln.matchmaking.v1.TurnServer
	25, // 27: nn.npln.matchmaking.v1.IceServerSet.ttl:type_name -> google.protobuf.Duration
	26, // 28: nn.npln.matchmaking.v1.IceServerSet.update_time:type_name -> google.protobuf.Timestamp
	25, // 29: nn.npln.matchmaking.v1.IceServerSet.client_cache_duration:type_name -> google.protobuf.Duration
	5,  // 30: nn.npln.matchmaking.v1.StunServer.protocol:type_name -> nn.npln.matchmaking.v1.StunServer.Protocol
	6,  // 31: nn.npln.matchmaking.v1.TurnServer.protocol:type_name -> nn.npln.matchmaking.v1.TurnServer.Protocol
	7,  // 32: nn.npln.matchmaking.v1.LatencyMeasurementServer.protocol:type_name -> nn.npln.matchmaking.v1.LatencyMeasurementServer.Protocol
	25, // 33: nn.npln.matchmaking.v1.LatencyData.LatenciesEntry.value:type_name -> google.protobuf.Duration
	27, // 34: nn.npln.matchmaking.v1.imported:extendee -> google.protobuf.FileOptions
	35, // [35:35] is the sub-list for method output_type
	35, // [35:35] is the sub-list for method input_type
	35, // [35:35] is the sub-list for extension type_name
	34, // [34:35] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_proto_matchmaking_v1_resources_proto_init() }
func file_proto_matchmaking_v1_resources_proto_init() {
	if File_proto_matchmaking_v1_resources_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_matchmaking_v1_resources_proto_rawDesc), len(file_proto_matchmaking_v1_resources_proto_rawDesc)),
			NumEnums:      8,
			NumMessages:   16,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_proto_matchmaking_v1_resources_proto_goTypes,
		DependencyIndexes: file_proto_matchmaking_v1_resources_proto_depIdxs,
		EnumInfos:         file_proto_matchmaking_v1_resources_proto_enumTypes,
		MessageInfos:      file_proto_matchmaking_v1_resources_proto_msgTypes,
		ExtensionInfos:    file_proto_matchmaking_v1_resources_proto_extTypes,
	}.Build()
	File_proto_matchmaking_v1_resources_proto = out.File
	file_proto_matchmaking_v1_resources_proto_goTypes = nil
	file_proto_matchmaking_v1_resources_proto_depIdxs = nil
}
