// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: proto/friends/v1/friends.proto

package friends

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Friends_ActivateUser_FullMethodName         = "/nn.npln.friends.v1.Friends/ActivateUser"
	Friends_ListFriendUsers_FullMethodName      = "/nn.npln.friends.v1.Friends/ListFriendUsers"
	Friends_ListBlockingUsers_FullMethodName    = "/nn.npln.friends.v1.Friends/ListBlockingUsers"
	Friends_SubscribeFriendUsers_FullMethodName = "/nn.npln.friends.v1.Friends/SubscribeFriendUsers"
)

// FriendsClient is the client API for Friends service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FriendsClient interface {
	ActivateUser(ctx context.Context, in *ActivateUserRequest, opts ...grpc.CallOption) (*ActivateUserResponse, error)
	ListFriendUsers(ctx context.Context, in *ListFriendUsersRequest, opts ...grpc.CallOption) (*ListFriendUsersResponse, error)
	ListBlockingUsers(ctx context.Context, in *ListBlockingUsersRequest, opts ...grpc.CallOption) (*ListBlockingUsersResponse, error)
	SubscribeFriendUsers(ctx context.Context, in *SubscribeFriendUsersRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeFriendUsersResponse], error)
}

type friendsClient struct {
	cc grpc.ClientConnInterface
}

func NewFriendsClient(cc grpc.ClientConnInterface) FriendsClient {
	return &friendsClient{cc}
}

func (c *friendsClient) ActivateUser(ctx context.Context, in *ActivateUserRequest, opts ...grpc.CallOption) (*ActivateUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActivateUserResponse)
	err := c.cc.Invoke(ctx, Friends_ActivateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendsClient) ListFriendUsers(ctx context.Context, in *ListFriendUsersRequest, opts ...grpc.CallOption) (*ListFriendUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFriendUsersResponse)
	err := c.cc.Invoke(ctx, Friends_ListFriendUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendsClient) ListBlockingUsers(ctx context.Context, in *ListBlockingUsersRequest, opts ...grpc.CallOption) (*ListBlockingUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBlockingUsersResponse)
	err := c.cc.Invoke(ctx, Friends_ListBlockingUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendsClient) SubscribeFriendUsers(ctx context.Context, in *SubscribeFriendUsersRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeFriendUsersResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Friends_ServiceDesc.Streams[0], Friends_SubscribeFriendUsers_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeFriendUsersRequest, SubscribeFriendUsersResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Friends_SubscribeFriendUsersClient = grpc.ServerStreamingClient[SubscribeFriendUsersResponse]

// FriendsServer is the server API for Friends service.
// All implementations must embed UnimplementedFriendsServer
// for forward compatibility.
type FriendsServer interface {
	ActivateUser(context.Context, *ActivateUserRequest) (*ActivateUserResponse, error)
	ListFriendUsers(context.Context, *ListFriendUsersRequest) (*ListFriendUsersResponse, error)
	ListBlockingUsers(context.Context, *ListBlockingUsersRequest) (*ListBlockingUsersResponse, error)
	SubscribeFriendUsers(*SubscribeFriendUsersRequest, grpc.ServerStreamingServer[SubscribeFriendUsersResponse]) error
	mustEmbedUnimplementedFriendsServer()
}

// UnimplementedFriendsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFriendsServer struct{}

func (UnimplementedFriendsServer) ActivateUser(context.Context, *ActivateUserRequest) (*ActivateUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ActivateUser not implemented")
}
func (UnimplementedFriendsServer) ListFriendUsers(context.Context, *ListFriendUsersRequest) (*ListFriendUsersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFriendUsers not implemented")
}
func (UnimplementedFriendsServer) ListBlockingUsers(context.Context, *ListBlockingUsersRequest) (*ListBlockingUsersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBlockingUsers not implemented")
}
func (UnimplementedFriendsServer) SubscribeFriendUsers(*SubscribeFriendUsersRequest, grpc.ServerStreamingServer[SubscribeFriendUsersResponse]) error {
	return status.Error(codes.Unimplemented, "method SubscribeFriendUsers not implemented")
}
func (UnimplementedFriendsServer) mustEmbedUnimplementedFriendsServer() {}
func (UnimplementedFriendsServer) testEmbeddedByValue()                 {}

// UnsafeFriendsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FriendsServer will
// result in compilation errors.
type UnsafeFriendsServer interface {
	mustEmbedUnimplementedFriendsServer()
}

func RegisterFriendsServer(s grpc.ServiceRegistrar, srv FriendsServer) {
	// If the following call panics, it indicates UnimplementedFriendsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Friends_ServiceDesc, srv)
}

func _Friends_ActivateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendsServer).ActivateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Friends_ActivateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendsServer).ActivateUser(ctx, req.(*ActivateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Friends_ListFriendUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFriendUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendsServer).ListFriendUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Friends_ListFriendUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendsServer).ListFriendUsers(ctx, req.(*ListFriendUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Friends_ListBlockingUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBlockingUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendsServer).ListBlockingUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Friends_ListBlockingUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendsServer).ListBlockingUsers(ctx, req.(*ListBlockingUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Friends_SubscribeFriendUsers_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeFriendUsersRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FriendsServer).SubscribeFriendUsers(m, &grpc.GenericServerStream[SubscribeFriendUsersRequest, SubscribeFriendUsersResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Friends_SubscribeFriendUsersServer = grpc.ServerStreamingServer[SubscribeFriendUsersResponse]

// Friends_ServiceDesc is the grpc.ServiceDesc for Friends service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Friends_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nn.npln.friends.v1.Friends",
	HandlerType: (*FriendsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ActivateUser",
			Handler:    _Friends_ActivateUser_Handler,
		},
		{
			MethodName: "ListFriendUsers",
			Handler:    _Friends_ListFriendUsers_Handler,
		},
		{
			MethodName: "ListBlockingUsers",
			Handler:    _Friends_ListBlockingUsers_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeFriendUsers",
			Handler:       _Friends_SubscribeFriendUsers_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/friends/v1/friends.proto",
}
