// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: proto/friends/v1/friends.proto

package friends

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActivateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateUserRequest) Reset() {
	*x = ActivateUserRequest{}
	mi := &file_proto_friends_v1_friends_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateUserRequest) ProtoMessage() {}

func (x *ActivateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_friends_v1_friends_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateUserRequest.ProtoReflect.Descriptor instead.
func (*ActivateUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_friends_v1_friends_proto_rawDescGZIP(), []int{0}
}

func (x *ActivateUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ActivateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateUserResponse) Reset() {
	*x = ActivateUserResponse{}
	mi := &file_proto_friends_v1_friends_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateUserResponse) ProtoMessage() {}

func (x *ActivateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_friends_v1_friends_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateUserResponse.ProtoReflect.Descriptor instead.
func (*ActivateUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_friends_v1_friends_proto_rawDescGZIP(), []int{1}
}

type ListFriendUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parent        string                 `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFriendUsersRequest) Reset() {
	*x = ListFriendUsersRequest{}
	mi := &file_proto_friends_v1_friends_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFriendUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFriendUsersRequest) ProtoMessage() {}

func (x *ListFriendUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_friends_v1_friends_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFriendUsersRequest.ProtoReflect.Descriptor instead.
func (*ListFriendUsersRequest) Descriptor() ([]byte, []int) {
	return file_proto_friends_v1_friends_proto_rawDescGZIP(), []int{2}
}

func (x *ListFriendUsersRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ListFriendUsersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListFriendUsersRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListFriendUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FriendUsers   []*FriendUser          `protobuf:"bytes,1,rep,name=friend_users,json=friendUsers,proto3" json:"friend_users,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFriendUsersResponse) Reset() {
	*x = ListFriendUsersResponse{}
	mi := &file_proto_friends_v1_friends_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFriendUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFriendUsersResponse) ProtoMessage() {}

func (x *ListFriendUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_friends_v1_friends_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFriendUsersResponse.ProtoReflect.Descriptor instead.
func (*ListFriendUsersResponse) Descriptor() ([]byte, []int) {
	return file_proto_friends_v1_friends_proto_rawDescGZIP(), []int{3}
}

func (x *ListFriendUsersResponse) GetFriendUsers() []*FriendUser {
	if x != nil {
		return x.FriendUsers
	}
	return nil
}

func (x *ListFriendUsersResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type ListBlockingUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parent        string                 `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBlockingUsersRequest) Reset() {
	*x = ListBlockingUsersRequest{}
	mi := &file_proto_friends_v1_friends_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBlockingUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlockingUsersRequest) ProtoMessage() {}

func (x *ListBlockingUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_friends_v1_friends_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlockingUsersRequest.ProtoReflect.Descriptor instead.
func (*ListBlockingUsersRequest) Descriptor() ([]byte, []int) {
	return file_proto_friends_v1_friends_proto_rawDescGZIP(), []int{4}
}

func (x *ListBlockingUsersRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ListBlockingUsersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListBlockingUsersRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListBlockingUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockingUsers []*BlockingUser        `protobuf:"bytes,1,rep,name=blocking_users,json=blockingUsers,proto3" json:"blocking_users,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBlockingUsersResponse) Reset() {
	*x = ListBlockingUsersResponse{}
	mi := &file_proto_friends_v1_friends_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBlockingUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlockingUsersResponse) ProtoMessage() {}

func (x *ListBlockingUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_friends_v1_friends_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlockingUsersResponse.ProtoReflect.Descriptor instead.
func (*ListBlockingUsersResponse) Descriptor() ([]byte, []int) {
	return file_proto_friends_v1_friends_proto_rawDescGZIP(), []int{5}
}

func (x *ListBlockingUsersResponse) GetBlockingUsers() []*BlockingUser {
	if x != nil {
		return x.BlockingUsers
	}
	return nil
}

func (x *ListBlockingUsersResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type SubscribeFriendUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeFriendUsersRequest) Reset() {
	*x = SubscribeFriendUsersRequest{}
	mi := &file_proto_friends_v1_friends_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeFriendUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeFriendUsersRequest) ProtoMessage() {}

func (x *SubscribeFriendUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_friends_v1_friends_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeFriendUsersRequest.ProtoReflect.Descriptor instead.
func (*SubscribeFriendUsersRequest) Descriptor() ([]byte, []int) {
	return file_proto_friends_v1_friends_proto_rawDescGZIP(), []int{6}
}

func (x *SubscribeFriendUsersRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

type SubscribeFriendUsersResponse struct {
	state             protoimpl.MessageState                          `protogen:"open.v1"`
	FriendAccounts    []*SubscribeFriendUsersResponse_FriendAccount   `protobuf:"bytes,1,rep,name=friend_accounts,json=friendAccounts,proto3" json:"friend_accounts,omitempty"`
	BlockingAccounts  []*SubscribeFriendUsersResponse_BlockingAccount `protobuf:"bytes,2,rep,name=blocking_accounts,json=blockingAccounts,proto3" json:"blocking_accounts,omitempty"`
	KeepAliveInterval *durationpb.Duration                            `protobuf:"bytes,3,opt,name=keep_alive_interval,json=keepAliveInterval,proto3" json:"keep_alive_interval,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SubscribeFriendUsersResponse) Reset() {
	*x = SubscribeFriendUsersResponse{}
	mi := &file_proto_friends_v1_friends_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeFriendUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeFriendUsersResponse) ProtoMessage() {}

func (x *SubscribeFriendUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_friends_v1_friends_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeFriendUsersResponse.ProtoReflect.Descriptor instead.
func (*SubscribeFriendUsersResponse) Descriptor() ([]byte, []int) {
	return file_proto_friends_v1_friends_proto_rawDescGZIP(), []int{7}
}

func (x *SubscribeFriendUsersResponse) GetFriendAccounts() []*SubscribeFriendUsersResponse_FriendAccount {
	if x != nil {
		return x.FriendAccounts
	}
	return nil
}

func (x *SubscribeFriendUsersResponse) GetBlockingAccounts() []*SubscribeFriendUsersResponse_BlockingAccount {
	if x != nil {
		return x.BlockingAccounts
	}
	return nil
}

func (x *SubscribeFriendUsersResponse) GetKeepAliveInterval() *durationpb.Duration {
	if x != nil {
		return x.KeepAliveInterval
	}
	return nil
}

type SubscribeFriendUsersResponse_FriendAccount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NsaId         string                 `protobuf:"bytes,1,opt,name=nsa_id,json=nsaId,proto3" json:"nsa_id,omitempty"`
	Users         []*FriendUser          `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeFriendUsersResponse_FriendAccount) Reset() {
	*x = SubscribeFriendUsersResponse_FriendAccount{}
	mi := &file_proto_friends_v1_friends_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeFriendUsersResponse_FriendAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeFriendUsersResponse_FriendAccount) ProtoMessage() {}

func (x *SubscribeFriendUsersResponse_FriendAccount) ProtoReflect() protoreflect.Message {
	mi := &file_proto_friends_v1_friends_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeFriendUsersResponse_FriendAccount.ProtoReflect.Descriptor instead.
func (*SubscribeFriendUsersResponse_FriendAccount) Descriptor() ([]byte, []int) {
	return file_proto_friends_v1_friends_proto_rawDescGZIP(), []int{7, 0}
}

func (x *SubscribeFriendUsersResponse_FriendAccount) GetNsaId() string {
	if x != nil {
		return x.NsaId
	}
	return ""
}

func (x *SubscribeFriendUsersResponse_FriendAccount) GetUsers() []*FriendUser {
	if x != nil {
		return x.Users
	}
	return nil
}

type SubscribeFriendUsersResponse_BlockingAccount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NsaId         string                 `protobuf:"bytes,1,opt,name=nsa_id,json=nsaId,proto3" json:"nsa_id,omitempty"`
	Users         []*BlockingUser        `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeFriendUsersResponse_BlockingAccount) Reset() {
	*x = SubscribeFriendUsersResponse_BlockingAccount{}
	mi := &file_proto_friends_v1_friends_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeFriendUsersResponse_BlockingAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeFriendUsersResponse_BlockingAccount) ProtoMessage() {}

func (x *SubscribeFriendUsersResponse_BlockingAccount) ProtoReflect() protoreflect.Message {
	mi := &file_proto_friends_v1_friends_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeFriendUsersResponse_BlockingAccount.ProtoReflect.Descriptor instead.
func (*SubscribeFriendUsersResponse_BlockingAccount) Descriptor() ([]byte, []int) {
	return file_proto_friends_v1_friends_proto_rawDescGZIP(), []int{7, 1}
}

func (x *SubscribeFriendUsersResponse_BlockingAccount) GetNsaId() string {
	if x != nil {
		return x.NsaId
	}
	return ""
}

func (x *SubscribeFriendUsersResponse_BlockingAccount) GetUsers() []*BlockingUser {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_proto_friends_v1_friends_proto protoreflect.FileDescriptor

const file_proto_friends_v1_friends_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/friends/v1/friends.proto\x12\x12nn.npln.friends.v1\x1a proto/friends/v1/resources.proto\x1a\x1egoogle/protobuf/duration.proto\")\n" +
	"\x13ActivateUserRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x16\n" +
	"\x14ActivateUserResponse\"l\n" +
	"\x16ListFriendUsersRequest\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\tR\x06parent\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"\x84\x01\n" +
	"\x17ListFriendUsersResponse\x12A\n" +
	"\ffriend_users\x18\x01 \x03(\v2\x1e.nn.npln.friends.v1.FriendUserR\vfriendUsers\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"n\n" +
	"\x18ListBlockingUsersRequest\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\tR\x06parent\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"\x8c\x01\n" +
	"\x19ListBlockingUsersResponse\x12G\n" +
	"\x0eblocking_users\x18\x01 \x03(\v2 .nn.npln.friends.v1.BlockingUserR\rblockingUsers\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"1\n" +
	"\x1bSubscribeFriendUsersRequest\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\"\x81\x04\n" +
	"\x1cSubscribeFriendUsersResponse\x12g\n" +
	"\x0ffriend_accounts\x18\x01 \x03(\v2>.nn.npln.friends.v1.SubscribeFriendUsersResponse.FriendAccountR\x0efriendAccounts\x12m\n" +
	"\x11blocking_accounts\x18\x02 \x03(\v2@.nn.npln.friends.v1.SubscribeFriendUsersResponse.BlockingAccountR\x10blockingAccounts\x12I\n" +
	"\x13keep_alive_interval\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x11keepAliveInterval\x1a\\\n" +
	"\rFriendAccount\x12\x15\n" +
	"\x06nsa_id\x18\x01 \x01(\tR\x05nsaId\x124\n" +
	"\x05users\x18\x02 \x03(\v2\x1e.nn.npln.friends.v1.FriendUserR\x05users\x1a`\n" +
	"\x0fBlockingAccount\x12\x15\n" +
	"\x06nsa_id\x18\x01 \x01(\tR\x05nsaId\x126\n" +
	"\x05users\x18\x02 \x03(\v2 .nn.npln.friends.v1.BlockingUserR\x05users2\xc7\x03\n" +
	"\aFriends\x12a\n" +
	"\fActivateUser\x12'.nn.npln.friends.v1.ActivateUserRequest\x1a(.nn.npln.friends.v1.ActivateUserResponse\x12j\n" +
	"\x0fListFriendUsers\x12*.nn.npln.friends.v1.ListFriendUsersRequest\x1a+.nn.npln.friends.v1.ListFriendUsersResponse\x12p\n" +
	"\x11ListBlockingUsers\x12,.nn.npln.friends.v1.ListBlockingUsersRequest\x1a-.nn.npln.friends.v1.ListBlockingUsersResponse\x12{\n" +
	"\x14SubscribeFriendUsers\x12/.nn.npln.friends.v1.SubscribeFriendUsersRequest\x1a0.nn.npln.friends.v1.SubscribeFriendUsersResponse0\x01B1Z/openpak/stardew-valley/proto/friends/v1;friendsb\x06proto3"

var (
	file_proto_friends_v1_friends_proto_rawDescOnce sync.Once
	file_proto_friends_v1_friends_proto_rawDescData []byte
)

func file_proto_friends_v1_friends_proto_rawDescGZIP() []byte {
	file_proto_friends_v1_friends_proto_rawDescOnce.Do(func() {
		file_proto_friends_v1_friends_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_friends_v1_friends_proto_rawDesc), len(file_proto_friends_v1_friends_proto_rawDesc)))
	})
	return file_proto_friends_v1_friends_proto_rawDescData
}

var file_proto_friends_v1_friends_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_friends_v1_friends_proto_goTypes = []any{
	(*ActivateUserRequest)(nil),                          // 0: nn.npln.friends.v1.ActivateUserRequest
	(*ActivateUserResponse)(nil),                         // 1: nn.npln.friends.v1.ActivateUserResponse
	(*ListFriendUsersRequest)(nil),                       // 2: nn.npln.friends.v1.ListFriendUsersRequest
	(*ListFriendUsersResponse)(nil),                      // 3: nn.npln.friends.v1.ListFriendUsersResponse
	(*ListBlockingUsersRequest)(nil),                     // 4: nn.npln.friends.v1.ListBlockingUsersRequest
	(*ListBlockingUsersResponse)(nil),                    // 5: nn.npln.friends.v1.ListBlockingUsersResponse
	(*SubscribeFriendUsersRequest)(nil),                  // 6: nn.npln.friends.v1.SubscribeFriendUsersRequest
	(*SubscribeFriendUsersResponse)(nil),                 // 7: nn.npln.friends.v1.SubscribeFriendUsersResponse
	(*SubscribeFriendUsersResponse_FriendAccount)(nil),   // 8: nn.npln.friends.v1.SubscribeFriendUsersResponse.FriendAccount
	(*SubscribeFriendUsersResponse_BlockingAccount)(nil), // 9: nn.npln.friends.v1.SubscribeFriendUsersResponse.BlockingAccount
	(*FriendUser)(nil),                                   // 10: nn.npln.friends.v1.FriendUser
	(*BlockingUser)(nil),                                 // 11: nn.npln.friends.v1.BlockingUser
	(*durationpb.Duration)(nil),                          // 12: google.protobuf.Duration
}
var file_proto_friends_v1_friends_proto_depIdxs = []int32{
	10, // 0: nn.npln.friends.v1.ListFriendUsersResponse.friend_users:type_name -> nn.npln.friends.v1.FriendUser
	11, // 1: nn.npln.friends.v1.ListBlockingUsersResponse.blocking_users:type_name -> nn.npln.friends.v1.BlockingUser
	8,  // 2: nn.npln.friends.v1.SubscribeFriendUsersResponse.friend_accounts:type_name -> nn.npln.friends.v1.SubscribeFriendUsersResponse.FriendAccount
	9,  // 3: nn.npln.friends.v1.SubscribeFriendUsersResponse.blocking_accounts:type_name -> nn.npln.friends.v1.SubscribeFriendUsersResponse.BlockingAccount
	12, // 4: nn.npln.friends.v1.SubscribeFriendUsersResponse.keep_alive_interval:type_name -> google.protobuf.Duration
	10, // 5: nn.npln.friends.v1.SubscribeFriendUsersResponse.FriendAccount.users:type_name -> nn.npln.friends.v1.FriendUser
	11, // 6: nn.npln.friends.v1.SubscribeFriendUsersResponse.BlockingAccount.users:type_name -> nn.npln.friends.v1.BlockingUser
	0,  // 7: nn.npln.friends.v1.Friends.ActivateUser:input_type -> nn.npln.friends.v1.ActivateUserRequest
	2,  // 8: nn.npln.friends.v1.Friends.ListFriendUsers:input_type -> nn.npln.friends.v1.ListFriendUsersRequest
	4,  // 9: nn.npln.friends.v1.Friends.ListBlockingUsers:input_type -> nn.npln.friends.v1.ListBlockingUsersRequest
	6,  // 10: nn.npln.friends.v1.Friends.SubscribeFriendUsers:input_type -> nn.npln.friends.v1.SubscribeFriendUsersRequest
	1,  // 11: nn.npln.friends.v1.Friends.ActivateUser:output_type -> nn.npln.friends.v1.ActivateUserResponse
	3,  // 12: nn.npln.friends.v1.Friends.ListFriendUsers:output_type -> nn.npln.friends.v1.ListFriendUsersResponse
	5,  // 13: nn.npln.friends.v1.Friends.ListBlockingUsers:output_type -> nn.npln.friends.v1.ListBlockingUsersResponse
	7,  // 14: nn.npln.friends.v1.Friends.SubscribeFriendUsers:output_type -> nn.npln.friends.v1.SubscribeFriendUsersResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_friends_v1_friends_proto_init() }
func file_proto_friends_v1_friends_proto_init() {
	if File_proto_friends_v1_friends_proto != nil {
		return
	}
	file_proto_friends_v1_resources_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_friends_v1_friends_proto_rawDesc), len(file_proto_friends_v1_friends_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_friends_v1_friends_proto_goTypes,
		DependencyIndexes: file_proto_friends_v1_friends_proto_depIdxs,
		MessageInfos:      file_proto_friends_v1_friends_proto_msgTypes,
	}.Build()
	File_proto_friends_v1_friends_proto = out.File
	file_proto_friends_v1_friends_proto_goTypes = nil
	file_proto_friends_v1_friends_proto_depIdxs = nil
}
