// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: proto/auth/v1/auth.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUserRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Parent          string                 `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	User            *User                  `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	ExternalIdToken *ExternalIdToken       `protobuf:"bytes,3,opt,name=external_id_token,json=externalIdToken,proto3" json:"external_id_token,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_proto_auth_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *CreateUserRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *CreateUserRequest) GetExternalIdToken() *ExternalIdToken {
	if x != nil {
		return x.ExternalIdToken
	}
	return nil
}

type IssueTokenRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	User            string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	ExternalIdToken *ExternalIdToken       `protobuf:"bytes,2,opt,name=external_id_token,json=externalIdToken,proto3" json:"external_id_token,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IssueTokenRequest) Reset() {
	*x = IssueTokenRequest{}
	mi := &file_proto_auth_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueTokenRequest) ProtoMessage() {}

func (x *IssueTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueTokenRequest.ProtoReflect.Descriptor instead.
func (*IssueTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *IssueTokenRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *IssueTokenRequest) GetExternalIdToken() *ExternalIdToken {
	if x != nil {
		return x.ExternalIdToken
	}
	return nil
}

type IssueTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         *Token                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueTokenResponse) Reset() {
	*x = IssueTokenResponse{}
	mi := &file_proto_auth_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueTokenResponse) ProtoMessage() {}

func (x *IssueTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueTokenResponse.ProtoReflect.Descriptor instead.
func (*IssueTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *IssueTokenResponse) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_proto_auth_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *RefreshTokenRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         *Token                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_proto_auth_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_auth_proto_rawDescGZIP(), []int{4}
}

func (x *RefreshTokenResponse) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

type IssuePrearrangedUserTokenRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Tenant          string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	UserIndex       int32                  `protobuf:"varint,2,opt,name=user_index,json=userIndex,proto3" json:"user_index,omitempty"`
	ExternalIdToken *ExternalIdToken       `protobuf:"bytes,3,opt,name=external_id_token,json=externalIdToken,proto3" json:"external_id_token,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IssuePrearrangedUserTokenRequest) Reset() {
	*x = IssuePrearrangedUserTokenRequest{}
	mi := &file_proto_auth_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssuePrearrangedUserTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssuePrearrangedUserTokenRequest) ProtoMessage() {}

func (x *IssuePrearrangedUserTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssuePrearrangedUserTokenRequest.ProtoReflect.Descriptor instead.
func (*IssuePrearrangedUserTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_auth_proto_rawDescGZIP(), []int{5}
}

func (x *IssuePrearrangedUserTokenRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *IssuePrearrangedUserTokenRequest) GetUserIndex() int32 {
	if x != nil {
		return x.UserIndex
	}
	return 0
}

func (x *IssuePrearrangedUserTokenRequest) GetExternalIdToken() *ExternalIdToken {
	if x != nil {
		return x.ExternalIdToken
	}
	return nil
}

type IssuePrearrangedUserTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Token         *Token                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssuePrearrangedUserTokenResponse) Reset() {
	*x = IssuePrearrangedUserTokenResponse{}
	mi := &file_proto_auth_v1_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssuePrearrangedUserTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssuePrearrangedUserTokenResponse) ProtoMessage() {}

func (x *IssuePrearrangedUserTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssuePrearrangedUserTokenResponse.ProtoReflect.Descriptor instead.
func (*IssuePrearrangedUserTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_auth_proto_rawDescGZIP(), []int{6}
}

func (x *IssuePrearrangedUserTokenResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *IssuePrearrangedUserTokenResponse) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

type IssueAnonymousUserTokenRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Tenant          string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	ExternalIdToken *ExternalIdToken       `protobuf:"bytes,2,opt,name=external_id_token,json=externalIdToken,proto3" json:"external_id_token,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IssueAnonymousUserTokenRequest) Reset() {
	*x = IssueAnonymousUserTokenRequest{}
	mi := &file_proto_auth_v1_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueAnonymousUserTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueAnonymousUserTokenRequest) ProtoMessage() {}

func (x *IssueAnonymousUserTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueAnonymousUserTokenRequest.ProtoReflect.Descriptor instead.
func (*IssueAnonymousUserTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_auth_proto_rawDescGZIP(), []int{7}
}

func (x *IssueAnonymousUserTokenRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *IssueAnonymousUserTokenRequest) GetExternalIdToken() *ExternalIdToken {
	if x != nil {
		return x.ExternalIdToken
	}
	return nil
}

type IssueAnonymousUserTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         *Token                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueAnonymousUserTokenResponse) Reset() {
	*x = IssueAnonymousUserTokenResponse{}
	mi := &file_proto_auth_v1_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueAnonymousUserTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueAnonymousUserTokenResponse) ProtoMessage() {}

func (x *IssueAnonymousUserTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueAnonymousUserTokenResponse.ProtoReflect.Descriptor instead.
func (*IssueAnonymousUserTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_auth_proto_rawDescGZIP(), []int{8}
}

func (x *IssueAnonymousUserTokenResponse) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

type RefreshAnonymousTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshAnonymousTokenRequest) Reset() {
	*x = RefreshAnonymousTokenRequest{}
	mi := &file_proto_auth_v1_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshAnonymousTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshAnonymousTokenRequest) ProtoMessage() {}

func (x *RefreshAnonymousTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshAnonymousTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshAnonymousTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_auth_proto_rawDescGZIP(), []int{9}
}

func (x *RefreshAnonymousTokenRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *RefreshAnonymousTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshAnonymousTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         *Token                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshAnonymousTokenResponse) Reset() {
	*x = RefreshAnonymousTokenResponse{}
	mi := &file_proto_auth_v1_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshAnonymousTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshAnonymousTokenResponse) ProtoMessage() {}

func (x *RefreshAnonymousTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshAnonymousTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshAnonymousTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_auth_proto_rawDescGZIP(), []int{10}
}

func (x *RefreshAnonymousTokenResponse) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parent        string                 `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_proto_auth_v1_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_auth_proto_rawDescGZIP(), []int{11}
}

func (x *ListUsersRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_proto_auth_v1_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_auth_proto_rawDescGZIP(), []int{12}
}

func (x *ListUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_proto_auth_v1_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_auth_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Token struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	Ttl           *durationpb.Duration   `protobuf:"bytes,4,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Token) Reset() {
	*x = Token{}
	mi := &file_proto_auth_v1_auth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_auth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_auth_proto_rawDescGZIP(), []int{14}
}

func (x *Token) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *Token) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *Token) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *Token) GetTtl() *durationpb.Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

type ExternalIdToken struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Token:
	//
	//	*ExternalIdToken_NsaIdToken
	//	*ExternalIdToken_DummyExtIdToken
	Token         isExternalIdToken_Token `protobuf_oneof:"token"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExternalIdToken) Reset() {
	*x = ExternalIdToken{}
	mi := &file_proto_auth_v1_auth_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalIdToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalIdToken) ProtoMessage() {}

func (x *ExternalIdToken) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_auth_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalIdToken.ProtoReflect.Descriptor instead.
func (*ExternalIdToken) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_auth_proto_rawDescGZIP(), []int{15}
}

func (x *ExternalIdToken) GetToken() isExternalIdToken_Token {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *ExternalIdToken) GetNsaIdToken() string {
	if x != nil {
		if x, ok := x.Token.(*ExternalIdToken_NsaIdToken); ok {
			return x.NsaIdToken
		}
	}
	return ""
}

func (x *ExternalIdToken) GetDummyExtIdToken() string {
	if x != nil {
		if x, ok := x.Token.(*ExternalIdToken_DummyExtIdToken); ok {
			return x.DummyExtIdToken
		}
	}
	return ""
}

type isExternalIdToken_Token interface {
	isExternalIdToken_Token()
}

type ExternalIdToken_NsaIdToken struct {
	NsaIdToken string `protobuf:"bytes,1,opt,name=nsa_id_token,json=nsaIdToken,proto3,oneof"`
}

type ExternalIdToken_DummyExtIdToken struct {
	DummyExtIdToken string `protobuf:"bytes,2,opt,name=dummy_ext_id_token,json=dummyExtIdToken,proto3,oneof"`
}

func (*ExternalIdToken_NsaIdToken) isExternalIdToken_Token() {}

func (*ExternalIdToken_DummyExtIdToken) isExternalIdToken_Token() {}

var File_proto_auth_v1_auth_proto protoreflect.FileDescriptor

const file_proto_auth_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x18proto/auth/v1/auth.proto\x12\x0fnn.npln.auth.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1dproto/auth/v1/resources.proto\"\xa4\x01\n" +
	"\x11CreateUserRequest\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\tR\x06parent\x12)\n" +
	"\x04user\x18\x02 \x01(\v2\x15.nn.npln.auth.v1.UserR\x04user\x12L\n" +
	"\x11external_id_token\x18\x03 \x01(\v2 .nn.npln.auth.v1.ExternalIdTokenR\x0fexternalIdToken\"u\n" +
	"\x11IssueTokenRequest\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12L\n" +
	"\x11external_id_token\x18\x02 \x01(\v2 .nn.npln.auth.v1.ExternalIdTokenR\x0fexternalIdToken\"B\n" +
	"\x12IssueTokenResponse\x12,\n" +
	"\x05token\x18\x01 \x01(\v2\x16.nn.npln.auth.v1.TokenR\x05token\"N\n" +
	"\x13RefreshTokenRequest\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\"D\n" +
	"\x14RefreshTokenResponse\x12,\n" +
	"\x05token\x18\x01 \x01(\v2\x16.nn.npln.auth.v1.TokenR\x05token\"\xa7\x01\n" +
	" IssuePrearrangedUserTokenRequest\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x1d\n" +
	"\n" +
	"user_index\x18\x02 \x01(\x05R\tuserIndex\x12L\n" +
	"\x11external_id_token\x18\x03 \x01(\v2 .nn.npln.auth.v1.ExternalIdTokenR\x0fexternalIdToken\"|\n" +
	"!IssuePrearrangedUserTokenResponse\x12)\n" +
	"\x04user\x18\x01 \x01(\v2\x15.nn.npln.auth.v1.UserR\x04user\x12,\n" +
	"\x05token\x18\x02 \x01(\v2\x16.nn.npln.auth.v1.TokenR\x05token\"\x86\x01\n" +
	"\x1eIssueAnonymousUserTokenRequest\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12L\n" +
	"\x11external_id_token\x18\x02 \x01(\v2 .nn.npln.auth.v1.ExternalIdTokenR\x0fexternalIdToken\"O\n" +
	"\x1fIssueAnonymousUserTokenResponse\x12,\n" +
	"\x05token\x18\x01 \x01(\v2\x16.nn.npln.auth.v1.TokenR\x05token\"[\n" +
	"\x1cRefreshAnonymousTokenRequest\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\"M\n" +
	"\x1dRefreshAnonymousTokenResponse\x12,\n" +
	"\x05token\x18\x01 \x01(\v2\x16.nn.npln.auth.v1.TokenR\x05token\"*\n" +
	"\x10ListUsersRequest\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\tR\x06parent\"@\n" +
	"\x11ListUsersResponse\x12+\n" +
	"\x05users\x18\x01 \x03(\v2\x15.nn.npln.auth.v1.UserR\x05users\"'\n" +
	"\x11DeleteUserRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x90\x01\n" +
	"\x05Token\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x12+\n" +
	"\x03ttl\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\x03ttl\"m\n" +
	"\x0fExternalIdToken\x12\"\n" +
	"\fnsa_id_token\x18\x01 \x01(\tH\x00R\n" +
	"nsaIdToken\x12-\n" +
	"\x12dummy_ext_id_token\x18\x02 \x01(\tH\x00R\x0fdummyExtIdTokenB\a\n" +
	"\x05token2\xe1\x06\n" +
	"\x04Auth\x12G\n" +
	"\n" +
	"CreateUser\x12\".nn.npln.auth.v1.CreateUserRequest\x1a\x15.nn.npln.auth.v1.User\x12U\n" +
	"\n" +
	"IssueToken\x12\".nn.npln.auth.v1.IssueTokenRequest\x1a#.nn.npln.auth.v1.IssueTokenResponse\x12[\n" +
	"\fRefreshToken\x12$.nn.npln.auth.v1.RefreshTokenRequest\x1a%.nn.npln.auth.v1.RefreshTokenResponse\x12\x82\x01\n" +
	"\x19IssuePrearrangedUserToken\x121.nn.npln.auth.v1.IssuePrearrangedUserTokenRequest\x1a2.nn.npln.auth.v1.IssuePrearrangedUserTokenResponse\x12|\n" +
	"\x17IssueAnonymousUserToken\x12/.nn.npln.auth.v1.IssueAnonymousUserTokenRequest\x1a0.nn.npln.auth.v1.IssueAnonymousUserTokenResponse\x12z\n" +
	"\x19RefreshAnonymousUserToken\x12-.nn.npln.auth.v1.RefreshAnonymousTokenRequest\x1a..nn.npln.auth.v1.RefreshAnonymousTokenResponse\x12?\n" +
	"\rValidateToken\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12R\n" +
	"\tListUsers\x12!.nn.npln.auth.v1.ListUsersRequest\x1a\".nn.npln.auth.v1.ListUsersResponse\x12H\n" +
	"\n" +
	"DeleteUser\x12\".nn.npln.auth.v1.DeleteUserRequest\x1a\x16.google.protobuf.EmptyB,Z*github.com/openpak/npln/proto/auth/v1;authb\x06proto3"

var (
	file_proto_auth_v1_auth_proto_rawDescOnce sync.Once
	file_proto_auth_v1_auth_proto_rawDescData []byte
)

func file_proto_auth_v1_auth_proto_rawDescGZIP() []byte {
	file_proto_auth_v1_auth_proto_rawDescOnce.Do(func() {
		file_proto_auth_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_auth_v1_auth_proto_rawDesc), len(file_proto_auth_v1_auth_proto_rawDesc)))
	})
	return file_proto_auth_v1_auth_proto_rawDescData
}

var file_proto_auth_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_auth_v1_auth_proto_goTypes = []any{
	(*CreateUserRequest)(nil),                 // 0: nn.npln.auth.v1.CreateUserRequest
	(*IssueTokenRequest)(nil),                 // 1: nn.npln.auth.v1.IssueTokenRequest
	(*IssueTokenResponse)(nil),                // 2: nn.npln.auth.v1.IssueTokenResponse
	(*RefreshTokenRequest)(nil),               // 3: nn.npln.auth.v1.RefreshTokenRequest
	(*RefreshTokenResponse)(nil),              // 4: nn.npln.auth.v1.RefreshTokenResponse
	(*IssuePrearrangedUserTokenRequest)(nil),  // 5: nn.npln.auth.v1.IssuePrearrangedUserTokenRequest
	(*IssuePrearrangedUserTokenResponse)(nil), // 6: nn.npln.auth.v1.IssuePrearrangedUserTokenResponse
	(*IssueAnonymousUserTokenRequest)(nil),    // 7: nn.npln.auth.v1.IssueAnonymousUserTokenRequest
	(*IssueAnonymousUserTokenResponse)(nil),   // 8: nn.npln.auth.v1.IssueAnonymousUserTokenResponse
	(*RefreshAnonymousTokenRequest)(nil),      // 9: nn.npln.auth.v1.RefreshAnonymousTokenRequest
	(*RefreshAnonymousTokenResponse)(nil),     // 10: nn.npln.auth.v1.RefreshAnonymousTokenResponse
	(*ListUsersRequest)(nil),                  // 11: nn.npln.auth.v1.ListUsersRequest
	(*ListUsersResponse)(nil),                 // 12: nn.npln.auth.v1.ListUsersResponse
	(*DeleteUserRequest)(nil),                 // 13: nn.npln.auth.v1.DeleteUserRequest
	(*Token)(nil),                             // 14: nn.npln.auth.v1.Token
	(*ExternalIdToken)(nil),                   // 15: nn.npln.auth.v1.ExternalIdToken
	(*User)(nil),                              // 16: nn.npln.auth.v1.User
	(*durationpb.Duration)(nil),               // 17: google.protobuf.Duration
	(*emptypb.Empty)(nil),                     // 18: google.protobuf.Empty
}
var file_proto_auth_v1_auth_proto_depIdxs = []int32{
	16, // 0: nn.npln.auth.v1.CreateUserRequest.user:type_name -> nn.npln.auth.v1.User
	15, // 1: nn.npln.auth.v1.CreateUserRequest.external_id_token:type_name -> nn.npln.auth.v1.ExternalIdToken
	15, // 2: nn.npln.auth.v1.IssueTokenRequest.external_id_token:type_name -> nn.npln.auth.v1.ExternalIdToken
	14, // 3: nn.npln.auth.v1.IssueTokenResponse.token:type_name -> nn.npln.auth.v1.Token
	14, // 4: nn.npln.auth.v1.RefreshTokenResponse.token:type_name -> nn.npln.auth.v1.Token
	15, // 5: nn.npln.auth.v1.IssuePrearrangedUserTokenRequest.external_id_token:type_name -> nn.npln.auth.v1.ExternalIdToken
	16, // 6: nn.npln.auth.v1.IssuePrearrangedUserTokenResponse.user:type_name -> nn.npln.auth.v1.User
	14, // 7: nn.npln.auth.v1.IssuePrearrangedUserTokenResponse.token:type_name -> nn.npln.auth.v1.Token
	15, // 8: nn.npln.auth.v1.IssueAnonymousUserTokenRequest.external_id_token:type_name -> nn.npln.auth.v1.ExternalIdToken
	14, // 9: nn.npln.auth.v1.IssueAnonymousUserTokenResponse.token:type_name -> nn.npln.auth.v1.Token
	14, // 10: nn.npln.auth.v1.RefreshAnonymousTokenResponse.token:type_name -> nn.npln.auth.v1.Token
	16, // 11: nn.npln.auth.v1.ListUsersResponse.users:type_name -> nn.npln.auth.v1.User
	17, // 12: nn.npln.auth.v1.Token.ttl:type_name -> google.protobuf.Duration
	0,  // 13: nn.npln.auth.v1.Auth.CreateUser:input_type -> nn.npln.auth.v1.CreateUserRequest
	1,  // 14: nn.npln.auth.v1.Auth.IssueToken:input_type -> nn.npln.auth.v1.IssueTokenRequest
	3,  // 15: nn.npln.auth.v1.Auth.RefreshToken:input_type -> nn.npln.auth.v1.RefreshTokenRequest
	5,  // 16: nn.npln.auth.v1.Auth.IssuePrearrangedUserToken:input_type -> nn.npln.auth.v1.IssuePrearrangedUserTokenRequest
	7,  // 17: nn.npln.auth.v1.Auth.IssueAnonymousUserToken:input_type -> nn.npln.auth.v1.IssueAnonymousUserTokenRequest
	9,  // 18: nn.npln.auth.v1.Auth.RefreshAnonymousUserToken:input_type -> nn.npln.auth.v1.RefreshAnonymousTokenRequest
	18, // 19: nn.npln.auth.v1.Auth.ValidateToken:input_type -> google.protobuf.Empty
	11, // 20: nn.npln.auth.v1.Auth.ListUsers:input_type -> nn.npln.auth.v1.ListUsersRequest
	13, // 21: nn.npln.auth.v1.Auth.DeleteUser:input_type -> nn.npln.auth.v1.DeleteUserRequest
	16, // 22: nn.npln.auth.v1.Auth.CreateUser:output_type -> nn.npln.auth.v1.User
	2,  // 23: nn.npln.auth.v1.Auth.IssueToken:output_type -> nn.npln.auth.v1.IssueTokenResponse
	4,  // 24: nn.npln.auth.v1.Auth.RefreshToken:output_type -> nn.npln.auth.v1.RefreshTokenResponse
	6,  // 25: nn.npln.auth.v1.Auth.IssuePrearrangedUserToken:output_type -> nn.npln.auth.v1.IssuePrearrangedUserTokenResponse
	8,  // 26: nn.npln.auth.v1.Auth.IssueAnonymousUserToken:output_type -> nn.npln.auth.v1.IssueAnonymousUserTokenResponse
	10, // 27: nn.npln.auth.v1.Auth.RefreshAnonymousUserToken:output_type -> nn.npln.auth.v1.RefreshAnonymousTokenResponse
	18, // 28: nn.npln.auth.v1.Auth.ValidateToken:output_type -> google.protobuf.Empty
	12, // 29: nn.npln.auth.v1.Auth.ListUsers:output_type -> nn.npln.auth.v1.ListUsersResponse
	18, // 30: nn.npln.auth.v1.Auth.DeleteUser:output_type -> google.protobuf.Empty
	22, // [22:31] is the sub-list for method output_type
	13, // [13:22] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_auth_v1_auth_proto_init() }
func file_proto_auth_v1_auth_proto_init() {
	if File_proto_auth_v1_auth_proto != nil {
		return
	}
	file_proto_auth_v1_resources_proto_init()
	file_proto_auth_v1_auth_proto_msgTypes[15].OneofWrappers = []any{
		(*ExternalIdToken_NsaIdToken)(nil),
		(*ExternalIdToken_DummyExtIdToken)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_auth_v1_auth_proto_rawDesc), len(file_proto_auth_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_auth_v1_auth_proto_goTypes,
		DependencyIndexes: file_proto_auth_v1_auth_proto_depIdxs,
		MessageInfos:      file_proto_auth_v1_auth_proto_msgTypes,
	}.Build()
	File_proto_auth_v1_auth_proto = out.File
	file_proto_auth_v1_auth_proto_goTypes = nil
	file_proto_auth_v1_auth_proto_depIdxs = nil
}
