syntax = "proto3";

package nn.npln.toyohr.v1;

import "google/protobuf/timestamp.proto";

import "proto/common/value.proto";

option go_package = "github.com/openpak/npln/proto/toyohr/v1;toyohr";

message RegularSettings {
  repeated int32 stages = 1 [packed = true];

  nn.npln.common.MapValue attributes = 2;
}

message BankaraSettings {
  int32 rule = 1;

  repeated int32 stages = 2 [packed = true];

  nn.npln.common.MapValue attributes = 3;
}

message XSettings {
  int32 rule = 1;

  repeated int32 stages = 2 [packed = true];

  nn.npln.common.MapValue attributes = 3;
}

message LeagueSettings {
  int32 field_1 = 1;

  int32 rule = 2;

  repeated int32 stages = 3 [packed = true];

  nn.npln.common.MapValue field_4 = 4;

  nn.npln.common.MapValue field_5 = 5;
}

message VsSchedule {
  string name = 1;

  google.protobuf.Timestamp start_time = 2;

  google.protobuf.Timestamp end_time = 3;

  RegularSettings regular_settings = 4;

  repeated BankaraSettings bankara_settings = 5;

  XSettings x_settings = 6;

  LeagueSettings league_settings = 7;

  string schedule_set_id = 8;
}

message CoopSchedule {
  string name = 1;

  int32 field_2 = 2;

  string schedule_set_id = 3;

  google.protobuf.Timestamp start_time = 4;

  google.protobuf.Timestamp end_time = 5;

  Normal normal = 6;

  string shift_id = 9;

  google.protobuf.Timestamp timestamp = 10;

  message Normal {
    int32 stage = 1;

    string boss = 2;

    repeated int64 main_weapons = 3 [packed = true];

    int32 kuma_weapon = 4;

    string reward_type = 5;

    int32 reward_gear_id = 6;

    nn.npln.common.MapValue attributes = 7;
  }
}

message SeasonSchedule {
  string name = 1;

  int32 field_2 = 2;

  int32 field_3 = 3;

  google.protobuf.Timestamp start_time = 4;

  google.protobuf.Timestamp end_time = 5;

  nn.npln.common.MapValue attributes = 6;

  string schedule_set_id = 7;
}

message LeagueSchedule {
  string name = 1;

  int32 rule = 2;

  repeated int32 stages = 3 [packed = true];

  nn.npln.common.MapValue attributes = 4;

  string schedule_set_id = 5;

  google.protobuf.Timestamp timestamp = 6;

  repeated Slot slots = 7;

  google.protobuf.Timestamp start_time = 8;

  google.protobuf.Timestamp end_time = 9;

  message Slot {
    string name = 1;

    google.protobuf.Timestamp start_time = 2;

    google.protobuf.Timestamp end_time = 3;
  }
}

message VsParams {
  string name = 1;

  google.protobuf.Timestamp timestamp_1 = 2;

  google.protobuf.Timestamp timestamp_2 = 3;

  nn.npln.common.MapValue attributes = 4;

  string params_set_id = 5;
}
